(*
neuralhftokenizer
Copyright (C) 2026 Joao Paulo Schwarz Schuler

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program; if not, write to the Free Software Foundation, Inc.,
51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

Coded by Claude (AI).
*)

// neuralhftokenizer -- loads the HuggingFace single-file fast-tokenizer
// format (tokenizer.json) so the pretrained-checkpoint importers in
// neuralpretrained.pas (examples/GPT2Import, examples/LlamaImport) can take
// text prompts end to end instead of raw token ids.
//
// Supported (the two families the importers need):
//   * Byte-level BPE (GPT-2 / distilgpt2 / SmolLM2): the GPT-2
//     bytes-to-unicode alphabet, the GPT-2 pre-tokenization regex
//     ('s|'t|'re|'ve|'m|'ll|'d| ?\p{L}+| ?\p{N}+| ?[^\s\p{L}\p{N}]+|
//      \s+(?!\S)|\s+) and ranked merges.
//   * Metaspace BPE with byte fallback (Llama / TinyLlama): the
//     Prepend("▁") + Replace(" "->"▁") normalizer chain, whole-segment BPE
//     (no pre-tokenizer), <0xNN> byte-fallback tokens and the
//     Replace/ByteFallback/Fuse/Strip decoder chain.
//
// NOT supported (raises EHFTokenizerError with a clear message):
//   * model.type <> "BPE" (e.g. Unigram, WordPiece) -- the HF conversion of
//     SentencePiece Llama tokenizers is BPE, which is what ships in
//     TinyLlama / Llama-2 / SmolLM2 tokenizer.json files.
//   * The raw SentencePiece .model protobuf (use tokenizer.json instead).
//
// Unicode \p{L} / \p{N} classification for the GPT-2 regex is implemented
// over explicit ranges covering Latin (incl. Latin-1/Extended), Greek,
// Cyrillic, Armenian, Hebrew, Arabic, Devanagari, Hangul, Kana and CJK --
// an approximation of the full Unicode tables that is exact for these
// scripts; exotic codepoints outside them fall into the punctuation class.
//
// Special/added tokens are matched verbatim in the input text (HF fast
// tokenizer behavior) and their ids are exposed (BosId/EosId/UnkId), but
// they are never auto-injected: Encode('hello') returns only content ids.
//
// Parity with HF `tokenizers` is pinned by tests/TestNeuralHFTokenizer.pas
// against fixtures generated by tools/hf_tokenizer_fixture.py.

unit neuralhftokenizer;
{$include neuralnetwork.inc}
{$H+}

interface

uses
  Classes, SysUtils, neuralvolume;

type
  EHFTokenizerError = class(Exception);

  TNeuralAddedToken = record
    Content: string;
    Id: integer;
    Special: boolean;
  end;

  { TNeuralHFTokenizer }
  // Encoder/decoder for the HuggingFace tokenizer.json fast-tokenizer
  // format (byte-level BPE and metaspace/byte-fallback BPE).
  // Coded by Claude (AI).
  TNeuralHFTokenizer = class(TObject)
    private
      FVocab: TStringList;        // token -> id (Objects hold the id)
      FMerges: TStringList;       // left#1right -> rank (Objects hold rank)
      FIdToToken: array of string;
      FAddedTokens: array of TNeuralAddedToken;
      // model flags
      FByteFallback, FFuseUnk, FIgnoreMerges: boolean;
      FUnkId, FBosId, FEosId: integer;
      // pre-tokenizer / normalizer
      FByteLevel: boolean;        // ByteLevel pre-tokenizer present
      FAddPrefixSpace: boolean;
      FNormPrepend: string;       // Prepend normalizer content ('' = none)
      FNormReplaceFrom: array of string; // Replace normalizers, in order
      FNormReplaceTo: array of string;
      // decoder
      FDecReplaceFrom: array of string;  // decoder Replace rules, in order
      FDecReplaceTo: array of string;
      FDecStripLeft: integer;     // decoder Strip(' ', start, 0)
      // GPT-2 bytes<->unicode table
      FByteToCP: array[0..255] of cardinal;
      FCPToByte: array[0..$143] of integer;
      FKeysMangled: boolean;
      procedure DetectKeyMangling();
      function FixJSONKey(const Key: string): string;
      procedure BuildByteTable();
      procedure ClearState();
      function VocabFind(const Token: string): integer; // id or -1
      function MergeRank(const A, B: string): integer;  // rank or MaxInt
      procedure BPEWord(const Symbols: TStringList; Ids: TIntegerList);
      procedure EmitTokenOrFallback(const Symbol: string; Ids: TIntegerList);
      procedure EncodeSegment(const Segment: string; Ids: TIntegerList);
      procedure ByteLevelPieces(const Segment: string; Pieces: TStringList);
      function MapPieceToByteLevel(const Piece: string): TStringList;
      function FindAddedToken(const Text: string; Position: integer;
        out TokenIndex: integer): boolean;
      function IsAddedTokenId(Id: integer; out TokenIndex: integer): boolean;
    public
      constructor Create();
      destructor Destroy(); override;

      // Loads a HuggingFace tokenizer.json file.
      procedure LoadFromFile(const FileName: string);

      // Text -> token ids. Special tokens are matched if present verbatim
      // in the text but never auto-injected.
      procedure Encode(const Text: string; Ids: TIntegerList); overload;
      function Encode(const Text: string): TNeuralIntegerArray; overload;

      // Token ids -> text. SkipSpecialTokens drops added special tokens
      // (BOS/EOS/...) from the output, like HF decode(skip_special_tokens).
      function Decode(const Ids: array of integer;
        SkipSpecialTokens: boolean = true): string; overload;
      function Decode(Ids: TIntegerList;
        SkipSpecialTokens: boolean = true): string; overload;
      function DecodeToken(Id: integer): string;

      function GetVocabSize(): integer;
      function TokenToId(const Token: string): integer; // -1 if absent
      function IdToToken(Id: integer): string;
      function AddedTokenCount(): integer;
      function GetAddedToken(Index: integer): TNeuralAddedToken;

      property UnkId: integer read FUnkId; // -1 if none
      property BosId: integer read FBosId; // -1 if none
      property EosId: integer read FEosId; // -1 if none
      property IsByteLevel: boolean read FByteLevel;
  end;

implementation

uses
  fpjson, jsonparser, Math;

const
  csMergeSep = #1;
  csMetaspace = #$E2#$96#$81; // '▁' U+2581 in UTF-8

{ ---------------------------------------------------------------- }
{ UTF-8 helpers                                                     }
{ ---------------------------------------------------------------- }

// Decodes the codepoint starting at byte Position (1-based); advances
// Position past it. Invalid bytes are returned as-is (latin-1 style).
function NextCodePoint(const S: string; var Position: integer): cardinal;
var
  B: byte;
  Extra, Cnt: integer;
begin
  B := Ord(S[Position]);
  Inc(Position);
  if B < $80 then Exit(B);
  if (B and $E0) = $C0 then begin Result := B and $1F; Extra := 1; end
  else if (B and $F0) = $E0 then begin Result := B and $0F; Extra := 2; end
  else if (B and $F8) = $F0 then begin Result := B and $07; Extra := 3; end
  else Exit(B); // invalid lead byte
  for Cnt := 1 to Extra do
  begin
    if (Position > Length(S)) or ((Ord(S[Position]) and $C0) <> $80) then
      Exit(B); // truncated/invalid sequence
    Result := (Result shl 6) or (cardinal(Ord(S[Position])) and $3F);
    Inc(Position);
  end;
end;

function CodePointToUTF8(CP: cardinal): string;
begin
  if CP < $80 then
    Result := Chr(CP)
  else if CP < $800 then
    Result := Chr($C0 or (CP shr 6)) + Chr($80 or (CP and $3F))
  else if CP < $10000 then
    Result := Chr($E0 or (CP shr 12)) + Chr($80 or ((CP shr 6) and $3F)) +
      Chr($80 or (CP and $3F))
  else
    Result := Chr($F0 or (CP shr 18)) + Chr($80 or ((CP shr 12) and $3F)) +
      Chr($80 or ((CP shr 6) and $3F)) + Chr($80 or (CP and $3F));
end;

{ ---------------------------------------------------------------- }
{ Unicode character classes for the GPT-2 pre-tokenization regex    }
{ ---------------------------------------------------------------- }

function IsWhitespaceCP(CP: cardinal): boolean;
begin
  Result := ((CP >= 9) and (CP <= 13)) or (CP = 32) or (CP = $85) or
    (CP = $A0) or (CP = $1680) or ((CP >= $2000) and (CP <= $200A)) or
    (CP = $2028) or (CP = $2029) or (CP = $202F) or (CP = $205F) or
    (CP = $3000);
end;

// \p{L} over the major scripts (see unit header for the approximation).
function IsLetterCP(CP: cardinal): boolean;
begin
  Result :=
    ((CP >= Ord('A')) and (CP <= Ord('Z'))) or
    ((CP >= Ord('a')) and (CP <= Ord('z'))) or
    (CP = $AA) or (CP = $B5) or (CP = $BA) or
    ((CP >= $C0) and (CP <= $D6)) or
    ((CP >= $D8) and (CP <= $F6)) or
    ((CP >= $F8) and (CP <= $2C1)) or            // Latin Extended-A/B, IPA
    ((CP >= $370) and (CP <= $3FF) and (CP <> $375) and (CP <> $378) and
      (CP <> $379) and (CP <> $37E) and (CP <> $384) and (CP <> $385) and
      (CP <> $387) and (CP <> $38B) and (CP <> $38D) and (CP <> $3A2)) or
    ((CP >= $400) and (CP <= $481)) or           // Cyrillic
    ((CP >= $48A) and (CP <= $52F)) or
    ((CP >= $531) and (CP <= $556)) or           // Armenian
    ((CP >= $561) and (CP <= $587)) or
    ((CP >= $5D0) and (CP <= $5EA)) or           // Hebrew
    ((CP >= $620) and (CP <= $64A)) or           // Arabic
    ((CP >= $671) and (CP <= $6D3)) or
    ((CP >= $904) and (CP <= $939)) or           // Devanagari
    ((CP >= $1E00) and (CP <= $1FBC)) or         // Latin Ext Additional/Greek Ext
    ((CP >= $3041) and (CP <= $3096)) or         // Hiragana
    ((CP >= $30A1) and (CP <= $30FA)) or         // Katakana
    ((CP >= $4E00) and (CP <= $9FFF)) or         // CJK Unified
    ((CP >= $AC00) and (CP <= $D7A3));           // Hangul
end;

// \p{N} over the common ranges (Nd digits + frequent No like ², ½).
function IsNumberCP(CP: cardinal): boolean;
begin
  Result :=
    ((CP >= Ord('0')) and (CP <= Ord('9'))) or
    (CP = $B2) or (CP = $B3) or (CP = $B9) or
    ((CP >= $BC) and (CP <= $BE)) or
    ((CP >= $660) and (CP <= $669)) or           // Arabic-Indic
    ((CP >= $6F0) and (CP <= $6F9)) or
    ((CP >= $966) and (CP <= $96F)) or           // Devanagari
    ((CP >= $FF10) and (CP <= $FF19));           // Fullwidth
end;

{ ---------------------------------------------------------------- }
{ fpjson portability helpers                                        }
{ ---------------------------------------------------------------- }

// fpjson converts \uXXXX escapes through the widestring manager; without
// one installed (plain FPC programs that don't use LazUTF8/cwstring) every
// non-ASCII escape decodes to '?'. Decode them to raw UTF-8 up front so
// parsing is environment-independent. Backslash handling is exact: the
// scan steps over every two-character escape, so "\\u0041" (literal
// backslash) is never decoded.
function DecodeUnicodeEscapes(const S: string): string;
var
  Position, Total: integer;
  CP, LowCP: cardinal;

  function HexAt(StartPos: integer; out Value: cardinal): boolean;
  var
    Cnt: integer;
    Digit: char;
  begin
    Value := 0;
    Result := StartPos + 3 <= Length(S);
    if not Result then exit;
    for Cnt := StartPos to StartPos + 3 do
    begin
      Digit := S[Cnt];
      case Digit of
        '0'..'9': Value := (Value shl 4) or cardinal(Ord(Digit) - Ord('0'));
        'a'..'f': Value := (Value shl 4) or cardinal(Ord(Digit) - Ord('a') + 10);
        'A'..'F': Value := (Value shl 4) or cardinal(Ord(Digit) - Ord('A') + 10);
        else Exit(false);
      end;
    end;
  end;

begin
  Result := '';
  Total := Length(S);
  Position := 1;
  while Position <= Total do
  begin
    if (S[Position] = '\') and (Position < Total) then
    begin
      if (S[Position + 1] = 'u') and HexAt(Position + 2, CP) then
      begin
        Inc(Position, 6);
        if (CP >= $D800) and (CP <= $DBFF) and (Position + 1 <= Total) and
          (S[Position] = '\') and (S[Position + 1] = 'u') and
          HexAt(Position + 2, LowCP) and (LowCP >= $DC00) and
          (LowCP <= $DFFF) then
        begin // surrogate pair
          CP := $10000 + ((CP - $D800) shl 10) + (LowCP - $DC00);
          Inc(Position, 6);
        end;
        Result := Result + CodePointToUTF8(CP);
      end
      else
      begin // any other escape: copy verbatim, never reinterpret char 2
        Result := Result + S[Position] + S[Position + 1];
        Inc(Position, 2);
      end;
    end
    else
    begin
      Result := Result + S[Position];
      Inc(Position);
    end;
  end;
end;

{ ---------------------------------------------------------------- }
{ TNeuralHFTokenizer                                                }
{ ---------------------------------------------------------------- }

constructor TNeuralHFTokenizer.Create();
begin
  inherited Create();
  FVocab := TStringList.Create();
  FVocab.Sorted := true;
  FVocab.CaseSensitive := true;
  FVocab.UseLocale := false;
  FVocab.Duplicates := dupIgnore;
  FMerges := TStringList.Create();
  FMerges.Sorted := true;
  FMerges.CaseSensitive := true;
  FMerges.UseLocale := false;
  FMerges.Duplicates := dupIgnore;
  BuildByteTable();
  ClearState();
end;

destructor TNeuralHFTokenizer.Destroy();
begin
  FMerges.Free;
  FVocab.Free;
  inherited Destroy();
end;

procedure TNeuralHFTokenizer.ClearState();
begin
  FVocab.Clear;
  FMerges.Clear;
  SetLength(FIdToToken, 0);
  SetLength(FAddedTokens, 0);
  SetLength(FNormReplaceFrom, 0);
  SetLength(FNormReplaceTo, 0);
  SetLength(FDecReplaceFrom, 0);
  SetLength(FDecReplaceTo, 0);
  FByteFallback := false;
  FFuseUnk := false;
  FIgnoreMerges := false;
  FByteLevel := false;
  FAddPrefixSpace := false;
  FNormPrepend := '';
  FDecStripLeft := 0;
  FUnkId := -1;
  FBosId := -1;
  FEosId := -1;
end;

// The GPT-2 bytes-to-unicode table: printable latin-1 bytes map to
// themselves; the rest map to 256, 257, ... in byte order.
procedure TNeuralHFTokenizer.BuildByteTable();
var
  B, Shifted: integer;
  CP: cardinal;
begin
  for B := 0 to High(FCPToByte) do FCPToByte[B] := -1;
  Shifted := 0;
  for B := 0 to 255 do
  begin
    if ((B >= 33) and (B <= 126)) or ((B >= 161) and (B <= 172)) or
      (B >= 174) then
      CP := cardinal(B)
    else
    begin
      CP := cardinal(256 + Shifted);
      Inc(Shifted);
    end;
    FByteToCP[B] := CP;
    FCPToByte[CP] := B;
  end;
end;

// fpjson stores object keys as raw bytes but converts them through the
// widestring manager on retrieval; in programs without a UTF-8 manager
// (no LazUTF8/cwstring) each raw UTF-8 byte of a key comes back latin-1
// re-encoded. The conversion is injective, so probe once with a known
// non-ASCII key and invert it when present.
// Parses JSON WITHOUT joUTF8: with that option (the GetJSON default) the
// scanner pipes string values through the widestring manager, which turns
// non-ASCII into '?' in programs without a UTF-8 manager. Without it the
// scanner copies raw bytes, which is exactly right for UTF-8 files whose
// \uXXXX escapes were already decoded by DecodeUnicodeEscapes.
function ParseJSONRaw(const S: string): TJSONData;
var
  Parser: TJSONParser;
begin
  Parser := TJSONParser.Create(S, []);
  try
    Result := Parser.Parse;
  finally
    Parser.Free;
  end;
end;

procedure TNeuralHFTokenizer.DetectKeyMangling();
var
  Probe: TJSONData;
  Key: string;
begin
  Probe := ParseJSONRaw('{"' + #$C3#$A2 + '": 1}');
  try
    Key := TJSONObject(Probe).Names[0];
  finally
    Probe.Free;
  end;
  if Key = #$C3#$A2 then
    FKeysMangled := false
  else if Key = #$C3#$83#$C2#$A2 then
    FKeysMangled := true
  else
    raise EHFTokenizerError.Create('Unsupported string codepage ' +
      'environment: JSON keys decode neither raw nor latin-1 re-encoded. ' +
      'Add the LazUTF8 (or cwstring) unit to your program.');
end;

function TNeuralHFTokenizer.FixJSONKey(const Key: string): string;
var
  Position: integer;
  CP: cardinal;
begin
  if not FKeysMangled then Exit(Key);
  Result := '';
  Position := 1;
  while Position <= Length(Key) do
  begin
    CP := NextCodePoint(Key, Position);
    if CP > 255 then Exit(Key); // not the latin-1 pattern: keep verbatim
    Result := Result + Chr(CP);
  end;
end;

function TNeuralHFTokenizer.VocabFind(const Token: string): integer;
var
  Idx: integer;
begin
  if FVocab.Find(Token, Idx)
  then Result := integer(PtrInt(FVocab.Objects[Idx]))
  else Result := -1;
end;

function TNeuralHFTokenizer.MergeRank(const A, B: string): integer;
var
  Idx: integer;
begin
  if FMerges.Find(A + csMergeSep + B, Idx)
  then Result := integer(PtrInt(FMerges.Objects[Idx]))
  else Result := High(integer);
end;

procedure TNeuralHFTokenizer.LoadFromFile(const FileName: string);
var
  Root: TJSONData;
  RootObj, ModelObj, Entry: TJSONObject;
  VocabObj: TJSONObject;
  MergesArr, AddedArr, SubArr: TJSONArray;
  FS: TFileStream;
  Cnt, TokenId, MaxId: integer;
  Left, Right, MergeStr, NormType, Content: string;
  SpacePos: integer;
  Node: TJSONData;

  procedure AddNormalizer(NormObj: TJSONObject);
  var
    Kind: string;
    InnerArr: TJSONArray;
    InnerCnt: integer;
  begin
    Kind := NormObj.Get('type', '');
    if Kind = 'Sequence' then
    begin
      InnerArr := NormObj.Arrays['normalizers'];
      for InnerCnt := 0 to InnerArr.Count - 1 do
        AddNormalizer(InnerArr.Objects[InnerCnt]);
    end
    else if Kind = 'Prepend' then
      FNormPrepend := NormObj.Get('prepend', '')
    else if Kind = 'Replace' then
    begin
      SetLength(FNormReplaceFrom, Length(FNormReplaceFrom) + 1);
      SetLength(FNormReplaceTo, Length(FNormReplaceTo) + 1);
      FNormReplaceFrom[High(FNormReplaceFrom)] :=
        NormObj.Objects['pattern'].Get('String', '');
      FNormReplaceTo[High(FNormReplaceTo)] := NormObj.Get('content', '');
    end
    else
      raise EHFTokenizerError.Create('Unsupported normalizer type: ' + Kind);
  end;

  procedure AddPreTokenizer(PreObj: TJSONObject);
  var
    Kind: string;
    InnerArr: TJSONArray;
    InnerCnt: integer;
  begin
    Kind := PreObj.Get('type', '');
    if Kind = 'Sequence' then
    begin
      InnerArr := PreObj.Arrays['pretokenizers'];
      for InnerCnt := 0 to InnerArr.Count - 1 do
        AddPreTokenizer(InnerArr.Objects[InnerCnt]);
    end
    else if Kind = 'ByteLevel' then
    begin
      FByteLevel := true;
      FAddPrefixSpace := PreObj.Get('add_prefix_space', false);
    end
    else
      raise EHFTokenizerError.Create(
        'Unsupported pre_tokenizer type: ' + Kind);
  end;

  procedure AddDecoder(DecObj: TJSONObject);
  var
    Kind: string;
    InnerArr: TJSONArray;
    InnerCnt: integer;
  begin
    Kind := DecObj.Get('type', '');
    if Kind = 'Sequence' then
    begin
      InnerArr := DecObj.Arrays['decoders'];
      for InnerCnt := 0 to InnerArr.Count - 1 do
        AddDecoder(InnerArr.Objects[InnerCnt]);
    end
    else if Kind = 'Replace' then
    begin
      SetLength(FDecReplaceFrom, Length(FDecReplaceFrom) + 1);
      SetLength(FDecReplaceTo, Length(FDecReplaceTo) + 1);
      FDecReplaceFrom[High(FDecReplaceFrom)] :=
        DecObj.Objects['pattern'].Get('String', '');
      FDecReplaceTo[High(FDecReplaceTo)] := DecObj.Get('content', '');
    end
    else if Kind = 'Strip' then
      FDecStripLeft := DecObj.Get('start', 0)
    else if (Kind = 'ByteLevel') or (Kind = 'ByteFallback') or
      (Kind = 'Fuse') then
      // ByteLevel/ByteFallback decoding is keyed off the model flags;
      // Fuse only concatenates, which Decode does anyway.
    else
      raise EHFTokenizerError.Create('Unsupported decoder type: ' + Kind);
  end;

var
  RawJson: string;
begin
  ClearState();
  DetectKeyMangling();
  FS := TFileStream.Create(FileName, fmOpenRead or fmShareDenyWrite);
  try
    SetLength(RawJson, FS.Size);
    if FS.Size > 0 then FS.ReadBuffer(RawJson[1], FS.Size);
  finally
    FS.Free;
  end;
  // decode \uXXXX up front (see DecodeUnicodeEscapes) and parse raw
  Root := ParseJSONRaw(DecodeUnicodeEscapes(RawJson));
  try
    if not (Root is TJSONObject) then
      raise EHFTokenizerError.Create('tokenizer.json: root is not an object');
    RootObj := TJSONObject(Root);

    // ---- model -------------------------------------------------
    ModelObj := RootObj.Objects['model'];
    if ModelObj.Get('type', '') <> 'BPE' then
      raise EHFTokenizerError.Create('Unsupported model.type "' +
        ModelObj.Get('type', '') +
        '" (only BPE is supported; Unigram is not)');
    FByteFallback := ModelObj.Get('byte_fallback', false);
    FFuseUnk := ModelObj.Get('fuse_unk', false);
    FIgnoreMerges := ModelObj.Get('ignore_merges', false);

    // vocab: token -> id
    VocabObj := ModelObj.Objects['vocab'];
    MaxId := -1;
    for Cnt := 0 to VocabObj.Count - 1 do
      MaxId := Max(MaxId, VocabObj.Items[Cnt].AsInteger);
    SetLength(FIdToToken, MaxId + 1);
    for Cnt := 0 to VocabObj.Count - 1 do
    begin
      TokenId := VocabObj.Items[Cnt].AsInteger;
      Content := FixJSONKey(VocabObj.Names[Cnt]);
      FVocab.AddObject(Content, TObject(PtrInt(TokenId)));
      FIdToToken[TokenId] := Content;
    end;

    // merges: ["a b", ...] (old) or [["a","b"], ...] (new)
    MergesArr := ModelObj.Arrays['merges'];
    for Cnt := 0 to MergesArr.Count - 1 do
    begin
      Node := MergesArr.Items[Cnt];
      if Node is TJSONArray then
      begin
        SubArr := TJSONArray(Node);
        Left := SubArr.Strings[0];
        Right := SubArr.Strings[1];
      end
      else
      begin
        MergeStr := Node.AsString;
        SpacePos := Pos(' ', MergeStr);
        Left := Copy(MergeStr, 1, SpacePos - 1);
        Right := Copy(MergeStr, SpacePos + 1, Length(MergeStr));
      end;
      FMerges.AddObject(Left + csMergeSep + Right, TObject(PtrInt(Cnt)));
    end;

    // unk token
    Node := ModelObj.Find('unk_token');
    if (Node <> nil) and not Node.IsNull then
      FUnkId := VocabFind(Node.AsString);

    // ---- added tokens -------------------------------------------
    Node := RootObj.Find('added_tokens');
    if (Node <> nil) and (Node is TJSONArray) then
    begin
      AddedArr := TJSONArray(Node);
      SetLength(FAddedTokens, AddedArr.Count);
      for Cnt := 0 to AddedArr.Count - 1 do
      begin
        Entry := AddedArr.Objects[Cnt];
        FAddedTokens[Cnt].Content := Entry.Get('content', '');
        FAddedTokens[Cnt].Id := Entry.Get('id', -1);
        FAddedTokens[Cnt].Special := Entry.Get('special', false);
        Content := FAddedTokens[Cnt].Content;
        if FAddedTokens[Cnt].Special then
        begin
          if (Content = '<s>') or (Content = '<|startoftext|>') then
            FBosId := FAddedTokens[Cnt].Id;
          if (Content = '</s>') or (Content = '<|endoftext|>') or
            (Content = '<|im_end|>') then
            FEosId := FAddedTokens[Cnt].Id;
          if (Content = '<unk>') and (FUnkId < 0) then
            FUnkId := FAddedTokens[Cnt].Id;
        end;
      end;
      // GPT-2 family: <|endoftext|> doubles as BOS.
      if (FBosId < 0) and (FEosId >= 0) then FBosId := FEosId;
    end;

    // ---- normalizer / pre_tokenizer / decoder -------------------
    Node := RootObj.Find('normalizer');
    if (Node <> nil) and (Node is TJSONObject) then
      AddNormalizer(TJSONObject(Node));
    Node := RootObj.Find('pre_tokenizer');
    if (Node <> nil) and (Node is TJSONObject) then
      AddPreTokenizer(TJSONObject(Node));
    Node := RootObj.Find('decoder');
    if (Node <> nil) and (Node is TJSONObject) then
      AddDecoder(TJSONObject(Node));
  finally
    Root.Free;
  end;
end;

function TNeuralHFTokenizer.FindAddedToken(const Text: string;
  Position: integer; out TokenIndex: integer): boolean;
var
  Cnt, BestLen, ContentLen: integer;
begin
  Result := false;
  TokenIndex := -1;
  BestLen := 0;
  for Cnt := 0 to High(FAddedTokens) do
  begin
    ContentLen := Length(FAddedTokens[Cnt].Content);
    if (ContentLen > BestLen) and
      (Copy(Text, Position, ContentLen) = FAddedTokens[Cnt].Content) then
    begin
      BestLen := ContentLen;
      TokenIndex := Cnt;
      Result := true;
    end;
  end;
end;

function TNeuralHFTokenizer.IsAddedTokenId(Id: integer;
  out TokenIndex: integer): boolean;
var
  Cnt: integer;
begin
  Result := false;
  TokenIndex := -1;
  for Cnt := 0 to High(FAddedTokens) do
    if FAddedTokens[Cnt].Id = Id then
    begin
      TokenIndex := Cnt;
      Exit(true);
    end;
end;

// Splits a byte-level segment with the GPT-2 pre-tokenization regex:
// 's|'t|'re|'ve|'m|'ll|'d| ?\p{L}+| ?\p{N}+| ?[^\s\p{L}\p{N}]+|\s+(?!\S)|\s+
procedure TNeuralHFTokenizer.ByteLevelPieces(const Segment: string;
  Pieces: TStringList);
var
  CPs: array of cardinal;
  CPStr: array of string;
  Total, Position, Idx, RunStart, RunEnd: integer;

  function Collect(StartIdx, EndIdx: integer): string;
  var
    J: integer;
  begin
    Result := '';
    for J := StartIdx to EndIdx do Result := Result + CPStr[J];
  end;

  function MatchContraction(StartIdx: integer): integer; // length or 0
  begin
    Result := 0;
    if CPs[StartIdx] <> Ord('''') then Exit;
    if StartIdx + 1 <= High(CPs) then
    begin
      if (CPs[StartIdx + 1] = Ord('s')) or (CPs[StartIdx + 1] = Ord('t')) or
        (CPs[StartIdx + 1] = Ord('m')) or (CPs[StartIdx + 1] = Ord('d')) then
        Exit(2);
      if StartIdx + 2 <= High(CPs) then
      begin
        if ((CPs[StartIdx + 1] = Ord('r')) and (CPs[StartIdx + 2] = Ord('e')))
          or ((CPs[StartIdx + 1] = Ord('v')) and (CPs[StartIdx + 2] = Ord('e')))
          or ((CPs[StartIdx + 1] = Ord('l')) and (CPs[StartIdx + 2] = Ord('l')))
        then Exit(3);
      end;
    end;
  end;

  function IsOtherCP(CP: cardinal): boolean; // [^\s\p{L}\p{N}]
  begin
    Result := (not IsWhitespaceCP(CP)) and (not IsLetterCP(CP)) and
      (not IsNumberCP(CP));
  end;

begin
  // decode UTF-8 into codepoint arrays
  SetLength(CPs, Length(Segment));
  SetLength(CPStr, Length(Segment));
  Total := 0;
  Position := 1;
  while Position <= Length(Segment) do
  begin
    RunStart := Position;
    CPs[Total] := NextCodePoint(Segment, Position);
    CPStr[Total] := Copy(Segment, RunStart, Position - RunStart);
    Inc(Total);
  end;
  SetLength(CPs, Total);
  SetLength(CPStr, Total);

  Idx := 0;
  while Idx < Total do
  begin
    // contractions
    RunEnd := MatchContraction(Idx);
    if RunEnd > 0 then
    begin
      Pieces.Add(Collect(Idx, Idx + RunEnd - 1));
      Inc(Idx, RunEnd);
      continue;
    end;
    if (CPs[Idx] = 32) and (Idx + 1 < Total) and IsLetterCP(CPs[Idx + 1]) then
    begin // " ?\p{L}+"
      RunEnd := Idx + 1;
      while (RunEnd + 1 < Total) and IsLetterCP(CPs[RunEnd + 1]) do
        Inc(RunEnd);
      Pieces.Add(Collect(Idx, RunEnd));
      Idx := RunEnd + 1;
    end
    else if (CPs[Idx] = 32) and (Idx + 1 < Total) and
      IsNumberCP(CPs[Idx + 1]) then
    begin // " ?\p{N}+"
      RunEnd := Idx + 1;
      while (RunEnd + 1 < Total) and IsNumberCP(CPs[RunEnd + 1]) do
        Inc(RunEnd);
      Pieces.Add(Collect(Idx, RunEnd));
      Idx := RunEnd + 1;
    end
    else if (CPs[Idx] = 32) and (Idx + 1 < Total) and
      (not IsWhitespaceCP(CPs[Idx + 1])) then
    begin // " ?[^\s\p{L}\p{N}]+"
      RunEnd := Idx + 1;
      while (RunEnd + 1 < Total) and IsOtherCP(CPs[RunEnd + 1]) do
        Inc(RunEnd);
      Pieces.Add(Collect(Idx, RunEnd));
      Idx := RunEnd + 1;
    end
    else if IsLetterCP(CPs[Idx]) then
    begin
      RunEnd := Idx;
      while (RunEnd + 1 < Total) and IsLetterCP(CPs[RunEnd + 1]) do
        Inc(RunEnd);
      Pieces.Add(Collect(Idx, RunEnd));
      Idx := RunEnd + 1;
    end
    else if IsNumberCP(CPs[Idx]) then
    begin
      RunEnd := Idx;
      while (RunEnd + 1 < Total) and IsNumberCP(CPs[RunEnd + 1]) do
        Inc(RunEnd);
      Pieces.Add(Collect(Idx, RunEnd));
      Idx := RunEnd + 1;
    end
    else if not IsWhitespaceCP(CPs[Idx]) then
    begin
      RunEnd := Idx;
      while (RunEnd + 1 < Total) and IsOtherCP(CPs[RunEnd + 1]) do
        Inc(RunEnd);
      Pieces.Add(Collect(Idx, RunEnd));
      Idx := RunEnd + 1;
    end
    else
    begin // whitespace run: \s+(?!\S) | \s+
      RunEnd := Idx;
      while (RunEnd + 1 < Total) and IsWhitespaceCP(CPs[RunEnd + 1]) do
        Inc(RunEnd);
      if (RunEnd + 1 < Total) and (RunEnd > Idx) then
      begin
        // leave the last whitespace char to (possibly) attach to the
        // next piece via the " ?" prefixes
        Pieces.Add(Collect(Idx, RunEnd - 1));
        Idx := RunEnd;
      end
      else
      begin
        Pieces.Add(Collect(Idx, RunEnd));
        Idx := RunEnd + 1;
      end;
    end;
  end;
end;

// Maps a raw piece to its byte-level alphabet symbols (one mapped
// codepoint per input byte). Caller frees the result.
function TNeuralHFTokenizer.MapPieceToByteLevel(
  const Piece: string): TStringList;
var
  Cnt: integer;
begin
  Result := TStringList.Create();
  for Cnt := 1 to Length(Piece) do
    Result.Add(CodePointToUTF8(FByteToCP[Ord(Piece[Cnt])]));
end;

procedure TNeuralHFTokenizer.EmitTokenOrFallback(const Symbol: string;
  Ids: TIntegerList);
var
  TokenId, Cnt: integer;
  ByteToken: string;
begin
  TokenId := VocabFind(Symbol);
  if TokenId >= 0 then
  begin
    Ids.Add(TokenId);
    Exit;
  end;
  if FByteFallback then
  begin
    // check all byte tokens exist before emitting any
    for Cnt := 1 to Length(Symbol) do
      if VocabFind('<0x' + IntToHex(Ord(Symbol[Cnt]), 2) + '>') < 0 then
      begin
        if (FUnkId >= 0) and ((not FFuseUnk) or (Ids.Count = 0) or
          (Ids[Ids.Count - 1] <> FUnkId)) then
          Ids.Add(FUnkId);
        Exit;
      end;
    for Cnt := 1 to Length(Symbol) do
    begin
      ByteToken := '<0x' + IntToHex(Ord(Symbol[Cnt]), 2) + '>';
      Ids.Add(VocabFind(ByteToken));
    end;
  end
  else if (FUnkId >= 0) and ((not FFuseUnk) or (Ids.Count = 0) or
    (Ids[Ids.Count - 1] <> FUnkId)) then
    Ids.Add(FUnkId);
end;

// Ranked BPE merge loop over the symbols of one word/piece.
procedure TNeuralHFTokenizer.BPEWord(const Symbols: TStringList;
  Ids: TIntegerList);
var
  Cnt, BestIdx, BestRank, Rank, WholeId: integer;
  Whole: string;
begin
  if Symbols.Count = 0 then exit;
  if FIgnoreMerges then
  begin
    Whole := '';
    for Cnt := 0 to Symbols.Count - 1 do Whole := Whole + Symbols[Cnt];
    WholeId := VocabFind(Whole);
    if WholeId >= 0 then
    begin
      Ids.Add(WholeId);
      Exit;
    end;
  end;
  while Symbols.Count > 1 do
  begin
    BestIdx := -1;
    BestRank := High(integer);
    for Cnt := 0 to Symbols.Count - 2 do
    begin
      Rank := MergeRank(Symbols[Cnt], Symbols[Cnt + 1]);
      if Rank < BestRank then
      begin
        BestRank := Rank;
        BestIdx := Cnt;
      end;
    end;
    if BestIdx < 0 then break;
    Symbols[BestIdx] := Symbols[BestIdx] + Symbols[BestIdx + 1];
    Symbols.Delete(BestIdx + 1);
  end;
  for Cnt := 0 to Symbols.Count - 1 do
    EmitTokenOrFallback(Symbols[Cnt], Ids);
end;

procedure TNeuralHFTokenizer.EncodeSegment(const Segment: string;
  Ids: TIntegerList);
var
  Pieces, Symbols: TStringList;
  Cnt, Position, RunStart: integer;
  Normalized: string;
begin
  if Segment = '' then exit;
  if FByteLevel then
  begin
    Normalized := Segment;
    if FAddPrefixSpace and (Normalized[1] <> ' ') then
      Normalized := ' ' + Normalized;
    Pieces := TStringList.Create();
    try
      ByteLevelPieces(Normalized, Pieces);
      for Cnt := 0 to Pieces.Count - 1 do
      begin
        Symbols := MapPieceToByteLevel(Pieces[Cnt]);
        try
          BPEWord(Symbols, Ids);
        finally
          Symbols.Free;
        end;
      end;
    finally
      Pieces.Free;
    end;
  end
  else
  begin
    // metaspace family: normalize, then whole-segment BPE over codepoints
    Normalized := FNormPrepend + Segment;
    for Cnt := 0 to High(FNormReplaceFrom) do
      Normalized := StringReplace(Normalized, FNormReplaceFrom[Cnt],
        FNormReplaceTo[Cnt], [rfReplaceAll]);
    Symbols := TStringList.Create();
    try
      Position := 1;
      while Position <= Length(Normalized) do
      begin
        RunStart := Position;
        NextCodePoint(Normalized, Position);
        Symbols.Add(Copy(Normalized, RunStart, Position - RunStart));
      end;
      BPEWord(Symbols, Ids);
    finally
      Symbols.Free;
    end;
  end;
end;

procedure TNeuralHFTokenizer.Encode(const Text: string; Ids: TIntegerList);
var
  Position, SegStart, TokenIndex: integer;
begin
  if GetVocabSize() = 0 then
    raise EHFTokenizerError.Create('Encode called before LoadFromFile.');
  Position := 1;
  SegStart := 1;
  while Position <= Length(Text) do
  begin
    if FindAddedToken(Text, Position, TokenIndex) then
    begin
      if Position > SegStart then
        EncodeSegment(Copy(Text, SegStart, Position - SegStart), Ids);
      Ids.Add(FAddedTokens[TokenIndex].Id);
      Inc(Position, Length(FAddedTokens[TokenIndex].Content));
      SegStart := Position;
    end
    else
      Inc(Position);
  end;
  if Position > SegStart then
    EncodeSegment(Copy(Text, SegStart, Position - SegStart), Ids);
end;

function TNeuralHFTokenizer.Encode(const Text: string): TNeuralIntegerArray;
var
  Ids: TIntegerList;
  Cnt: integer;
begin
  Ids := TIntegerList.Create();
  try
    Encode(Text, Ids);
    SetLength(Result, Ids.Count);
    for Cnt := 0 to Ids.Count - 1 do Result[Cnt] := Ids[Cnt];
  finally
    Ids.Free;
  end;
end;

// Decodes one NON-added token id to its surface text (byte-level unmapping
// or metaspace replacement + byte-fallback included).
function TNeuralHFTokenizer.DecodeToken(Id: integer): string;
var
  Token: string;
  Position, ByteVal, Cnt: integer;
  CP: cardinal;
begin
  Result := '';
  if (Id < 0) or (Id > High(FIdToToken)) then exit;
  Token := FIdToToken[Id];
  if FByteLevel then
  begin
    Position := 1;
    while Position <= Length(Token) do
    begin
      CP := NextCodePoint(Token, Position);
      if (CP <= cardinal(High(FCPToByte))) and (FCPToByte[CP] >= 0)
      then Result := Result + Chr(FCPToByte[CP])
      else Result := Result + CodePointToUTF8(CP);
    end;
  end
  else
  begin
    // byte-fallback token? "<0xNN>"
    if FByteFallback and (Length(Token) = 6) and (Copy(Token, 1, 3) = '<0x')
      and (Token[6] = '>') then
    begin
      ByteVal := StrToIntDef('$' + Copy(Token, 4, 2), -1);
      if ByteVal >= 0 then Exit(Chr(ByteVal));
    end;
    Result := Token;
    for Cnt := 0 to High(FDecReplaceFrom) do
      Result := StringReplace(Result, FDecReplaceFrom[Cnt],
        FDecReplaceTo[Cnt], [rfReplaceAll]);
  end;
end;

function TNeuralHFTokenizer.Decode(const Ids: array of integer;
  SkipSpecialTokens: boolean = true): string;
var
  Cnt, TokenIndex, Stripped: integer;
begin
  Result := '';
  for Cnt := 0 to High(Ids) do
  begin
    if IsAddedTokenId(Ids[Cnt], TokenIndex) then
    begin
      if not (SkipSpecialTokens and FAddedTokens[TokenIndex].Special) then
        Result := Result + FAddedTokens[TokenIndex].Content;
    end
    else
      Result := Result + DecodeToken(Ids[Cnt]);
  end;
  // decoder Strip(' ', start, 0): drop up to N leading spaces
  Stripped := 0;
  while (Stripped < FDecStripLeft) and (Length(Result) > Stripped) and
    (Result[Stripped + 1] = ' ') do
    Inc(Stripped);
  if Stripped > 0 then Delete(Result, 1, Stripped);
end;

function TNeuralHFTokenizer.Decode(Ids: TIntegerList;
  SkipSpecialTokens: boolean = true): string;
var
  Arr: array of integer;
  Cnt: integer;
begin
  SetLength(Arr, Ids.Count);
  for Cnt := 0 to Ids.Count - 1 do Arr[Cnt] := Ids[Cnt];
  Result := Decode(Arr, SkipSpecialTokens);
end;

function TNeuralHFTokenizer.GetVocabSize(): integer;
begin
  Result := Length(FIdToToken);
end;

function TNeuralHFTokenizer.TokenToId(const Token: string): integer;
var
  TokenIndex: integer;
begin
  Result := VocabFind(Token);
  if Result < 0 then
    for TokenIndex := 0 to High(FAddedTokens) do
      if FAddedTokens[TokenIndex].Content = Token then
        Exit(FAddedTokens[TokenIndex].Id);
end;

function TNeuralHFTokenizer.IdToToken(Id: integer): string;
var
  TokenIndex: integer;
begin
  if (Id >= 0) and (Id <= High(FIdToToken)) and (FIdToToken[Id] <> '')
  then Result := FIdToToken[Id]
  else if IsAddedTokenId(Id, TokenIndex)
  then Result := FAddedTokens[TokenIndex].Content
  else Result := '';
end;

function TNeuralHFTokenizer.AddedTokenCount(): integer;
begin
  Result := Length(FAddedTokens);
end;

function TNeuralHFTokenizer.GetAddedToken(Index: integer): TNeuralAddedToken;
begin
  Result := FAddedTokens[Index];
end;

end.
