program MahalanobisOOD;
(*
MahalanobisOOD: a tiny pure-CPU reproduction of Lee et al. 2018
"A Simple Unified Framework for Detecting Out-of-Distribution Samples and
Adversarial Attacks" (NeurIPS 2018).

Pipeline:
  TRAIN  -> fit a small softmax MLP on K IN-distribution Gaussian blobs
            (the classifier is then FROZEN: feature extraction is forward-only).
  FIT    -> read the PENULTIMATE-layer feature vector f for every training
            sample (NN.Layers[cPenultimateIdx].Output after NN.Compute), then
            fit one class-conditional Gaussian per class: per-class mean mu_c
            and a single SHARED (tied) covariance Sigma pooled across classes.
  SCORE  -> for a new x, score(x) = max_c -(f-mu_c)^T Sigma^-1 (f-mu_c)
            (the maximum NEGATIVE squared Mahalanobis distance over classes).
            IN-distribution points sit close to a class mean -> high score;
            OOD points sit far from every mean -> low score.

Three OOD arms are reported:
  EASY  -> far-away Gaussian blobs in a region the classifier never saw
           (+30 per coordinate). Score distributions do not overlap, so the
           AUROC pins at exactly 1.0 — kept as a baseline so the contrast with
           the harder arms is visible.
  HARD  -> a HELD-OUT-CLASS split (near-OOD): the class-conditional Gaussians
           are fit on only K-1 IN-distribution classes and the held-out class
           is treated as OOD. Its samples come from the SAME generator (one
           axis over) so its penultimate features sit near the in-dist manifold
           and the AUROC lands in a discriminating 0.8-0.99 band.
  On the HARD split we additionally contrast TIED (single pooled) covariance
  against PER-CLASS (untied) covariance and chart the AUROC delta. Tied is the
  paper's default; untied is the obvious ablation.

We report a single AUROC per arm (held-in test samples = positives, OOD =
negatives) computed via the Mann-Whitney U / rank-statistic form with
tie-averaged ranks.

Numerical note: the tied covariance Sigma is regularised with a small ridge
(+cRidge on the diagonal, cRidge = 1e-3) before inversion so the Cholesky
factorisation stays well-conditioned even when a feature is near-constant.

Built-in self-check (this is a self-checking example, since the AUROC helper
lives locally in this .lpr): the program prints PASS/FAIL and Halt(1)s if the
observed AUROC on the easy synthetic split is not > cMinAUROC (0.8).

Pure CPU, single-threaded manual training loop, runs in a few seconds.

Copyright (C) 2026 Joao Paulo Schwarz Schuler

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
any later version.

Coded by Claude (AI).
*)

{$mode objfpc}{$H+}

uses {$IFDEF UNIX} {$IFDEF UseCThreads}
  cthreads, {$ENDIF} {$ENDIF}
  Classes, SysUtils, Math,
  neuralnetwork,
  neuralvolume;

const
  cInputDim       = 8;     // input feature dimension
  cNumClasses     = 5;     // K in-distribution classes
  cFeatDim        = 16;    // penultimate-layer width (Mahalanobis works here)
  cTrainPerClass  = 200;
  cTestPerClass   = 200;   // held-in test points (positives)
  cOODCount       = 1000;  // out-of-distribution points (negatives)
  cEpochs         = 60;
  cLearningRate   = 0.03;
  cRidge          = 1e-3;  // diagonal ridge added to Sigma before inversion
  cMinAUROC       = 0.8;   // self-check threshold

  // index of the penultimate layer (the FullConnectReLU feeding the logits):
  //   0 Input  1 FCReLU  2 FCReLU(<-penultimate)  3 FCLinear  4 SoftMax
  cPenultimateIdx = 2;

  cBlobSpread     = 1.0;   // per-class Gaussian std in input space
  cClassSep       = 6.0;   // spacing between in-distribution class centres
  cOODShift       = 30.0;  // how far the EASY OOD blob sits from the in-dist cloud

  // HARD (held-out-class) split: classes 0..cHeldOutClass-1 are IN-distribution
  // (the Gaussians are fit on them); cHeldOutClass is treated as OOD. The held
  // out class is generated by the SAME MakeInSample generator, so it is a
  // genuine near-OOD sample sitting close to the in-dist feature manifold.
  cHeldOutClass   = cNumClasses - 1; // last class held out as near-OOD
  cInClasses      = cNumClasses - 1; // K-1 in-distribution classes on HARD split
  // near-OOD blobs sit at the midpoint between these two KEPT in-dist classes,
  // i.e. on the decision boundary between two clusters (genuine near-OOD).
  cNearA          = 0;
  cNearB          = 1;
  cNearOODSpread  = 2.2;   // widen the near-OOD blob so it overlaps the manifold

type
  TFeat   = array[0..cFeatDim - 1] of TNeuralFloat;
  TMatrix = array of array of TNeuralFloat;

// Why: Box-Muller gives N(0,1) samples without pulling in a dependency.
function RandomGauss(): TNeuralFloat;
var
  U1, U2: TNeuralFloat;
begin
  repeat
    U1 := Random;
  until U1 > 1e-9;
  U2 := Random;
  Result := Sqrt(-2 * Ln(U1)) * Cos(2 * Pi * U2);
end;

procedure BuildNet(out NN: TNNet);
begin
  NN := TNNet.Create();
  NN.AddLayer(TNNetInput.Create(cInputDim, 1, 1));
  NN.AddLayer(TNNetFullConnectReLU.Create(cFeatDim));
  NN.AddLayer(TNNetFullConnectReLU.Create(cFeatDim));   // penultimate (idx 2)
  NN.AddLayer(TNNetFullConnectLinear.Create(cNumClasses));
  NN.AddLayer(TNNetSoftMax.Create());
end;

// In-distribution class centre: class c lives along a coordinate axis so the
// K blobs are linearly separable but the features still need K means.
procedure ClassCenter(ClassId: integer; out C: array of TNeuralFloat);
var
  D: integer;
begin
  for D := 0 to cInputDim - 1 do C[D] := 0;
  C[ClassId mod cInputDim] := cClassSep * (1 + ClassId div cInputDim);
end;

procedure MakeInSample(ClassId: integer; X, Y: TNNetVolume);
var
  D: integer;
  C: array[0..cInputDim - 1] of TNeuralFloat;
begin
  ClassCenter(ClassId, C);
  for D := 0 to cInputDim - 1 do
    X.FData[D] := C[D] + RandomGauss() * cBlobSpread;
  Y.Fill(0);
  Y.FData[ClassId] := 1.0;
end;

// EASY OOD sample: a Gaussian blob shifted far from every in-distribution
// centre. Lands in a region of feature space the classifier never saw, so its
// Mahalanobis score is hugely negative and the split is trivially separable.
procedure MakeOODSample(X: TNNetVolume);
var
  D: integer;
begin
  for D := 0 to cInputDim - 1 do
    X.FData[D] := cOODShift + RandomGauss() * cBlobSpread;
end;

// HARD / near-OOD sample (held-out-class split): a blob sitting at the MIDPOINT
// between two IN-distribution class centres (classes A and B) with a slightly
// wider spread. It lives INSIDE the convex hull of the kept classes, so its
// penultimate features land near the in-dist manifold (on the boundary between
// two class clusters) rather than far away. That overlap is what drops the
// AUROC into the discriminating 0.8-0.99 band.
procedure MakeNearOODSample(A, B: integer; X: TNNetVolume);
var
  D: integer;
  Ca, Cb: array[0..cInputDim - 1] of TNeuralFloat;
begin
  ClassCenter(A, Ca);
  ClassCenter(B, Cb);
  for D := 0 to cInputDim - 1 do
    X.FData[D] := 0.5 * (Ca[D] + Cb[D]) + RandomGauss() * (cBlobSpread * cNearOODSpread);
end;

// ---- AUROC via the Mann-Whitney U / rank statistic (tie-averaged ranks) ----
// Positives = Pos[], negatives = Neg[]. Merges, sorts ascending, assigns
// 1-based ranks averaging ties, then
//   AUROC = (sum of positive ranks - nPos*(nPos+1)/2) / (nPos * nNeg).
// Equals P(score(pos) > score(neg)) with ties counted as 1/2.
function AUROC(const Pos, Neg: array of TNeuralFloat): TNeuralFloat;
var
  nPos, nNeg, n, I, J, K: integer;
  Vals: array of TNeuralFloat;
  IsPos: array of boolean;
  Rank: array of TNeuralFloat;
  AvgRank, RankSumPos, Tmp: TNeuralFloat;
  TmpB: boolean;
begin
  nPos := Length(Pos);
  nNeg := Length(Neg);
  n := nPos + nNeg;
  if (nPos = 0) or (nNeg = 0) then Exit(0.5);

  SetLength(Vals, n);
  SetLength(IsPos, n);
  for I := 0 to nPos - 1 do begin Vals[I] := Pos[I]; IsPos[I] := True; end;
  for I := 0 to nNeg - 1 do
  begin
    Vals[nPos + I] := Neg[I];
    IsPos[nPos + I] := False;
  end;

  // insertion sort ascending by value (n ~ a few thousand, called once)
  for I := 1 to n - 1 do
  begin
    Tmp := Vals[I]; TmpB := IsPos[I];
    J := I - 1;
    while (J >= 0) and (Vals[J] > Tmp) do
    begin
      Vals[J + 1] := Vals[J]; IsPos[J + 1] := IsPos[J];
      Dec(J);
    end;
    Vals[J + 1] := Tmp; IsPos[J + 1] := TmpB;
  end;

  // tie-averaged 1-based ranks
  SetLength(Rank, n);
  I := 0;
  while I < n do
  begin
    J := I;
    while (J + 1 < n) and (Vals[J + 1] = Vals[I]) do Inc(J);
    // ranks i+1 .. j+1 averaged
    AvgRank := ((I + 1) + (J + 1)) / 2.0;
    for K := I to J do Rank[K] := AvgRank;
    I := J + 1;
  end;

  RankSumPos := 0;
  for I := 0 to n - 1 do
    if IsPos[I] then RankSumPos := RankSumPos + Rank[I];

  Result := (RankSumPos - nPos * (nPos + 1) / 2.0) / (nPos * nNeg);
end;

// In-place Cholesky inverse of an SPD matrix A (size cFeatDim).
// A = L L^T, then invert via forward/back substitution on the columns of I.
// Returns the inverse in Inv. Assumes A is SPD (guaranteed by the ridge).
procedure CholeskyInverse(const A: TMatrix; out Inv: TMatrix);
var
  n, i, j, k: integer;
  L: TMatrix;
  Y, Col: array of TNeuralFloat;
  Sum: TNeuralFloat;
begin
  n := Length(A);
  SetLength(L, n, n);
  for i := 0 to n - 1 do
    for j := 0 to n - 1 do L[i][j] := 0;

  // Cholesky factorisation A = L L^T (lower triangular L)
  for j := 0 to n - 1 do
  begin
    Sum := A[j][j];
    for k := 0 to j - 1 do Sum := Sum - L[j][k] * L[j][k];
    L[j][j] := Sqrt(Sum);
    for i := j + 1 to n - 1 do
    begin
      Sum := A[i][j];
      for k := 0 to j - 1 do Sum := Sum - L[i][k] * L[j][k];
      L[i][j] := Sum / L[j][j];
    end;
  end;

  SetLength(Inv, n, n);
  SetLength(Y, n);
  SetLength(Col, n);
  // Solve A * x = e_c for each unit column e_c -> column c of the inverse.
  for k := 0 to n - 1 do
  begin
    // forward solve L y = e_k
    for i := 0 to n - 1 do
    begin
      Sum := 0;
      if i = k then Sum := 1;
      for j := 0 to i - 1 do Sum := Sum - L[i][j] * Y[j];
      Y[i] := Sum / L[i][i];
    end;
    // back solve L^T x = y
    for i := n - 1 downto 0 do
    begin
      Sum := Y[i];
      for j := i + 1 to n - 1 do Sum := Sum - L[j][i] * Col[j];
      Col[i] := Sum / L[i][i];
    end;
    for i := 0 to n - 1 do Inv[i][k] := Col[i];
  end;
end;

type
  // Class-conditional Gaussian model fit on the FROZEN penultimate features.
  //   Mu[c]       per-class mean
  //   InMask[c]   True if class c is IN-distribution (fit on it), False if held out
  //   TiedInv     inverse of the single pooled (tied) covariance Sigma
  //   ClassInv[c] inverse of the per-class (untied) covariance Sigma_c
  TGaussModel = record
    Mu:       array[0..cNumClasses - 1] of TFeat;
    InMask:   array[0..cNumClasses - 1] of boolean;
    TiedInv:  TMatrix;
    ClassInv: array[0..cNumClasses - 1] of TMatrix;
  end;

  TCovMode = (cmTied, cmUntied);

var
  GNN: TNNet;           // global so the fit/score helpers can forward through it
  GX, GY: TNNetVolume;

// read the penultimate features of the LAST forward pass into F
procedure ReadFeatures(out F: TFeat);
var d2: integer;
begin
  for d2 := 0 to cFeatDim - 1 do
    F[d2] := GNN.Layers[cPenultimateIdx].Output.FData[d2];
end;

// Fit per-class means, the tied (pooled) covariance and the per-class (untied)
// covariances, using ONLY the classes flagged in InMask as in-distribution.
// The same deterministic training points are regenerated via a fixed seed.
procedure FitGaussians(const InMask: array of boolean; out M: TGaussModel);
var
  C, D, E, S: integer;
  ClassCount: array[0..cNumClasses - 1] of integer;
  Feat, Tmp: TFeat;
  Sigma: TMatrix;
  ClassSigma: array[0..cNumClasses - 1] of TMatrix;
  TotalN: TNeuralFloat;
begin
  for C := 0 to cNumClasses - 1 do
  begin
    M.InMask[C] := InMask[C];
    ClassCount[C] := 0;
    for D := 0 to cFeatDim - 1 do M.Mu[C][D] := 0;
  end;
  SetLength(Sigma, cFeatDim, cFeatDim);
  for D := 0 to cFeatDim - 1 do
    for E := 0 to cFeatDim - 1 do Sigma[D][E] := 0;
  for C := 0 to cNumClasses - 1 do
  begin
    SetLength(ClassSigma[C], cFeatDim, cFeatDim);
    for D := 0 to cFeatDim - 1 do
      for E := 0 to cFeatDim - 1 do ClassSigma[C][D][E] := 0;
  end;

  // Pass 1: per-class means (in-distribution classes only).
  RandSeed := 989898;
  for C := 0 to cNumClasses - 1 do
    for S := 1 to cTrainPerClass do
    begin
      MakeInSample(C, GX, GY);
      if not InMask[C] then continue;
      GNN.Compute(GX);
      ReadFeatures(Feat);
      for D := 0 to cFeatDim - 1 do M.Mu[C][D] := M.Mu[C][D] + Feat[D];
      Inc(ClassCount[C]);
    end;
  for C := 0 to cNumClasses - 1 do
    if InMask[C] then
      for D := 0 to cFeatDim - 1 do M.Mu[C][D] := M.Mu[C][D] / ClassCount[C];

  // Pass 2: tied Sigma = (1/N) sum_c sum_i (f-mu_c)(f-mu_c)^T and, in parallel,
  // each per-class Sigma_c = (1/N_c) sum_i (f-mu_c)(f-mu_c)^T.
  RandSeed := 989898;
  TotalN := 0;
  for C := 0 to cNumClasses - 1 do
    for S := 1 to cTrainPerClass do
    begin
      MakeInSample(C, GX, GY);
      if not InMask[C] then continue;
      GNN.Compute(GX);
      ReadFeatures(Feat);
      for D := 0 to cFeatDim - 1 do Tmp[D] := Feat[D] - M.Mu[C][D];
      for D := 0 to cFeatDim - 1 do
        for E := 0 to cFeatDim - 1 do
        begin
          Sigma[D][E]         := Sigma[D][E]         + Tmp[D] * Tmp[E];
          ClassSigma[C][D][E] := ClassSigma[C][D][E] + Tmp[D] * Tmp[E];
        end;
      TotalN := TotalN + 1;
    end;
  for D := 0 to cFeatDim - 1 do
    for E := 0 to cFeatDim - 1 do
      Sigma[D][E] := Sigma[D][E] / TotalN;
  for D := 0 to cFeatDim - 1 do Sigma[D][D] := Sigma[D][D] + cRidge;
  CholeskyInverse(Sigma, M.TiedInv);

  for C := 0 to cNumClasses - 1 do
    if InMask[C] then
    begin
      for D := 0 to cFeatDim - 1 do
        for E := 0 to cFeatDim - 1 do
          ClassSigma[C][D][E] := ClassSigma[C][D][E] / ClassCount[C];
      for D := 0 to cFeatDim - 1 do
        ClassSigma[C][D][D] := ClassSigma[C][D][D] + cRidge;
      CholeskyInverse(ClassSigma[C], M.ClassInv[C]);
    end;
end;

// score(x) = max_{c in-dist} -(f-mu_c)^T Inv_c (f-mu_c). For the TIED mode
// Inv_c is the single pooled inverse for every class; for UNTIED each class
// uses its own covariance inverse. The maximum is over IN-distribution classes.
function MahalanobisScore(const M: TGaussModel; const Feat: TFeat;
  Mode: TCovMode): TNeuralFloat;
var
  C, D, Idx: integer;
  Dv: TFeat;
  Quad, BestScore: TNeuralFloat;
  Inv: TMatrix;
begin
  BestScore := -Infinity;
  for C := 0 to cNumClasses - 1 do
  begin
    if not M.InMask[C] then continue;
    if Mode = cmTied then Inv := M.TiedInv else Inv := M.ClassInv[C];
    for D := 0 to cFeatDim - 1 do Dv[D] := Feat[D] - M.Mu[C][D];
    Quad := 0;
    for D := 0 to cFeatDim - 1 do
      for Idx := 0 to cFeatDim - 1 do
        Quad := Quad + Dv[D] * Inv[D][Idx] * Dv[Idx];
    if -Quad > BestScore then BestScore := -Quad;
  end;
  Result := BestScore;
end;

// Report one OOD-detection arm: print mean scores and AUROC, return the AUROC.
function ReportArm(const ArmName: string; const Pos, Neg: array of TNeuralFloat): TNeuralFloat;
var
  I: integer;
  MeanPos, MeanNeg, Auc: TNeuralFloat;
begin
  MeanPos := 0; for I := 0 to High(Pos) do MeanPos := MeanPos + Pos[I];
  MeanPos := MeanPos / Length(Pos);
  MeanNeg := 0; for I := 0 to High(Neg) do MeanNeg := MeanNeg + Neg[I];
  MeanNeg := MeanNeg / Length(Neg);
  Auc := AUROC(Pos, Neg);
  WriteLn(ArmName);
  WriteLn('  held-in (pos) n=', Length(Pos):4, '  mean score = ', MeanPos:14:4);
  WriteLn('  OOD     (neg) n=', Length(Neg):4, '  mean score = ', MeanNeg:14:4);
  WriteLn('  AUROC = ', Auc:0:4);
  if MeanPos <= MeanNeg then
    WriteLn('  WARN: held-in mean score not above OOD mean score');
  Result := Auc;
end;

procedure RunDemo();
var
  Epoch, I, C, S, N: integer;
  Loss, Diff: TNeuralFloat;
  Feat: TFeat;
  AllIn, HardIn: array[0..cNumClasses - 1] of boolean;
  ModelAll, ModelHard: TGaussModel;
  // EASY arm
  EasyPos, EasyNeg: array of TNeuralFloat;
  // HARD arm (held-out-class), tied + untied
  HardPos, HardNeg: array of TNeuralFloat;
  HardPosU, HardNegU: array of TNeuralFloat;
  AucEasy, AucHardTied, AucHardUntied: TNeuralFloat;
begin
  RandSeed := 424242;
  BuildNet(GNN);
  GX := TNNetVolume.Create(cInputDim, 1, 1);
  GY := TNNetVolume.Create(cNumClasses, 1, 1);
  try
    GNN.SetLearningRate(cLearningRate, 0.9);

    WriteLn('Architecture (penultimate feature layer = index ',
      cPenultimateIdx, ', width ', cFeatDim, '):');
    GNN.PrintSummary();
    WriteLn;
    WriteLn('In-distribution classes=', cNumClasses,
      '  train/class=', cTrainPerClass, '  test/class=', cTestPerClass,
      '  far-OOD points=', cOODCount);
    WriteLn('HARD split: Gaussians fit on classes 0..', cInClasses - 1,
      ' (class ', cHeldOutClass, ' held out); near-OOD = boundary blobs at the',
      ' midpoint of classes ', cNearA, '/', cNearB);
    WriteLn;

    // ----------------------------- TRAIN ---------------------------------
    // The classifier still trains on ALL K classes so the held-out class gets
    // a sensible (non-degenerate) penultimate feature; only the GAUSSIAN FIT
    // excludes it on the HARD arm.
    WriteLn('Training the classifier for ', cEpochs, ' epochs...');
    for Epoch := 1 to cEpochs do
    begin
      Loss := 0;
      for I := 1 to cTrainPerClass * cNumClasses do
      begin
        C := Random(cNumClasses);
        MakeInSample(C, GX, GY);
        GNN.Compute(GX);
        GNN.Backpropagate(GY);
        Diff := -Ln(Max(1e-9, GNN.GetLastLayer().Output.FData[C]));
        Loss := Loss + Diff;
      end;
      if (Epoch mod 20 = 0) or (Epoch = 1) then
        WriteLn('  epoch ', Epoch:4, '  mean_nll=',
          (Loss / (cTrainPerClass * cNumClasses)):8:5);
    end;
    WriteLn;

    // -------- FIT class-conditional Gaussians (two models) ---------------
    for C := 0 to cNumClasses - 1 do
    begin
      AllIn[C]  := True;                  // EASY arm: every class in-distribution
      HardIn[C] := (C <> cHeldOutClass);  // HARD arm: hold out the last class
    end;
    FitGaussians(AllIn,  ModelAll);
    FitGaussians(HardIn, ModelHard);

    // ====================== EASY arm (far-away OOD) ======================
    // Positives = held-in test points of all K classes (tied covariance).
    SetLength(EasyPos, cTestPerClass * cNumClasses);
    RandSeed := 555111;
    N := 0;
    for C := 0 to cNumClasses - 1 do
      for S := 1 to cTestPerClass do
      begin
        MakeInSample(C, GX, GY);
        GNN.Compute(GX);
        ReadFeatures(Feat);
        EasyPos[N] := MahalanobisScore(ModelAll, Feat, cmTied);
        Inc(N);
      end;
    SetLength(EasyNeg, cOODCount);
    for I := 0 to cOODCount - 1 do
    begin
      MakeOODSample(GX);
      GNN.Compute(GX);
      ReadFeatures(Feat);
      EasyNeg[I] := MahalanobisScore(ModelAll, Feat, cmTied);
    end;

    // ================ HARD arm (held-out-class near-OOD) =================
    // Positives = held-in test points of the K-1 IN classes; negatives = test
    // points of the HELD-OUT class. Scored both TIED and UNTIED.
    SetLength(HardPos, cTestPerClass * cInClasses);
    SetLength(HardPosU, cTestPerClass * cInClasses);
    RandSeed := 777222;
    N := 0;
    for C := 0 to cNumClasses - 1 do
      for S := 1 to cTestPerClass do
      begin
        MakeInSample(C, GX, GY);
        if C = cHeldOutClass then continue;
        GNN.Compute(GX);
        ReadFeatures(Feat);
        HardPos[N]  := MahalanobisScore(ModelHard, Feat, cmTied);
        HardPosU[N] := MahalanobisScore(ModelHard, Feat, cmUntied);
        Inc(N);
      end;
    SetLength(HardNeg, cTestPerClass);
    SetLength(HardNegU, cTestPerClass);
    RandSeed := 888333;
    N := 0;
    for S := 1 to cTestPerClass do
    begin
      MakeNearOODSample(cNearA, cNearB, GX);
      GNN.Compute(GX);
      ReadFeatures(Feat);
      HardNeg[N]  := MahalanobisScore(ModelHard, Feat, cmTied);
      HardNegU[N] := MahalanobisScore(ModelHard, Feat, cmUntied);
      Inc(N);
    end;

    // ------------------------------- REPORT ------------------------------
    WriteLn('Mahalanobis OOD detection (Lee et al. 2018)');
    WriteLn('Feature layer idx=', cPenultimateIdx, '  dim=', cFeatDim,
      '  ridge=', cRidge:0:4);
    WriteLn(StringOfChar('=', 64));
    AucEasy := ReportArm(
      'EASY  far-away OOD (+' + IntToStr(Round(cOODShift)) +
      '/coord), tied covariance:', EasyPos, EasyNeg);
    WriteLn(StringOfChar('-', 64));
    AucHardTied := ReportArm(
      'HARD  near-OOD boundary blob (midpoint classes ' + IntToStr(cNearA) +
      '/' + IntToStr(cNearB) + '), TIED covariance:', HardPos, HardNeg);
    WriteLn(StringOfChar('-', 64));
    AucHardUntied := ReportArm(
      'HARD  near-OOD boundary blob (midpoint classes ' + IntToStr(cNearA) +
      '/' + IntToStr(cNearB) + '), UNTIED (per-class) covariance:',
      HardPosU, HardNegU);
    WriteLn(StringOfChar('=', 64));
    WriteLn('AUROC summary:');
    WriteLn('  EASY (far-OOD, tied)          = ', AucEasy:0:4);
    WriteLn('  HARD (near-OOD, tied)         = ', AucHardTied:0:4);
    WriteLn('  HARD (near-OOD, untied)       = ', AucHardUntied:0:4);
    WriteLn('  delta (untied - tied), HARD   = ',
      (AucHardUntied - AucHardTied):0:4);
    if AucHardUntied > AucHardTied then
      WriteLn('  -> UNTIED (per-class) covariance wins on the HARD split')
    else if AucHardUntied < AucHardTied then
      WriteLn('  -> TIED (pooled) covariance wins on the HARD split')
    else
      WriteLn('  -> tied and untied tie on the HARD split');
    WriteLn(StringOfChar('=', 64));

    // ------------------------------- CHECKS ------------------------------
    // EASY must stay separable (pins at 1.0); HARD must land in a discriminating
    // band ABOVE the threshold but BELOW 1.0 (it must actually be harder).
    if AucEasy <= cMinAUROC then
    begin
      WriteLn('FAIL: EASY AUROC ', AucEasy:0:4, ' <= ', cMinAUROC:0:2);
      Halt(1);
    end;
    if AucHardTied <= cMinAUROC then
    begin
      WriteLn('FAIL: HARD tied AUROC ', AucHardTied:0:4, ' <= ', cMinAUROC:0:2,
        ' (held-out-class split not discriminating)');
      Halt(1);
    end;
    if AucHardTied >= 1.0 then
    begin
      WriteLn('FAIL: HARD tied AUROC ', AucHardTied:0:4,
        ' pinned at 1.0 - split is not actually near-OOD');
      Halt(1);
    end;
    WriteLn('PASS: EASY AUROC ', AucEasy:0:4, ' > ', cMinAUROC:0:2,
      ', HARD AUROC ', AucHardTied:0:4, ' in discriminating band (',
      cMinAUROC:0:2, ', 1.0)');
  finally
    GY.Free;
    GX.Free;
    GNN.Free;
  end;
end;

begin
  RunDemo();
end.
