program DiffusionInpainting;
(*
DiffusionInpainting: blended-diffusion (latent-space) STABLE-DIFFUSION
INPAINTING -- regenerate ONLY a masked hole while the rest stays pixel-faithful,
on the STANDARD 4-channel SD UNet (no 9-channel inpaint-specialized conv_in).
This is the "blended diffusion" SD inpaint mode (Avrahami et al. 2022, "Blended
Diffusion for Text-driven Editing of Natural Images", arXiv:2111.14818) -- the
most-used inpaint path that needs NO retrained inpaint UNet.

THE PIPELINE (every piece already landed; this is ONLY the driver that wires the
blend into the reverse loop):

  1. ENCODE   source RGB image  --VAE encoder-->  clean latent z0
        (neuralpretrained.pas BuildVaeEncoderFromSafeTensors.)
  2. MASK     a binary RGB mask (1 = HOLE to reconstruct, 0 = keep) is
        downsampled to the latent grid -> a per-voxel latent mask in {0,1}.
  3. BLENDED DENOISE  start from z0 re-noised to the first scheduled timestep,
        then run the reverse trajectory on the 4-channel SD UNet. At EVERY step
        the KNOWN region is blended back in:
          latents := mask*denoised + (1-mask)*AddNoise(z0, t)
        so the visible region always carries the right noise level for t while
        only the hole follows the denoiser (neuralpretrained.pas
        SDUNetDenoiseInpaint + neuraldiffusion.pas TNNetDiffusionScheduler).
  4. DECODE   the final latent  --VAE decoder-->  inpainted RGB image
        (neuralpretrained.pas BuildVaeDecoderFromSafeTensors.)

The ONLY new code (vs the ImageToImage SDEdit example) is the per-step latent
blend + the latent-space mask downsample -- both live in the reusable
SDUNetDenoiseInpaint driver. The standard 4-channel UNet, the VAE encoder/
decoder and the scheduler are reused untouched.

DEFERRED (follow-up): the 9-channel inpaint-specialized UNet (conv_in widened to
latent|mask|masked-latent, the diffusers "stable-diffusion-inpainting" weights)
and a non-deterministic reparameterized VAE sampling head are NOT done here --
this blended mode is the no-retrain path.

OFFLINE SMOKE RUN. Real SD checkpoints are far too large for this environment, so
by default the example runs a SELF-CONTAINED smoke on the committed tiny RANDOM
fixtures the importer parity tests use (tests/fixtures/tiny_vae_encoder|decoder
and tiny_sd_unet .safetensors). Those nets are untrained random weights, so the
"inpaint" is not a meaningful picture -- the point is to exercise the full driver
path end to end and write before/after PPM images, within a small RAM/time
budget. Point --vae-encoder / --vae-decoder / --unet (with their --*-config) at
real config-compatible checkpoints to run it for real.

OUTPUT. masked_input.ppm (the source VAE round-trip with the hole greyed out)
and inpainted.ppm (the blended-inpaint result). A synthetic source (smooth color
ramp) and a rectangular right-half hole are generated by default. The run asserts
the decoded image has no NaN/Inf, the KEPT latent region equals the source
exactly, and the MASKED region was changed by the denoiser.

RUN
  ./DiffusionInpainting                 smoke run on the tiny fixtures
  ./DiffusionInpainting --steps 8       more reverse steps
  ./DiffusionInpainting --vae-encoder enc.safetensors --vae-encoder-config enc.json \
                        --vae-decoder dec.safetensors --vae-decoder-config dec.json \
                        --unet unet.safetensors --unet-config unet.json
                                        real checkpoints (not in this repo)

Copyright (C) 2026 Joao Paulo Schwarz Schuler

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
any later version.

Coded by Claude (AI).
*)

{$mode objfpc}{$H+}

uses {$IFDEF UNIX} cthreads, {$ENDIF}
  Classes, SysUtils, Math,
  neuralnetwork,
  neuralvolume,
  neuraldiffusion,
  neuralpretrained;

const
  cDefaultSteps = 6;     // reverse DDIM steps in the smoke run
  cT            = 200;   // scheduler timesteps (matches the other examples)

// --- tiny PPM writer (P6 binary). V is a (W,H,3) volume in [-1,1]; pixels are
//     mapped to 0..255 and clamped. (Mirrors ImageToImage's writer.) ---
function WritePPM(V: TNNetVolume; const FileName: string): boolean;
var
  F: TFileStream;
  Hdr: string;
  x, y, c: integer;
  v01: TNeuralFloat;
  Row: array of byte;
begin
  Result := false;
  try
    F := TFileStream.Create(FileName, fmCreate);
    try
      Hdr := Format('P6'#10'%d %d'#10'255'#10, [V.SizeX, V.SizeY]);
      F.WriteBuffer(Hdr[1], Length(Hdr));
      SetLength(Row, V.SizeX * 3);
      for y := 0 to V.SizeY - 1 do
      begin
        for x := 0 to V.SizeX - 1 do
          for c := 0 to 2 do
          begin
            v01 := (V[x, y, c] + 1.0) * 127.5;
            if IsNan(v01) or IsInfinite(v01) then v01 := 0;
            if v01 < 0 then v01 := 0;
            if v01 > 255 then v01 := 255;
            Row[x * 3 + c] := Round(v01);
          end;
        F.WriteBuffer(Row[0], Length(Row));
      end;
      Result := true;
    finally
      F.Free;
    end;
  except
    Result := false;
  end;
end;

// Fill V (W,H,3) with a smooth synthetic color ramp in [-1,1] (the stand-in
// source image when no --image is given).
procedure MakeSyntheticImage(V: TNNetVolume);
var x, y: integer;
begin
  for y := 0 to V.SizeY - 1 do
    for x := 0 to V.SizeX - 1 do
    begin
      V[x, y, 0] := (x / Max(1, V.SizeX - 1)) * 2.0 - 1.0;          // R: left->right
      V[x, y, 1] := (y / Max(1, V.SizeY - 1)) * 2.0 - 1.0;          // G: top->bottom
      V[x, y, 2] := Sin((x + y) * 0.6) * 0.8;                       // B: ripple
    end;
end;

var
  Enc, Dec, UNet: TNNet;
  EncCfg, DecCfg: TVaeDecoderConfig;
  UCfg: TSDUNetConfig;
  Sched: TNNetDiffusionScheduler;

  Steps: integer;
  EncPath, EncCfgPath, DecPath, DecCfgPath, UNetPath, UNetCfgPath: string;
  UseFixtures: boolean;

  function FixtureBase: string;
  var
    Cand: array[0..2] of string;
    i: integer;
  begin
    Cand[0] := 'tests' + DirectorySeparator + 'fixtures' + DirectorySeparator;
    Cand[1] := '..' + DirectorySeparator + '..' + DirectorySeparator +
      'tests' + DirectorySeparator + 'fixtures' + DirectorySeparator;
    Cand[2] := 'fixtures' + DirectorySeparator;
    Result := Cand[0];
    for i := 0 to 2 do
      if FileExists(Cand[i] + 'tiny_sd_unet.safetensors') then
        Exit(Cand[i]);
  end;

  procedure ParseArgs;
  var i: integer; s: string;
  begin
    Steps := cDefaultSteps;
    EncPath := ''; EncCfgPath := ''; DecPath := ''; DecCfgPath := '';
    UNetPath := ''; UNetCfgPath := '';
    i := 1;
    while i <= ParamCount do
    begin
      s := ParamStr(i);
      if (s = '--steps') and (i < ParamCount) then begin Inc(i); Steps := StrToInt(ParamStr(i)); end
      else if (s = '--vae-encoder') and (i < ParamCount) then begin Inc(i); EncPath := ParamStr(i); end
      else if (s = '--vae-encoder-config') and (i < ParamCount) then begin Inc(i); EncCfgPath := ParamStr(i); end
      else if (s = '--vae-decoder') and (i < ParamCount) then begin Inc(i); DecPath := ParamStr(i); end
      else if (s = '--vae-decoder-config') and (i < ParamCount) then begin Inc(i); DecCfgPath := ParamStr(i); end
      else if (s = '--unet') and (i < ParamCount) then begin Inc(i); UNetPath := ParamStr(i); end
      else if (s = '--unet-config') and (i < ParamCount) then begin Inc(i); UNetCfgPath := ParamStr(i); end;
      Inc(i);
    end;
    UseFixtures := (UNetPath = '') or (EncPath = '') or (DecPath = '');
  end;

// Build the latent-space inpaint MASK over a (Sx,Sy,Depth) latent: 1 = HOLE
// (regenerate), 0 = KEEP. The smoke mask is the right half of the grid.
procedure MakeInpaintMask(Mask: TNNetVolume; Templ: TNNetVolume);
var x, y, c: integer;
begin
  Mask.ReSize(Templ);
  for y := 0 to Mask.SizeY - 1 do
    for x := 0 to Mask.SizeX - 1 do
      for c := 0 to Mask.Depth - 1 do
        if x >= (Mask.SizeX div 2) then Mask[x, y, c] := 1.0   // right half: hole
        else Mask[x, y, c] := 0.0;                             // left half: keep
end;

var
  ImgIn, Z0, Mask, EncStates, Latents, Scratch, KnownNoised, Recon: TNNetVolume;
  ImgGrid, i, x, y, sIdx: integer;
  Schedule: array of integer;
  NumNan: integer;
  outv: TNNetVolume;
  m, d, maxKeepErr, maskedDiff: TNeuralFloat;
begin
  SetExceptionMask([exInvalidOp, exDenormalized, exZeroDivide,
                    exOverflow, exUnderflow, exPrecision]);
  RandSeed := 2026;
  ParseArgs;

  WriteLn('DiffusionInpainting (blended): encode -> masked blended denoise -> decode.');
  if UseFixtures then
  begin
    EncPath := FixtureBase + 'tiny_vae_encoder.safetensors';
    EncCfgPath := FixtureBase + 'tiny_vae_encoder_config.json';
    DecPath := FixtureBase + 'tiny_vae_decoder.safetensors';
    DecCfgPath := FixtureBase + 'tiny_vae_decoder_config.json';
    UNetPath := FixtureBase + 'tiny_sd_unet.safetensors';
    UNetCfgPath := FixtureBase + 'tiny_sd_unet_config.json';
    WriteLn('[SMOKE mode] using committed tiny RANDOM fixtures: ', FixtureBase);
    WriteLn('  (untrained nets -> the inpaint is not a real picture; this validates the driver path)');
  end
  else
    WriteLn('[REAL mode] using supplied checkpoints.');

  if not FileExists(UNetPath) then
  begin
    WriteLn('SD UNet checkpoint not found: ', UNetPath);
    WriteLn('Run from the repo root so the tiny fixtures are visible, or pass --unet.');
    Halt(0);
  end;

  WriteLn(Format('reverse steps = %d   T = %d', [Steps, cT]));
  WriteLn;

  Sched := TNNetDiffusionScheduler.Create(cT, dsLinear, dpEps);
  Enc := BuildVaeEncoderFromSafeTensors(EncPath, EncCfg, {pTrainable=}true, EncCfgPath);
  Dec := BuildVaeDecoderFromSafeTensors(DecPath, DecCfg, {pTrainable=}true, DecCfgPath);
  UNet := BuildSDUNetFromSafeTensors(UNetPath, UCfg, {pTrainable=}true, UNetCfgPath);

  ImgGrid := EncCfg.LatentGrid shl (EncCfg.NumBlockOut - 1);
  WriteLn(Format('VAE: %dx%d RGB <-> %dx%dx%d latent;  SD UNet denoise grid %dx%dx%d.',
    [ImgGrid, ImgGrid, EncCfg.LatentGrid, EncCfg.LatentGrid, EncCfg.LatentChannels,
     UCfg.LatentGrid, UCfg.LatentGrid, UCfg.InChannels]));
  if UCfg.LatentGrid <> EncCfg.LatentGrid then
  begin
    WriteLn('FATAL: VAE latent grid <> SD UNet grid; pass matched checkpoints.');
    Halt(1);
  end;
  WriteLn;

  ImgIn := TNNetVolume.Create(ImgGrid, ImgGrid, EncCfg.OutChannels);
  Z0 := TNNetVolume.Create;
  Mask := TNNetVolume.Create;
  EncStates := TNNetVolume.Create(UCfg.TextSeqLen, 1, UCfg.CrossAttentionDim);
  Latents := TNNetVolume.Create;
  Scratch := TNNetVolume.Create;
  KnownNoised := TNNetVolume.Create;
  Recon := TNNetVolume.Create;
  Schedule := nil;
  try
    // prompt: with a real run feed your CLIP encoder states; offline random.
    for i := 0 to EncStates.Size - 1 do
      EncStates.FData[i] := RandG(0, 1) * 0.5;

    // 1. source image (synthetic ramp) -> ENCODE to clean latent z0.
    MakeSyntheticImage(ImgIn);
    Enc.Compute(ImgIn);
    Z0.Copy(Enc.GetLastLayer().Output);
    WriteLn(Format('Encoded latent: %dx%dx%d.', [Z0.SizeX, Z0.SizeY, Z0.Depth]));

    // 2. latent-space mask (right half = hole).
    MakeInpaintMask(Mask, Z0);
    WriteLn(Format('[INPAINT] mask %dx%dx%d: regenerate right half, keep left half.',
      [Mask.SizeX, Mask.SizeY, Mask.Depth]));

    // masked_input.ppm = source round-trip with the hole region greyed.
    Dec.Compute(Z0);
    Recon.Copy(Dec.GetLastLayer().Output);
    for y := 0 to Recon.SizeY - 1 do
      for x := 0 to Recon.SizeX - 1 do
        if x >= (Recon.SizeX div 2) then
        begin
          Recon[x, y, 0] := 0.0; Recon[x, y, 1] := 0.0; Recon[x, y, 2] := 0.0;
        end;
    if WritePPM(Recon, 'masked_input.ppm')
      then WriteLn('Wrote masked_input.ppm (source round-trip, hole greyed).')
      else WriteLn('FAILED writing masked_input.ppm');

    // 3. descending schedule T..0, then BLENDED denoise.
    SetLength(Schedule, Steps + 1);
    for sIdx := 0 to Steps do
      Schedule[sIdx] := Round(cT * (1.0 - sIdx / Steps));
    WriteLn('Blended denoising (', Steps, ' reverse steps):');
    SDUNetDenoiseInpaint(UNet, UCfg, Z0, Mask, EncStates, Sched,
      Schedule, smDDIM, 0.0, Latents, Scratch, KnownNoised);

    // 4. DECODE the final latent.
    Dec.Compute(Latents);
    outv := Dec.GetLastLayer().Output;
    NumNan := 0;
    for i := 0 to outv.Size - 1 do
      if IsNan(outv.FData[i]) or IsInfinite(outv.FData[i]) then Inc(NumNan);
    Recon.Copy(outv);
    if WritePPM(Recon, 'inpainted.ppm')
      then WriteLn('Wrote inpainted.ppm (blended-inpaint result).')
      else WriteLn('FAILED writing inpainted.ppm');

    WriteLn;
    if NumNan = 0
      then WriteLn('OK: decoded inpaint has no NaN/Inf pixels.')
      else WriteLn('WARNING: ', NumNan, ' NaN/Inf pixels in the decoded inpaint.');

    // regression check (latent space, exact): KEPT region == source latent
    // (pixel-faithful), MASKED region changed by the denoiser.
    maxKeepErr := 0;
    maskedDiff := 0;
    for i := 0 to Latents.Size - 1 do
    begin
      m := Mask.FData[i];
      d := Abs(Latents.FData[i] - Z0.FData[i]);
      if m < 0.5 then begin if d > maxKeepErr then maxKeepErr := d; end
      else maskedDiff := maskedDiff + d;
    end;
    WriteLn(Format('[INPAINT] kept-region max error = %.6g ; masked-region total change = %.6g',
      [maxKeepErr, maskedDiff]));
    if maxKeepErr > 1e-4 then
    begin
      WriteLn('FAIL: kept latent region drifted from the source.');
      Halt(1);
    end;
    if maskedDiff <= 1e-6 then
    begin
      WriteLn('FAIL: masked latent region was not regenerated (unchanged).');
      Halt(1);
    end;
    WriteLn('OK: kept region pixel-faithful, masked hole regenerated.');
    WriteLn('Done. Compare masked_input.ppm vs inpainted.ppm.');
  finally
    SetLength(Schedule, 0);
    ImgIn.Free; Z0.Free; Mask.Free; EncStates.Free;
    Latents.Free; Scratch.Free; KnownNoised.Free; Recon.Free;
    Enc.Free; Dec.Free; UNet.Free; Sched.Free;
  end;
end.
