unit TestNeuralPretrained;
// Tests for the safetensors reader (neuralsafetensors.pas) and the GPT-2
// pretrained-checkpoint importer (neuralpretrained.pas).
//
// The flagship test is TestGPT2LogitParity: it loads the committed tiny
// random GPT-2-shaped checkpoint (tests/fixtures/tiny_gpt2.safetensors,
// generated by tools/gpt2_tiny_fixture.py) and asserts that the imported
// TNNet's logits match the INDEPENDENT pure-Python GPT-2 forward (the
// oracle, same generator script) to < 1e-3 (typically ~1e-5 end-to-end f32).
//
// This unit is coded by Claude (AI).
{$mode objfpc}{$H+}

interface

uses
  Classes, SysUtils, fpcunit, testregistry, fpjson, jsonparser,
  neuralvolume, neuralnetwork, neuralsafetensors, neuralpretrained;

type
  TTestNeuralPretrained = class(TTestCase)
  private
    function FixturePath(const FileName: string): string;
    // Composes a minimal safetensors byte stream into a temp file and
    // returns its path. HeaderJson is written verbatim (preceded by its
    // 8-byte little-endian length); Payload is the raw data section.
    function WriteTempSafeTensors(const HeaderJson: string;
      const Payload: array of byte): string;
  published
    procedure TestTokenLayerNormForwardAndSaveLoad;
    procedure TestLearnedPositionalEmbeddingForwardAndSaveLoad;
    procedure TestF16Decode;
    procedure TestBF16Decode;
    procedure TestReaderReadsF16AndBF16Tensors;
    procedure TestReaderRejectsGarbage;
    procedure TestReaderReadsTinyFixture;
    procedure TestImporterFailsOnMissingTensor;
    procedure TestGPT2ConfigFromFixture;
    procedure TestGPT2LogitParity;
  end;

implementation

function TTestNeuralPretrained.FixturePath(const FileName: string): string;
begin
  // RunAll.sh runs the suite from the tests/ directory; also probe the repo
  // root in case the binary is started from there.
  Result := 'fixtures' + DirectorySeparator + FileName;
  if not FileExists(Result) then
    Result := 'tests' + DirectorySeparator + 'fixtures' + DirectorySeparator +
      FileName;
  if not FileExists(Result) then
    Fail('Fixture not found: ' + FileName +
      ' (run python3 tools/gpt2_tiny_fixture.py from the repo root).');
end;

function TTestNeuralPretrained.WriteTempSafeTensors(const HeaderJson: string;
  const Payload: array of byte): string;
var
  FS: TFileStream;
  HeaderLen: QWord;
begin
  Result := GetTempDir(false) + 'cai_st_test_' + IntToStr(Random(1000000)) +
    '.safetensors';
  FS := TFileStream.Create(Result, fmCreate);
  try
    HeaderLen := Length(HeaderJson);
    FS.WriteBuffer(HeaderLen, 8);
    if HeaderJson <> '' then
      FS.WriteBuffer(HeaderJson[1], Length(HeaderJson));
    if Length(Payload) > 0 then
      FS.WriteBuffer(Payload[0], Length(Payload));
  finally
    FS.Free;
  end;
end;

procedure TTestNeuralPretrained.TestTokenLayerNormForwardAndSaveLoad;
var
  NN, NN2: TNNet;
  LN: TNNetLayer;
  Input, Out1, Out2: TNNetVolume;
  i, t, c: integer;
  Mean, Variance, Expected: double;
  TokenVals: array[0..3] of double;
begin
  RandSeed := 424242;
  // (SeqLen=3, 1, Depth=4) input; per-token normalization over Depth.
  NN := TNNet.Create();
  NN.AddLayer( TNNetInput.Create(3, 1, 4) );
  LN := NN.AddLayer( TNNetTokenLayerNorm.Create(1e-5) );
  // Distinct gamma/beta per channel.
  for c := 0 to 3 do
  begin
    LN.Neurons[0].Weights.FData[c] := 0.5 + 0.25 * c; // gamma
    LN.Neurons[1].Weights.FData[c] := 0.1 * c - 0.2;  // beta
  end;
  LN.FlushWeightCache();
  Input := TNNetVolume.Create(3, 1, 4);
  Out1 := TNNetVolume.Create;
  Out2 := TNNetVolume.Create;
  NN2 := TNNet.Create();
  try
    for i := 0 to Input.Size - 1 do
      Input.FData[i] := Sin(i * 1.7) * 2 + 0.3 * i;
    NN.Compute(Input);
    NN.GetOutput(Out1);
    // Hand-computed per-token LayerNorm for each of the 3 tokens.
    for t := 0 to 2 do
    begin
      Mean := 0;
      for c := 0 to 3 do
      begin
        TokenVals[c] := Input.FData[t * 4 + c];
        Mean := Mean + TokenVals[c];
      end;
      Mean := Mean / 4;
      Variance := 0;
      for c := 0 to 3 do
        Variance := Variance + Sqr(TokenVals[c] - Mean);
      Variance := Variance / 4;
      for c := 0 to 3 do
      begin
        Expected := (0.5 + 0.25 * c) *
          ((TokenVals[c] - Mean) / Sqrt(Variance + 1e-5)) + (0.1 * c - 0.2);
        AssertEquals('per-token LN value t=' + IntToStr(t) + ' c=' +
          IntToStr(c), Expected, Out1.FData[t * 4 + c], 1e-5);
      end;
    end;
    // Save/load round-trip must preserve structure and weights.
    NN2.LoadFromString(NN.SaveToString());
    AssertTrue('reloaded layer class',
      NN2.Layers[1] is TNNetTokenLayerNorm);
    NN2.Compute(Input);
    NN2.GetOutput(Out2);
    for i := 0 to Out1.Size - 1 do
      AssertEquals('save/load forward equality at ' + IntToStr(i),
        Out1.FData[i], Out2.FData[i], 1e-7);
  finally
    NN2.Free;
    Out2.Free;
    Out1.Free;
    Input.Free;
    NN.Free;
  end;
end;

procedure TTestNeuralPretrained.TestLearnedPositionalEmbeddingForwardAndSaveLoad;
var
  NN, NN2: TNNet;
  PosLayer: TNNetLayer;
  Input, Out1, Out2: TNNetVolume;
  i, x, c: integer;
begin
  RandSeed := 424242;
  // (SeqLen=3, 1, Depth=2) input with a MaxPosition=5 table: only the first
  // 3 rows participate.
  NN := TNNet.Create();
  NN.AddLayer( TNNetInput.Create(3, 1, 2) );
  PosLayer := NN.AddLayer( TNNetLearnedPositionalEmbedding.Create(5) );
  for x := 0 to 4 do
    for c := 0 to 1 do
      PosLayer.Neurons[0].Weights[x, 0, c] := 10 * x + c;
  PosLayer.FlushWeightCache();
  Input := TNNetVolume.Create(3, 1, 2);
  Out1 := TNNetVolume.Create;
  Out2 := TNNetVolume.Create;
  NN2 := TNNet.Create();
  try
    for i := 0 to Input.Size - 1 do Input.FData[i] := 0.5 * i;
    NN.Compute(Input);
    NN.GetOutput(Out1);
    for x := 0 to 2 do
      for c := 0 to 1 do
        AssertEquals('pos add x=' + IntToStr(x) + ' c=' + IntToStr(c),
          0.5 * (x * 2 + c) + 10 * x + c, Out1.FData[x * 2 + c], 1e-6);
    NN2.LoadFromString(NN.SaveToString());
    AssertTrue('reloaded layer class',
      NN2.Layers[1] is TNNetLearnedPositionalEmbedding);
    AssertEquals('MaxPosition round-trip', 5,
      TNNetLearnedPositionalEmbedding(NN2.Layers[1]).MaxPosition);
    NN2.Compute(Input);
    NN2.GetOutput(Out2);
    for i := 0 to Out1.Size - 1 do
      AssertEquals('save/load forward equality at ' + IntToStr(i),
        Out1.FData[i], Out2.FData[i], 1e-7);
  finally
    NN2.Free;
    Out2.Free;
    Out1.Free;
    Input.Free;
    NN.Free;
  end;
end;

procedure TTestNeuralPretrained.TestF16Decode;
begin
  RandSeed := 424242;
  // Hand-computed IEEE binary16 bit patterns.
  AssertEquals('f16 1.0', 1.0, DecodeF16($3C00), 0);
  AssertEquals('f16 -2.0', -2.0, DecodeF16($C000), 0);
  AssertEquals('f16 0.5', 0.5, DecodeF16($3800), 0);
  AssertEquals('f16 65504 (max normal)', 65504.0, DecodeF16($7BFF), 0);
  // 0x3555: exp=13 -> 2^-2, mantissa=0x155=341 -> (1+341/1024)*0.25
  AssertEquals('f16 0x3555', (1.0 + 341.0 / 1024.0) * 0.25,
    DecodeF16($3555), 0);
  // Subnormals: value = mantissa * 2^-24.
  AssertEquals('f16 smallest subnormal', 5.9604644775390625e-8,
    DecodeF16($0001), 0);
  AssertEquals('f16 largest subnormal', 1023.0 * 5.9604644775390625e-8,
    DecodeF16($03FF), 0);
  // Signed zero.
  AssertEquals('f16 +0', 0.0, DecodeF16($0000), 0);
  AssertEquals('f16 -0', 0.0, DecodeF16($8000), 0);
end;

procedure TTestNeuralPretrained.TestBF16Decode;
begin
  RandSeed := 424242;
  // bf16 is the upper half of a single's bit pattern.
  AssertEquals('bf16 1.0', 1.0, DecodeBF16($3F80), 0);
  AssertEquals('bf16 -1.0', -1.0, DecodeBF16($BF80), 0);
  AssertEquals('bf16 3.140625', 3.140625, DecodeBF16($4049), 0);
  AssertEquals('bf16 -0.5', -0.5, DecodeBF16($BF00), 0);
  AssertEquals('bf16 256', 256.0, DecodeBF16($4380), 0);
  AssertEquals('bf16 +0', 0.0, DecodeBF16($0000), 0);
  // Smallest bf16 normal = 2^-126.
  AssertEquals('bf16 2^-126', 1.1754943508222875e-38, DecodeBF16($0080), 0);
end;

procedure TTestNeuralPretrained.TestReaderReadsF16AndBF16Tensors;
var
  Path: string;
  Reader: TNNetSafeTensorsReader;
  V: TNNetVolume;
begin
  RandSeed := 424242;
  // Two tensors: "a" = F16 [2] = {1.0 (0x3C00), -2.0 (0xC000)},
  //              "b" = BF16 [2] = {1.0 (0x3F80), 3.140625 (0x4049)}.
  // Bytes are little-endian.
  Path := WriteTempSafeTensors(
    '{"a":{"dtype":"F16","shape":[2],"data_offsets":[0,4]},' +
    '"b":{"dtype":"BF16","shape":[2],"data_offsets":[4,8]}}',
    [$00, $3C, $00, $C0, $80, $3F, $49, $40]);
  try
    Reader := TNNetSafeTensorsReader.Create(Path);
    try
      AssertEquals('tensor count', 2, Reader.Count);
      AssertEquals('a dtype', 'F16', Reader.GetDType('a'));
      AssertEquals('b dtype', 'BF16', Reader.GetDType('b'));
      V := TNNetVolume.Create;
      try
        Reader.LoadTensorFlat('a', V);
        AssertEquals('a size', 2, V.Size);
        AssertEquals('a[0]', 1.0, V.FData[0], 0);
        AssertEquals('a[1]', -2.0, V.FData[1], 0);
        Reader.LoadTensorFlat('b', V);
        AssertEquals('b[0]', 1.0, V.FData[0], 0);
        AssertEquals('b[1]', 3.140625, V.FData[1], 0);
      finally
        V.Free;
      end;
    finally
      Reader.Free;
    end;
  finally
    DeleteFile(Path);
  end;
end;

procedure TTestNeuralPretrained.TestReaderRejectsGarbage;
var
  Path: string;
  Reader: TNNetSafeTensorsReader;
  FS: TFileStream;
  Failed: boolean;
begin
  RandSeed := 424242;
  // (a) File shorter than the 8-byte header length.
  Path := GetTempDir(false) + 'cai_st_trunc.safetensors';
  FS := TFileStream.Create(Path, fmCreate);
  FS.WriteBuffer(Path[1], 4);
  FS.Free;
  Failed := false;
  try
    Reader := TNNetSafeTensorsReader.Create(Path);
    Reader.Free;
  except
    on ESafeTensorsError do Failed := true;
  end;
  DeleteFile(Path);
  AssertTrue('truncated file must be rejected', Failed);

  // (b) Header length exceeding the file size.
  Path := WriteTempSafeTensors('', []);
  // Rewrite the first 8 bytes with a huge length.
  FS := TFileStream.Create(Path, fmOpenReadWrite);
  FS.Position := 0;
  FS.WriteDWord($FFFFFF);
  FS.Free;
  Failed := false;
  try
    Reader := TNNetSafeTensorsReader.Create(Path);
    Reader.Free;
  except
    on ESafeTensorsError do Failed := true;
  end;
  DeleteFile(Path);
  AssertTrue('oversized header length must be rejected', Failed);

  // (c) Header is not JSON.
  Path := WriteTempSafeTensors('this is not json at all!!', []);
  Failed := false;
  try
    Reader := TNNetSafeTensorsReader.Create(Path);
    Reader.Free;
  except
    on ESafeTensorsError do Failed := true;
  end;
  DeleteFile(Path);
  AssertTrue('non-JSON header must be rejected', Failed);

  // (d) data_offsets pointing beyond the data section.
  Path := WriteTempSafeTensors(
    '{"t":{"dtype":"F32","shape":[4],"data_offsets":[0,16]}}',
    [$00, $00, $80, $3F]); // only 4 payload bytes, 16 promised
  Failed := false;
  try
    Reader := TNNetSafeTensorsReader.Create(Path);
    Reader.Free;
  except
    on ESafeTensorsError do Failed := true;
  end;
  DeleteFile(Path);
  AssertTrue('out-of-bounds data_offsets must be rejected', Failed);

  // (e) Element count inconsistent with the byte span.
  Path := WriteTempSafeTensors(
    '{"t":{"dtype":"F32","shape":[2],"data_offsets":[0,4]}}',
    [$00, $00, $80, $3F]);
  Failed := false;
  try
    Reader := TNNetSafeTensorsReader.Create(Path);
    Reader.Free;
  except
    on ESafeTensorsError do Failed := true;
  end;
  DeleteFile(Path);
  AssertTrue('shape/byte-span mismatch must be rejected', Failed);
end;

procedure TTestNeuralPretrained.TestReaderReadsTinyFixture;
var
  Reader: TNNetSafeTensorsReader;
begin
  RandSeed := 424242;
  Reader := TNNetSafeTensorsReader.Create(FixturePath('tiny_gpt2.safetensors'));
  try
    AssertTrue('wte present', Reader.HasTensor('wte.weight'));
    AssertEquals('wte dtype', 'F32', Reader.GetDType('wte.weight'));
    AssertEquals('wte dims', 2, Reader.DimCount('wte.weight'));
    AssertEquals('vocab', 11, Reader.DimSize('wte.weight', 0));
    AssertEquals('d_model', 8, Reader.DimSize('wte.weight', 1));
    AssertEquals('wpe rows', 16, Reader.DimSize('wpe.weight', 0));
    AssertEquals('c_attn shape', '[8, 24]',
      Reader.ShapeAsString('h.0.attn.c_attn.weight'));
    AssertTrue('block 1 present', Reader.HasTensor('h.1.ln_1.weight'));
    AssertTrue('block 2 absent', not Reader.HasTensor('h.2.ln_1.weight'));
  finally
    Reader.Free;
  end;
end;

procedure TTestNeuralPretrained.TestImporterFailsOnMissingTensor;
var
  Path: string;
  NN: TNNet;
  Failed: boolean;
  Payload: array of byte;
  i: integer;
begin
  RandSeed := 424242;
  // A "checkpoint" containing ONLY wte.weight [2, 4]: the importer must
  // fail loudly on the missing wpe.weight, not import partially.
  SetLength(Payload, 2 * 4 * 4);
  for i := 0 to High(Payload) do Payload[i] := 0;
  Path := WriteTempSafeTensors(
    '{"wte.weight":{"dtype":"F32","shape":[2,4],"data_offsets":[0,32]}}',
    Payload);
  Failed := false;
  NN := nil;
  try
    try
      NN := BuildGPT2FromSafeTensors(Path, 4, 2);
    except
      on EPretrainedImportError do Failed := true;
    end;
  finally
    NN.Free;
    DeleteFile(Path);
  end;
  AssertTrue('missing wpe.weight must abort the import', Failed);
end;

procedure TTestNeuralPretrained.TestGPT2ConfigFromFixture;
var
  Reader: TNNetSafeTensorsReader;
  Config: TGPT2Config;
begin
  RandSeed := 424242;
  Reader := TNNetSafeTensorsReader.Create(FixturePath('tiny_gpt2.safetensors'));
  try
    Config := ReadGPT2Config(Reader, 2);
    AssertEquals('n_layer', 2, Config.NLayers);
    AssertEquals('n_head', 2, Config.NHeads);
    AssertEquals('n_embd', 8, Config.NEmbd);
    AssertEquals('n_ctx', 16, Config.NCtx);
    AssertEquals('vocab', 11, Config.VocabSize);
    AssertEquals('prefix', '', Config.Prefix);
  finally
    Reader.Free;
  end;
end;

procedure TTestNeuralPretrained.TestGPT2LogitParity;
var
  NN: TNNet;
  Config: TGPT2Config;
  RefRoot: TJSONData;
  Sequences, SeqArr, LogitsArr, PosArr, RowArr: TJSONArray;
  Input, Output: TNNetVolume;
  RefJson: TStringList;
  SeqCnt, PosCnt, TokCnt: integer;
  Diff, MaxDiff: double;
  SeqLen, Vocab: integer;
begin
  RandSeed := 424242;
  NN := BuildGPT2FromSafeTensorsEx(FixturePath('tiny_gpt2.safetensors'),
    Config, {SeqLen=}0, {NumHeads=}2);
  RefJson := TStringList.Create;
  Input := TNNetVolume.Create;
  Output := TNNetVolume.Create;
  RefRoot := nil;
  try
    AssertEquals('n_layer', 2, Config.NLayers);
    SeqLen := Config.NCtx;
    Vocab := Config.VocabSize;
    RefJson.LoadFromFile(FixturePath('tiny_gpt2_logits.json'));
    RefRoot := GetJSON(RefJson.Text);
    Sequences := TJSONArray(TJSONObject(RefRoot).Find('sequences'));
    LogitsArr := TJSONArray(TJSONObject(RefRoot).Find('logits'));
    AssertTrue('sequences present', Sequences <> nil);
    AssertTrue('logits present', LogitsArr <> nil);
    AssertTrue('at least 3 sequences', Sequences.Count >= 3);
    MaxDiff := 0;
    Input.ReSize(SeqLen, 1, 1);
    for SeqCnt := 0 to Sequences.Count - 1 do
    begin
      SeqArr := TJSONArray(Sequences.Items[SeqCnt]);
      AssertEquals('sequence length', SeqLen, SeqArr.Count);
      for PosCnt := 0 to SeqLen - 1 do
        Input.FData[PosCnt] := SeqArr.Items[PosCnt].AsInteger;
      NN.Compute(Input);
      NN.GetOutput(Output);
      AssertEquals('output size', SeqLen * Vocab, Output.Size);
      PosArr := TJSONArray(LogitsArr.Items[SeqCnt]);
      for PosCnt := 0 to SeqLen - 1 do
      begin
        RowArr := TJSONArray(PosArr.Items[PosCnt]);
        for TokCnt := 0 to Vocab - 1 do
        begin
          Diff := Abs(Output.FData[PosCnt * Vocab + TokCnt] -
            RowArr.Items[TokCnt].AsFloat);
          if Diff > MaxDiff then MaxDiff := Diff;
        end;
      end;
    end;
    // f32 end-to-end vs the float64 Python oracle on f32-rounded weights:
    // observed max |diff| is ~1.4e-6, so the 1e-4 gate has a ~70x margin
    // (the hard acceptance ceiling is 1e-3). NEVER loosen the gate past
    // 1e-3 - if parity breaks, fix the model, don't widen the tolerance.
    AssertTrue('GPT-2 logit parity: max |diff| = ' +
      FloatToStr(MaxDiff) + ' must be < 1e-4', MaxDiff < 1e-4);
  finally
    RefRoot.Free;
    Output.Free;
    Input.Free;
    RefJson.Free;
    NN.Free;
  end;
end;

initialization
  RegisterTest(TTestNeuralPretrained);
end.
