unit TestNeuralNumpy;
(*
Tests for neuralnumpy.pas: the NumPy .npy / .npz reader+writer.
 - F32 round-trip is bit-exact (write a volume, read it back, compare bits).
 - F16 round-trip is value-exact within half-precision tolerance.
 - F64 / int dtypes round-trip through the single representation.
 - .npz STORED archive round-trips a named set of volumes.
 - Fortran-order and object-dtype headers are rejected.
 - When a committed numpy-produced fixture is present (tests/fixtures/
   numpy_crosscheck.npz, generated by tools/numpy_crosscheck_fixture.py),
   the reader is cross-checked against real numpy output.
Coded by Claude (AI).
*)

{$mode objfpc}{$H+}

interface

uses
  Classes, SysUtils, Math, fpcunit, testregistry,
  neuralvolume, neuralnumpy;

type
  TTestNeuralNumpy = class(TTestCase)
  private
    function TmpName(const Suffix: string): string;
    function MakeRamp(N: integer): TNNetVolume;
  published
    procedure TestNpyF32BitExactRoundTrip;
    procedure TestNpyF16ValueRoundTrip;
    procedure TestNpyF64RoundTrip;
    procedure TestNpyInt32RoundTrip;
    procedure TestNpyInt8RoundTrip;
    procedure TestNpy2DShapeMapping;
    procedure TestNpzNamedSetRoundTrip;
    procedure TestRejectFortranOrder;
    procedure TestRejectObjectDtype;
    procedure TestNumpyCrossCheckFixture;
  end;

implementation

function TTestNeuralNumpy.TmpName(const Suffix: string): string;
begin
  Result := GetTempDir + 'cai_npy_test_' + Suffix;
end;

function TTestNeuralNumpy.MakeRamp(N: integer): TNNetVolume;
var i: integer;
begin
  Result := TNNetVolume.Create(N, 1, 1);
  for i := 0 to N - 1 do
    Result.FData[i] := (i - N / 2) * 0.125;
end;

procedure TTestNeuralNumpy.TestNpyF32BitExactRoundTrip;
var
  V, R: TNNetVolume;
  fn: string;
  i: integer;
begin
  V := MakeRamp(17);
  R := nil;
  fn := TmpName('f32.npy');
  try
    SaveVolumeToNpy(fn, V, [], 'f4');
    R := LoadVolumeFromNpy(fn);
    AssertEquals('size', V.Size, R.Size);
    for i := 0 to V.Size - 1 do
      // bit-exact: identical singles
      AssertTrue('bit-exact element ' + IntToStr(i),
        PCardinal(@V.FData[i])^ = PCardinal(@R.FData[i])^);
  finally
    V.Free; R.Free; DeleteFile(fn);
  end;
end;

procedure TTestNeuralNumpy.TestNpyF16ValueRoundTrip;
var
  V, R: TNNetVolume;
  fn: string;
  i: integer;
begin
  V := MakeRamp(13);
  R := nil;
  fn := TmpName('f16.npy');
  try
    SaveVolumeToNpy(fn, V, [], 'f2');
    R := LoadVolumeFromNpy(fn);
    AssertEquals('size', V.Size, R.Size);
    for i := 0 to V.Size - 1 do
      // half precision: ~1e-3 relative; values here are small multiples of
      // 0.125 which are exactly representable, so demand tight equality.
      AssertEquals('f16 element ' + IntToStr(i), V.FData[i], R.FData[i], 0.01);
  finally
    V.Free; R.Free; DeleteFile(fn);
  end;
end;

procedure TTestNeuralNumpy.TestNpyF64RoundTrip;
var
  V, R: TNNetVolume;
  fn: string;
  i: integer;
begin
  V := MakeRamp(9);
  R := nil;
  fn := TmpName('f64.npy');
  try
    SaveVolumeToNpy(fn, V, [], 'f8');
    R := LoadVolumeFromNpy(fn);
    for i := 0 to V.Size - 1 do
      AssertEquals('f64 element ' + IntToStr(i), V.FData[i], R.FData[i], 1e-6);
  finally
    V.Free; R.Free; DeleteFile(fn);
  end;
end;

procedure TTestNeuralNumpy.TestNpyInt32RoundTrip;
var
  V, R: TNNetVolume;
  fn: string;
  i: integer;
begin
  V := TNNetVolume.Create(6, 1, 1);
  for i := 0 to 5 do V.FData[i] := i * 1000 - 2500;
  R := nil;
  fn := TmpName('i32.npy');
  try
    SaveVolumeToNpy(fn, V, [], 'i4');
    R := LoadVolumeFromNpy(fn);
    for i := 0 to 5 do
      AssertEquals('i32 element ' + IntToStr(i), V.FData[i], R.FData[i], 0.0);
  finally
    V.Free; R.Free; DeleteFile(fn);
  end;
end;

procedure TTestNeuralNumpy.TestNpyInt8RoundTrip;
var
  V, R: TNNetVolume;
  fn: string;
  i: integer;
begin
  V := TNNetVolume.Create(5, 1, 1);
  V.FData[0] := -128; V.FData[1] := -1; V.FData[2] := 0;
  V.FData[3] := 1; V.FData[4] := 127;
  R := nil;
  fn := TmpName('i8.npy');
  try
    SaveVolumeToNpy(fn, V, [], 'i1');
    R := LoadVolumeFromNpy(fn);
    for i := 0 to 4 do
      AssertEquals('i8 element ' + IntToStr(i), V.FData[i], R.FData[i], 0.0);
  finally
    V.Free; R.Free; DeleteFile(fn);
  end;
end;

procedure TTestNeuralNumpy.TestNpy2DShapeMapping;
var
  V, Res: TNNetVolume;
  fn: string;
  rr, cc: integer;
begin
  // 3 rows x 4 cols, row-major; element (rr,cc) = rr*10+cc.
  V := TNNetVolume.Create(4, 3, 1); // X=cols, Y=rows
  for rr := 0 to 2 do
    for cc := 0 to 3 do
      V.FData[rr * 4 + cc] := rr * 10 + cc;
  Res := nil;
  fn := TmpName('2d.npy');
  try
    SaveVolumeToNpy(fn, V, [3, 4], 'f4'); // numpy shape (3,4)
    Res := LoadVolumeFromNpy(fn);
    AssertEquals('SizeX=cols', 4, Res.SizeX);
    AssertEquals('SizeY=rows', 3, Res.SizeY);
    AssertEquals('Depth', 1, Res.Depth);
    for rr := 0 to 2 do
      for cc := 0 to 3 do
        AssertEquals('elem', rr * 10 + cc, Res.Get(cc, rr, 0), 0.0);
  finally
    V.Free; Res.Free; DeleteFile(fn);
  end;
end;

procedure TTestNeuralNumpy.TestNpzNamedSetRoundTrip;
var
  A, B, RA, RB: TNNetVolume;
  W: TNNetNpzWriter;
  Reader: TNNetNpzReader;
  fn: string;
  i: integer;
begin
  A := MakeRamp(7);
  B := TNNetVolume.Create(3, 1, 1);
  B.FData[0] := 1.5; B.FData[1] := -2.25; B.FData[2] := 100.0;
  RA := nil; RB := nil; Reader := nil;
  fn := TmpName('set.npz');
  W := TNNetNpzWriter.Create(fn);
  try
    W.AddVolume('alpha', A, [], 'f4');
    W.AddVolume('beta', B, [3], 'f4');
    W.Save;

    Reader := TNNetNpzReader.Create(fn);
    AssertEquals('count', 2, Reader.Count);
    AssertTrue('has alpha', Reader.HasKey('alpha'));
    AssertTrue('has beta', Reader.HasKey('beta'));
    RA := Reader.LoadVolume('alpha');
    RB := Reader.LoadVolume('beta');
    AssertEquals('alpha size', A.Size, RA.Size);
    for i := 0 to A.Size - 1 do
      AssertTrue('alpha bit ' + IntToStr(i),
        PCardinal(@A.FData[i])^ = PCardinal(@RA.FData[i])^);
    for i := 0 to B.Size - 1 do
      AssertTrue('beta bit ' + IntToStr(i),
        PCardinal(@B.FData[i])^ = PCardinal(@RB.FData[i])^);
  finally
    W.Free; Reader.Free;
    A.Free; B.Free; RA.Free; RB.Free; DeleteFile(fn);
  end;
end;

procedure TTestNeuralNumpy.TestRejectFortranOrder;
var
  fn: string;
  S: TFileStream;
  Header: string;
  Hdr: TBytes;
  Magic: array[0..7] of byte;
  Lo: word;
  raised_: boolean;
  V: TNNetVolume;
  i: integer;
begin
  // Hand-craft a minimal v1.0 .npy with fortran_order True.
  fn := TmpName('fortran.npy');
  Header := '{''descr'': ''<f4'', ''fortran_order'': True, ''shape'': (2, 2), }';
  while (10 + Length(Header) + 1) mod 64 <> 0 do Header := Header + ' ';
  Header := Header + #10;
  Magic[0] := $93; Magic[1] := Ord('N'); Magic[2] := Ord('U');
  Magic[3] := Ord('M'); Magic[4] := Ord('P'); Magic[5] := Ord('Y');
  Magic[6] := 1; Magic[7] := 0;
  Lo := Length(Header);
  S := TFileStream.Create(fn, fmCreate);
  try
    S.WriteBuffer(Magic, 8);
    S.WriteBuffer(Lo, 2);
    SetLength(Hdr, Length(Header));
    for i := 1 to Length(Header) do Hdr[i - 1] := Ord(Header[i]);
    S.WriteBuffer(Hdr[0], Length(Hdr));
    // 4 float32 zeros
    SetLength(Hdr, 16);
    for i := 0 to 15 do Hdr[i] := 0;
    S.WriteBuffer(Hdr[0], 16);
  finally
    S.Free;
  end;
  raised_ := false;
  V := nil;
  try
    try
      V := LoadVolumeFromNpy(fn);
    except
      on E: ENumpyError do raised_ := true;
    end;
  finally
    V.Free; DeleteFile(fn);
  end;
  AssertTrue('Fortran order must be rejected', raised_);
end;

procedure TTestNeuralNumpy.TestRejectObjectDtype;
var
  fn: string;
  S: TFileStream;
  Header: string;
  Hdr: TBytes;
  Magic: array[0..7] of byte;
  Lo: word;
  raised_: boolean;
  V: TNNetVolume;
  i: integer;
begin
  fn := TmpName('object.npy');
  Header := '{''descr'': ''|O'', ''fortran_order'': False, ''shape'': (1,), }';
  while (10 + Length(Header) + 1) mod 64 <> 0 do Header := Header + ' ';
  Header := Header + #10;
  Magic[0] := $93; Magic[1] := Ord('N'); Magic[2] := Ord('U');
  Magic[3] := Ord('M'); Magic[4] := Ord('P'); Magic[5] := Ord('Y');
  Magic[6] := 1; Magic[7] := 0;
  Lo := Length(Header);
  S := TFileStream.Create(fn, fmCreate);
  try
    S.WriteBuffer(Magic, 8);
    S.WriteBuffer(Lo, 2);
    SetLength(Hdr, Length(Header));
    for i := 1 to Length(Header) do Hdr[i - 1] := Ord(Header[i]);
    S.WriteBuffer(Hdr[0], Length(Hdr));
  finally
    S.Free;
  end;
  raised_ := false;
  V := nil;
  try
    try
      V := LoadVolumeFromNpy(fn);
    except
      on E: ENumpyError do raised_ := true;
    end;
  finally
    V.Free; DeleteFile(fn);
  end;
  AssertTrue('Object dtype must be rejected', raised_);
end;

procedure TTestNeuralNumpy.TestNumpyCrossCheckFixture;
var
  FixDir, NpyPath, NpzPath: string;
  V: TNNetVolume;
  Reader: TNNetNpzReader;
  i: integer;
begin
  // Cross-check against arrays produced by real numpy. The fixtures are tiny
  // and committed; if absent (clean checkout without the generator run) the
  // test is skipped rather than failed.
  FixDir := ExtractFilePath(ParamStr(0)) + 'fixtures' + PathDelim;
  NpyPath := FixDir + 'numpy_crosscheck_f32.npy';
  NpzPath := FixDir + 'numpy_crosscheck.npz';
  if not FileExists(NpyPath) then
  begin
    // try a path relative to CWD as well
    NpyPath := 'fixtures' + PathDelim + 'numpy_crosscheck_f32.npy';
    NpzPath := 'fixtures' + PathDelim + 'numpy_crosscheck.npz';
  end;
  if not FileExists(NpyPath) then
  begin
    Ignore('numpy cross-check fixtures absent; run ' +
      'tools/numpy_crosscheck_fixture.py to generate');
    exit;
  end;
  // The generator stores arange(12, dtype=f4) reshaped (3,4) in the .npy, and
  // {'ramp': arange(6,f4), 'half': arange(6,f2)*0.5} in the .npz.
  V := LoadVolumeFromNpy(NpyPath);
  try
    AssertEquals('crosscheck f32 size', 12, V.Size);
    for i := 0 to 11 do
      AssertEquals('crosscheck f32 v[' + IntToStr(i) + ']', i, V.FData[i], 0.0);
    AssertEquals('crosscheck f32 SizeX', 4, V.SizeX);
    AssertEquals('crosscheck f32 SizeY', 3, V.SizeY);
  finally
    V.Free;
  end;

  if FileExists(NpzPath) then
  begin
    Reader := TNNetNpzReader.Create(NpzPath);
    try
      AssertTrue('npz has ramp', Reader.HasKey('ramp'));
      AssertTrue('npz has half', Reader.HasKey('half'));
      V := Reader.LoadVolume('ramp');
      try
        for i := 0 to 5 do
          AssertEquals('npz ramp[' + IntToStr(i) + ']', i, V.FData[i], 0.0);
      finally V.Free; end;
      V := Reader.LoadVolume('half');
      try
        for i := 0 to 5 do
          AssertEquals('npz half[' + IntToStr(i) + ']', i * 0.5, V.FData[i],
            0.01);
      finally V.Free; end;
    finally
      Reader.Free;
    end;
  end;
end;

initialization
  RegisterTest(TTestNeuralNumpy);
end.
