unit TestNeuralPretrained;
// Tests for the safetensors reader (neuralsafetensors.pas) and the GPT-2
// and Llama pretrained-checkpoint importers (neuralpretrained.pas).
//
// The flagship tests are TestGPT2LogitParity and TestLlamaLogitParity: each
// loads a committed tiny random checkpoint (tests/fixtures/tiny_gpt2 /
// tiny_llama .safetensors, generated by tools/gpt2_tiny_fixture.py /
// tools/llama_tiny_fixture.py) and asserts that the imported TNNet's logits
// match the INDEPENDENT pure-Python forward (the oracle, same generator
// script; the Llama oracle is itself verified against HF transformers'
// LlamaForCausalLM to ~9e-7) to < 1e-3 (typically ~1e-5 end-to-end f32).
//
// This unit is coded by Claude (AI).
{$mode objfpc}{$H+}

interface

uses
  Classes, SysUtils, fpcunit, testregistry, fpjson, jsonparser,
  neuralvolume, neuralnetwork, neuralsafetensors, neuralpretrained,
  neuralhftokenizer;

type
  TTestNeuralPretrained = class(TTestCase)
  private
    function FixturePath(const FileName: string): string;
    // Composes a minimal safetensors byte stream into a temp file and
    // returns its path. HeaderJson is written verbatim (preceded by its
    // 8-byte little-endian length); Payload is the raw data section.
    function WriteTempSafeTensors(const HeaderJson: string;
      const Payload: array of byte): string;
    // Byte-for-byte file copy (used to assemble HF-style checkpoint
    // directories - config.json + model.safetensors - in a temp dir for
    // the BuildFromPretrained directory-dispatch tests).
    procedure CopyFileTo(const Src, Dst: string);
    // Shared parity loop: feeds every "sequences" row of the reference
    // logits fixture (JSON {"sequences": [[ids..]..], "logits": [[[..]]]})
    // through NN and asserts max |logit diff| < 1e-4 (hard ceiling 1e-3 -
    // NEVER loosen past it; fix the model instead).
    procedure AssertLogitParityWithFixture(NN: TNNet;
      const LogitsFileName: string; SeqLen, Vocab: integer);
    // BERT parity loop: feeds every "sequences"/"token_types" pair of the
    // reference fixture (JSON {"sequences", "token_types", "hidden",
    // "pooler"}) through NN as a (SeqLen,1,2) volume (ch0=token id,
    // ch1=segment id). PoolerRow0Only=false compares all SeqLen rows of
    // the (SeqLen,1,Hidden) output against "hidden"; true compares ONLY
    // row 0 against "pooler" (the [CLS] pooler_output of a net built with
    // pIncludePooler=true). Gate 2e-5: TIGHTER than the 1e-4 logit gate on
    // purpose - the exact-vs-tanh GELU difference is ~6e-5 on this fixture
    // and must FAIL (true f32 parity is ~1e-6). Never loosen.
    procedure AssertBertParityWithFixture(NN: TNNet;
      const HiddenFileName: string; SeqLen, Hidden: integer;
      PoolerRow0Only: boolean);
    // Sequence-classification parity loop: feeds every "sequences" row of
    // the fixture through NN ((SeqLen,1,2) token|token-type ids for
    // BertStyle, else (SeqLen,1,1) token ids), selects the pooled row via
    // SelectTokenLogits - row 0 for BERT's [CLS]-first pooling, the
    // fixture's "pooled_position" (the last non-pad token) for GPT-2 -
    // and asserts class-logit parity < 1e-4 PLUS the id2label round-trip:
    // ClassIndexToLabel(argmax) must equal the fixture's pinned label.
    procedure AssertSeqClsParityWithFixture(NN: TNNet;
      const LogitsFileName: string; SeqLen: integer; BertStyle: boolean;
      Id2Label: TStringList);
  published
    procedure TestTokenLayerNormForwardAndSaveLoad;
    procedure TestLearnedPositionalEmbeddingForwardAndSaveLoad;
    procedure TestF16Decode;
    procedure TestBF16Decode;
    procedure TestReaderReadsF16AndBF16Tensors;
    procedure TestReaderRejectsGarbage;
    procedure TestReaderReadsTinyFixture;
    procedure TestImporterFailsOnMissingTensor;
    procedure TestGPT2ConfigFromFixture;
    procedure TestGPT2LogitParity;
    procedure TestMakeInferenceOnlyKeepsOutputs;
    procedure TestTokenRMSNormForwardAndSaveLoad;
    procedure TestRotaryHalfPermutationMatchesHFRotateHalf;
    procedure TestSwiGLUMatchesLlamaMLPGating;
    procedure TestLlamaConfigFromJSONFile;
    procedure TestLlamaImporterFailsOnMissingTensor;
    procedure TestLlamaLogitParity;
    procedure TestShardedReaderMatchesSingleFile;
    procedure TestShardedLlamaLogitsBitIdentical;
    procedure TestDistilGPT2LogitParity;
    procedure TestSmolLM2LogitParity;
    procedure TestMistralLogitParity;
    procedure TestQwen2LogitParity;
    procedure TestQwen3LogitParity;
    procedure TestGPTNeoConfigFromJSONFile;
    procedure TestGPTNeoLogitParity;
    procedure TestGPTNeoXConfigFromJSONFile;
    procedure TestGPTNeoXLogitParity;
    procedure TestGPTNeoXSequentialLogitParity;
    procedure TestGPTJConfigFromJSONFile;
    procedure TestGPTJLogitParity;
    procedure TestPhiConfigFromJSONFile;
    procedure TestPhiLogitParity;
    procedure TestBertConfigFromJSONFile;
    procedure TestBertHiddenStateParity;
    procedure TestBertPoolerParity;
    procedure TestDistilBertConfigFromJSONFile;
    procedure TestDistilBertHiddenStateParity;
    procedure TestRobertaConfigFromJSONFile;
    procedure TestRobertaHiddenStateParity;
    procedure TestRobertaPoolerParity;
    procedure TestBertSeqClsLogitParity;
    procedure TestGPT2SeqClsLogitParity;
    procedure TestBuildFromPretrainedSeqClsDispatch;
    procedure TestBertPoolSentenceEmbedding;
    procedure TestBertTokenizeSentence;
    procedure TestBuildFromPretrainedDispatch;
    procedure TestBuildFromPretrainedRejectsUnsupportedModelType;
  end;

implementation

function TTestNeuralPretrained.FixturePath(const FileName: string): string;
begin
  // RunAll.sh runs the suite from the tests/ directory; also probe the repo
  // root in case the binary is started from there.
  Result := 'fixtures' + DirectorySeparator + FileName;
  if not FileExists(Result) then
    Result := 'tests' + DirectorySeparator + 'fixtures' + DirectorySeparator +
      FileName;
  if not FileExists(Result) then
    Fail('Fixture not found: ' + FileName +
      ' (run python3 tools/gpt2_tiny_fixture.py from the repo root).');
end;

function TTestNeuralPretrained.WriteTempSafeTensors(const HeaderJson: string;
  const Payload: array of byte): string;
var
  FS: TFileStream;
  HeaderLen: QWord;
begin
  Result := GetTempDir(false) + 'cai_st_test_' + IntToStr(Random(1000000)) +
    '.safetensors';
  FS := TFileStream.Create(Result, fmCreate);
  try
    HeaderLen := Length(HeaderJson);
    FS.WriteBuffer(HeaderLen, 8);
    if HeaderJson <> '' then
      FS.WriteBuffer(HeaderJson[1], Length(HeaderJson));
    if Length(Payload) > 0 then
      FS.WriteBuffer(Payload[0], Length(Payload));
  finally
    FS.Free;
  end;
end;

procedure TTestNeuralPretrained.CopyFileTo(const Src, Dst: string);
var
  SrcStream, DstStream: TFileStream;
begin
  SrcStream := TFileStream.Create(Src, fmOpenRead);
  try
    DstStream := TFileStream.Create(Dst, fmCreate);
    try
      DstStream.CopyFrom(SrcStream, SrcStream.Size);
    finally
      DstStream.Free;
    end;
  finally
    SrcStream.Free;
  end;
end;

procedure TTestNeuralPretrained.AssertLogitParityWithFixture(NN: TNNet;
  const LogitsFileName: string; SeqLen, Vocab: integer);
var
  RefRoot: TJSONData;
  Sequences, SeqArr, LogitsArr, PosArr, RowArr: TJSONArray;
  Input, Output: TNNetVolume;
  RefJson: TStringList;
  SeqCnt, PosCnt, TokCnt: integer;
  Diff, MaxDiff: double;
begin
  RefJson := TStringList.Create;
  Input := TNNetVolume.Create;
  Output := TNNetVolume.Create;
  RefRoot := nil;
  try
    RefJson.LoadFromFile(LogitsFileName);
    RefRoot := GetJSON(RefJson.Text);
    Sequences := TJSONArray(TJSONObject(RefRoot).Find('sequences'));
    LogitsArr := TJSONArray(TJSONObject(RefRoot).Find('logits'));
    AssertTrue('sequences present', Sequences <> nil);
    AssertTrue('logits present', LogitsArr <> nil);
    AssertTrue('at least 3 sequences', Sequences.Count >= 3);
    MaxDiff := 0;
    Input.ReSize(SeqLen, 1, 1);
    for SeqCnt := 0 to Sequences.Count - 1 do
    begin
      SeqArr := TJSONArray(Sequences.Items[SeqCnt]);
      AssertEquals('sequence length', SeqLen, SeqArr.Count);
      for PosCnt := 0 to SeqLen - 1 do
        Input.FData[PosCnt] := SeqArr.Items[PosCnt].AsInteger;
      NN.Compute(Input);
      NN.GetOutput(Output);
      AssertEquals('output size', SeqLen * Vocab, Output.Size);
      PosArr := TJSONArray(LogitsArr.Items[SeqCnt]);
      for PosCnt := 0 to SeqLen - 1 do
      begin
        RowArr := TJSONArray(PosArr.Items[PosCnt]);
        for TokCnt := 0 to Vocab - 1 do
        begin
          Diff := Abs(Output.FData[PosCnt * Vocab + TokCnt] -
            RowArr.Items[TokCnt].AsFloat);
          if Diff > MaxDiff then MaxDiff := Diff;
        end;
      end;
    end;
    // f32 end-to-end vs the float64 oracle on f32-rounded weights. NEVER
    // loosen the gate past 1e-3 - if parity breaks, fix the model, don't
    // widen the tolerance.
    AssertTrue('logit parity vs ' + LogitsFileName + ': max |diff| = ' +
      FloatToStr(MaxDiff) + ' must be < 1e-4', MaxDiff < 1e-4);
  finally
    RefRoot.Free;
    Output.Free;
    Input.Free;
    RefJson.Free;
  end;
end;

procedure TTestNeuralPretrained.AssertBertParityWithFixture(NN: TNNet;
  const HiddenFileName: string; SeqLen, Hidden: integer;
  PoolerRow0Only: boolean);
var
  RefRoot: TJSONData;
  Sequences, TokenTypes, RefArr, SeqArr, TypeArr, PosArr, RowArr: TJSONArray;
  Input, Output: TNNetVolume;
  RefJson: TStringList;
  SeqCnt, PosCnt, ChanCnt, FirstPos, LastPos: integer;
  Diff, MaxDiff: double;
begin
  RefJson := TStringList.Create;
  Input := TNNetVolume.Create;
  Output := TNNetVolume.Create;
  RefRoot := nil;
  try
    RefJson.LoadFromFile(HiddenFileName);
    RefRoot := GetJSON(RefJson.Text);
    Sequences := TJSONArray(TJSONObject(RefRoot).Find('sequences'));
    TokenTypes := TJSONArray(TJSONObject(RefRoot).Find('token_types'));
    if PoolerRow0Only then
      RefArr := TJSONArray(TJSONObject(RefRoot).Find('pooler'))
    else
      RefArr := TJSONArray(TJSONObject(RefRoot).Find('hidden'));
    AssertTrue('sequences present', Sequences <> nil);
    AssertTrue('token_types present', TokenTypes <> nil);
    AssertTrue('reference present', RefArr <> nil);
    AssertTrue('at least 3 sequences', Sequences.Count >= 3);
    MaxDiff := 0;
    Input.ReSize(SeqLen, 1, 2);
    for SeqCnt := 0 to Sequences.Count - 1 do
    begin
      SeqArr := TJSONArray(Sequences.Items[SeqCnt]);
      TypeArr := TJSONArray(TokenTypes.Items[SeqCnt]);
      AssertEquals('sequence length', SeqLen, SeqArr.Count);
      AssertEquals('token_types length', SeqLen, TypeArr.Count);
      for PosCnt := 0 to SeqLen - 1 do
      begin
        Input.FData[PosCnt * 2] := SeqArr.Items[PosCnt].AsInteger;
        Input.FData[PosCnt * 2 + 1] := TypeArr.Items[PosCnt].AsInteger;
      end;
      NN.Compute(Input);
      NN.GetOutput(Output);
      AssertEquals('output size', SeqLen * Hidden, Output.Size);
      if PoolerRow0Only then
      begin
        FirstPos := 0;
        LastPos := 0; // only the [CLS] row carries the HF pooler_output
      end
      else
      begin
        FirstPos := 0;
        LastPos := SeqLen - 1;
      end;
      for PosCnt := FirstPos to LastPos do
      begin
        if PoolerRow0Only then
          RowArr := TJSONArray(RefArr.Items[SeqCnt])
        else
        begin
          PosArr := TJSONArray(RefArr.Items[SeqCnt]);
          RowArr := TJSONArray(PosArr.Items[PosCnt]);
        end;
        for ChanCnt := 0 to Hidden - 1 do
        begin
          Diff := Abs(Output.FData[PosCnt * Hidden + ChanCnt] -
            RowArr.Items[ChanCnt].AsFloat);
          if Diff > MaxDiff then MaxDiff := Diff;
        end;
      end;
    end;
    // 2e-5 gate (see the declaration comment): catches a tanh-approximated
    // GELU (~6e-5 on this fixture) while true f32 parity is ~1e-6. NEVER
    // loosen - fix the model instead.
    AssertTrue('BERT parity vs ' + HiddenFileName + ': max |diff| = ' +
      FloatToStr(MaxDiff) + ' must be < 2e-5', MaxDiff < 2e-5);
  finally
    RefRoot.Free;
    Output.Free;
    Input.Free;
    RefJson.Free;
  end;
end;

procedure TTestNeuralPretrained.AssertSeqClsParityWithFixture(NN: TNNet;
  const LogitsFileName: string; SeqLen: integer; BertStyle: boolean;
  Id2Label: TStringList);
var
  RefRoot: TJSONData;
  Obj: TJSONObject;
  Sequences, TokenTypes, LogitsArr, LabelsArr: TJSONArray;
  SeqArr, TypeArr, RowArr: TJSONArray;
  Input, Output, Logits: TNNetVolume;
  RefJson: TStringList;
  SeqCnt, PosCnt, LabelCnt, NumLabels, PooledPos, ArgMax: integer;
  Diff, MaxDiff: double;
begin
  RefJson := TStringList.Create;
  Input := TNNetVolume.Create;
  Output := TNNetVolume.Create;
  Logits := TNNetVolume.Create;
  RefRoot := nil;
  try
    RefJson.LoadFromFile(LogitsFileName);
    RefRoot := GetJSON(RefJson.Text);
    Obj := TJSONObject(RefRoot);
    Sequences := TJSONArray(Obj.Find('sequences'));
    LogitsArr := TJSONArray(Obj.Find('logits'));
    LabelsArr := TJSONArray(Obj.Find('labels'));
    AssertTrue('sequences present', Sequences <> nil);
    AssertTrue('logits present', LogitsArr <> nil);
    AssertTrue('labels present', LabelsArr <> nil);
    AssertTrue('at least 3 sequences', Sequences.Count >= 3);
    TokenTypes := nil;
    if BertStyle then
    begin
      TokenTypes := TJSONArray(Obj.Find('token_types'));
      AssertTrue('token_types present', TokenTypes <> nil);
      PooledPos := 0; // [CLS]-first pooling (BertForSequenceClassification)
      Input.ReSize(SeqLen, 1, 2);
    end
    else
    begin
      // Last-non-pad-token pooling (GPT2ForSequenceClassification); the
      // fixture's sequences are full-length, so this is SeqLen - 1.
      PooledPos := Obj.Get('pooled_position', SeqLen - 1);
      AssertEquals('pooled position is the last token', SeqLen - 1,
        PooledPos);
      Input.ReSize(SeqLen, 1, 1);
    end;
    MaxDiff := 0;
    for SeqCnt := 0 to Sequences.Count - 1 do
    begin
      SeqArr := TJSONArray(Sequences.Items[SeqCnt]);
      AssertEquals('sequence length', SeqLen, SeqArr.Count);
      if BertStyle then
      begin
        TypeArr := TJSONArray(TokenTypes.Items[SeqCnt]);
        for PosCnt := 0 to SeqLen - 1 do
        begin
          Input.FData[PosCnt * 2] := SeqArr.Items[PosCnt].AsInteger;
          Input.FData[PosCnt * 2 + 1] := TypeArr.Items[PosCnt].AsInteger;
        end;
      end
      else
        for PosCnt := 0 to SeqLen - 1 do
          Input.FData[PosCnt] := SeqArr.Items[PosCnt].AsInteger;
      NN.Compute(Input);
      NN.GetOutput(Output);
      RowArr := TJSONArray(LogitsArr.Items[SeqCnt]);
      NumLabels := RowArr.Count;
      AssertEquals('per-position class logits', SeqLen * NumLabels,
        Output.Size);
      SelectTokenLogits(Output, PooledPos, Logits);
      AssertEquals('selected logits size', NumLabels, Logits.Size);
      ArgMax := 0;
      for LabelCnt := 0 to NumLabels - 1 do
      begin
        Diff := Abs(Logits.FData[LabelCnt] -
          RowArr.Items[LabelCnt].AsFloat);
        if Diff > MaxDiff then MaxDiff := Diff;
        if Logits.FData[LabelCnt] > Logits.FData[ArgMax] then
          ArgMax := LabelCnt;
      end;
      // id2label round-trip: argmax class index -> label string.
      AssertEquals('label of sequence ' + IntToStr(SeqCnt),
        LabelsArr.Items[SeqCnt].AsString,
        ClassIndexToLabel(Id2Label, ArgMax));
    end;
    // Same 1e-4 gate as the LM-logit parity tests. NEVER loosen past
    // 1e-3 - fix the model, don't widen the tolerance.
    AssertTrue('class-logit parity vs ' + LogitsFileName +
      ': max |diff| = ' + FloatToStr(MaxDiff) + ' must be < 1e-4',
      MaxDiff < 1e-4);
  finally
    RefRoot.Free;
    Logits.Free;
    Output.Free;
    Input.Free;
    RefJson.Free;
  end;
end;

procedure TTestNeuralPretrained.TestTokenLayerNormForwardAndSaveLoad;
var
  NN, NN2: TNNet;
  LN: TNNetLayer;
  Input, Out1, Out2: TNNetVolume;
  i, t, c: integer;
  Mean, Variance, Expected: double;
  TokenVals: array[0..3] of double;
begin
  RandSeed := 424242;
  // (SeqLen=3, 1, Depth=4) input; per-token normalization over Depth.
  NN := TNNet.Create();
  NN.AddLayer( TNNetInput.Create(3, 1, 4) );
  LN := NN.AddLayer( TNNetTokenLayerNorm.Create(1e-5) );
  // Distinct gamma/beta per channel.
  for c := 0 to 3 do
  begin
    LN.Neurons[0].Weights.FData[c] := 0.5 + 0.25 * c; // gamma
    LN.Neurons[1].Weights.FData[c] := 0.1 * c - 0.2;  // beta
  end;
  LN.FlushWeightCache();
  Input := TNNetVolume.Create(3, 1, 4);
  Out1 := TNNetVolume.Create;
  Out2 := TNNetVolume.Create;
  NN2 := TNNet.Create();
  try
    for i := 0 to Input.Size - 1 do
      Input.FData[i] := Sin(i * 1.7) * 2 + 0.3 * i;
    NN.Compute(Input);
    NN.GetOutput(Out1);
    // Hand-computed per-token LayerNorm for each of the 3 tokens.
    for t := 0 to 2 do
    begin
      Mean := 0;
      for c := 0 to 3 do
      begin
        TokenVals[c] := Input.FData[t * 4 + c];
        Mean := Mean + TokenVals[c];
      end;
      Mean := Mean / 4;
      Variance := 0;
      for c := 0 to 3 do
        Variance := Variance + Sqr(TokenVals[c] - Mean);
      Variance := Variance / 4;
      for c := 0 to 3 do
      begin
        Expected := (0.5 + 0.25 * c) *
          ((TokenVals[c] - Mean) / Sqrt(Variance + 1e-5)) + (0.1 * c - 0.2);
        AssertEquals('per-token LN value t=' + IntToStr(t) + ' c=' +
          IntToStr(c), Expected, Out1.FData[t * 4 + c], 1e-5);
      end;
    end;
    // Save/load round-trip must preserve structure and weights.
    NN2.LoadFromString(NN.SaveToString());
    AssertTrue('reloaded layer class',
      NN2.Layers[1] is TNNetTokenLayerNorm);
    NN2.Compute(Input);
    NN2.GetOutput(Out2);
    for i := 0 to Out1.Size - 1 do
      AssertEquals('save/load forward equality at ' + IntToStr(i),
        Out1.FData[i], Out2.FData[i], 1e-7);
  finally
    NN2.Free;
    Out2.Free;
    Out1.Free;
    Input.Free;
    NN.Free;
  end;
end;

procedure TTestNeuralPretrained.TestLearnedPositionalEmbeddingForwardAndSaveLoad;
var
  NN, NN2: TNNet;
  PosLayer: TNNetLayer;
  Input, Out1, Out2: TNNetVolume;
  i, x, c: integer;
begin
  RandSeed := 424242;
  // (SeqLen=3, 1, Depth=2) input with a MaxPosition=5 table: only the first
  // 3 rows participate.
  NN := TNNet.Create();
  NN.AddLayer( TNNetInput.Create(3, 1, 2) );
  PosLayer := NN.AddLayer( TNNetLearnedPositionalEmbedding.Create(5) );
  for x := 0 to 4 do
    for c := 0 to 1 do
      PosLayer.Neurons[0].Weights[x, 0, c] := 10 * x + c;
  PosLayer.FlushWeightCache();
  Input := TNNetVolume.Create(3, 1, 2);
  Out1 := TNNetVolume.Create;
  Out2 := TNNetVolume.Create;
  NN2 := TNNet.Create();
  try
    for i := 0 to Input.Size - 1 do Input.FData[i] := 0.5 * i;
    NN.Compute(Input);
    NN.GetOutput(Out1);
    for x := 0 to 2 do
      for c := 0 to 1 do
        AssertEquals('pos add x=' + IntToStr(x) + ' c=' + IntToStr(c),
          0.5 * (x * 2 + c) + 10 * x + c, Out1.FData[x * 2 + c], 1e-6);
    NN2.LoadFromString(NN.SaveToString());
    AssertTrue('reloaded layer class',
      NN2.Layers[1] is TNNetLearnedPositionalEmbedding);
    AssertEquals('MaxPosition round-trip', 5,
      TNNetLearnedPositionalEmbedding(NN2.Layers[1]).MaxPosition);
    NN2.Compute(Input);
    NN2.GetOutput(Out2);
    for i := 0 to Out1.Size - 1 do
      AssertEquals('save/load forward equality at ' + IntToStr(i),
        Out1.FData[i], Out2.FData[i], 1e-7);
  finally
    NN2.Free;
    Out2.Free;
    Out1.Free;
    Input.Free;
    NN.Free;
  end;
end;

procedure TTestNeuralPretrained.TestF16Decode;
begin
  RandSeed := 424242;
  // Hand-computed IEEE binary16 bit patterns.
  AssertEquals('f16 1.0', 1.0, DecodeF16($3C00), 0);
  AssertEquals('f16 -2.0', -2.0, DecodeF16($C000), 0);
  AssertEquals('f16 0.5', 0.5, DecodeF16($3800), 0);
  AssertEquals('f16 65504 (max normal)', 65504.0, DecodeF16($7BFF), 0);
  // 0x3555: exp=13 -> 2^-2, mantissa=0x155=341 -> (1+341/1024)*0.25
  AssertEquals('f16 0x3555', (1.0 + 341.0 / 1024.0) * 0.25,
    DecodeF16($3555), 0);
  // Subnormals: value = mantissa * 2^-24.
  AssertEquals('f16 smallest subnormal', 5.9604644775390625e-8,
    DecodeF16($0001), 0);
  AssertEquals('f16 largest subnormal', 1023.0 * 5.9604644775390625e-8,
    DecodeF16($03FF), 0);
  // Signed zero.
  AssertEquals('f16 +0', 0.0, DecodeF16($0000), 0);
  AssertEquals('f16 -0', 0.0, DecodeF16($8000), 0);
end;

procedure TTestNeuralPretrained.TestBF16Decode;
begin
  RandSeed := 424242;
  // bf16 is the upper half of a single's bit pattern.
  AssertEquals('bf16 1.0', 1.0, DecodeBF16($3F80), 0);
  AssertEquals('bf16 -1.0', -1.0, DecodeBF16($BF80), 0);
  AssertEquals('bf16 3.140625', 3.140625, DecodeBF16($4049), 0);
  AssertEquals('bf16 -0.5', -0.5, DecodeBF16($BF00), 0);
  AssertEquals('bf16 256', 256.0, DecodeBF16($4380), 0);
  AssertEquals('bf16 +0', 0.0, DecodeBF16($0000), 0);
  // Smallest bf16 normal = 2^-126.
  AssertEquals('bf16 2^-126', 1.1754943508222875e-38, DecodeBF16($0080), 0);
end;

procedure TTestNeuralPretrained.TestReaderReadsF16AndBF16Tensors;
var
  Path: string;
  Reader: TNNetSafeTensorsReader;
  V: TNNetVolume;
begin
  RandSeed := 424242;
  // Two tensors: "a" = F16 [2] = {1.0 (0x3C00), -2.0 (0xC000)},
  //              "b" = BF16 [2] = {1.0 (0x3F80), 3.140625 (0x4049)}.
  // Bytes are little-endian.
  Path := WriteTempSafeTensors(
    '{"a":{"dtype":"F16","shape":[2],"data_offsets":[0,4]},' +
    '"b":{"dtype":"BF16","shape":[2],"data_offsets":[4,8]}}',
    [$00, $3C, $00, $C0, $80, $3F, $49, $40]);
  try
    Reader := TNNetSafeTensorsReader.Create(Path);
    try
      AssertEquals('tensor count', 2, Reader.Count);
      AssertEquals('a dtype', 'F16', Reader.GetDType('a'));
      AssertEquals('b dtype', 'BF16', Reader.GetDType('b'));
      V := TNNetVolume.Create;
      try
        Reader.LoadTensorFlat('a', V);
        AssertEquals('a size', 2, V.Size);
        AssertEquals('a[0]', 1.0, V.FData[0], 0);
        AssertEquals('a[1]', -2.0, V.FData[1], 0);
        Reader.LoadTensorFlat('b', V);
        AssertEquals('b[0]', 1.0, V.FData[0], 0);
        AssertEquals('b[1]', 3.140625, V.FData[1], 0);
      finally
        V.Free;
      end;
    finally
      Reader.Free;
    end;
  finally
    DeleteFile(Path);
  end;
end;

procedure TTestNeuralPretrained.TestReaderRejectsGarbage;
var
  Path: string;
  Reader: TNNetSafeTensorsReader;
  FS: TFileStream;
  Failed: boolean;
begin
  RandSeed := 424242;
  // (a) File shorter than the 8-byte header length.
  Path := GetTempDir(false) + 'cai_st_trunc.safetensors';
  FS := TFileStream.Create(Path, fmCreate);
  FS.WriteBuffer(Path[1], 4);
  FS.Free;
  Failed := false;
  try
    Reader := TNNetSafeTensorsReader.Create(Path);
    Reader.Free;
  except
    on ESafeTensorsError do Failed := true;
  end;
  DeleteFile(Path);
  AssertTrue('truncated file must be rejected', Failed);

  // (b) Header length exceeding the file size.
  Path := WriteTempSafeTensors('', []);
  // Rewrite the first 8 bytes with a huge length.
  FS := TFileStream.Create(Path, fmOpenReadWrite);
  FS.Position := 0;
  FS.WriteDWord($FFFFFF);
  FS.Free;
  Failed := false;
  try
    Reader := TNNetSafeTensorsReader.Create(Path);
    Reader.Free;
  except
    on ESafeTensorsError do Failed := true;
  end;
  DeleteFile(Path);
  AssertTrue('oversized header length must be rejected', Failed);

  // (c) Header is not JSON.
  Path := WriteTempSafeTensors('this is not json at all!!', []);
  Failed := false;
  try
    Reader := TNNetSafeTensorsReader.Create(Path);
    Reader.Free;
  except
    on ESafeTensorsError do Failed := true;
  end;
  DeleteFile(Path);
  AssertTrue('non-JSON header must be rejected', Failed);

  // (d) data_offsets pointing beyond the data section.
  Path := WriteTempSafeTensors(
    '{"t":{"dtype":"F32","shape":[4],"data_offsets":[0,16]}}',
    [$00, $00, $80, $3F]); // only 4 payload bytes, 16 promised
  Failed := false;
  try
    Reader := TNNetSafeTensorsReader.Create(Path);
    Reader.Free;
  except
    on ESafeTensorsError do Failed := true;
  end;
  DeleteFile(Path);
  AssertTrue('out-of-bounds data_offsets must be rejected', Failed);

  // (e) Element count inconsistent with the byte span.
  Path := WriteTempSafeTensors(
    '{"t":{"dtype":"F32","shape":[2],"data_offsets":[0,4]}}',
    [$00, $00, $80, $3F]);
  Failed := false;
  try
    Reader := TNNetSafeTensorsReader.Create(Path);
    Reader.Free;
  except
    on ESafeTensorsError do Failed := true;
  end;
  DeleteFile(Path);
  AssertTrue('shape/byte-span mismatch must be rejected', Failed);
end;

procedure TTestNeuralPretrained.TestReaderReadsTinyFixture;
var
  Reader: TNNetSafeTensorsReader;
begin
  RandSeed := 424242;
  Reader := TNNetSafeTensorsReader.Create(FixturePath('tiny_gpt2.safetensors'));
  try
    AssertTrue('wte present', Reader.HasTensor('wte.weight'));
    AssertEquals('wte dtype', 'F32', Reader.GetDType('wte.weight'));
    AssertEquals('wte dims', 2, Reader.DimCount('wte.weight'));
    AssertEquals('vocab', 11, Reader.DimSize('wte.weight', 0));
    AssertEquals('d_model', 8, Reader.DimSize('wte.weight', 1));
    AssertEquals('wpe rows', 16, Reader.DimSize('wpe.weight', 0));
    AssertEquals('c_attn shape', '[8, 24]',
      Reader.ShapeAsString('h.0.attn.c_attn.weight'));
    AssertTrue('block 1 present', Reader.HasTensor('h.1.ln_1.weight'));
    AssertTrue('block 2 absent', not Reader.HasTensor('h.2.ln_1.weight'));
  finally
    Reader.Free;
  end;
end;

procedure TTestNeuralPretrained.TestImporterFailsOnMissingTensor;
var
  Path: string;
  NN: TNNet;
  Failed: boolean;
  Payload: array of byte;
  i: integer;
begin
  RandSeed := 424242;
  // A "checkpoint" containing ONLY wte.weight [2, 4]: the importer must
  // fail loudly on the missing wpe.weight, not import partially.
  SetLength(Payload, 2 * 4 * 4);
  for i := 0 to High(Payload) do Payload[i] := 0;
  Path := WriteTempSafeTensors(
    '{"wte.weight":{"dtype":"F32","shape":[2,4],"data_offsets":[0,32]}}',
    Payload);
  Failed := false;
  NN := nil;
  try
    try
      NN := BuildGPT2FromSafeTensors(Path, 4, 2);
    except
      on EPretrainedImportError do Failed := true;
    end;
  finally
    NN.Free;
    DeleteFile(Path);
  end;
  AssertTrue('missing wpe.weight must abort the import', Failed);
end;

procedure TTestNeuralPretrained.TestGPT2ConfigFromFixture;
var
  Reader: TNNetSafeTensorsReader;
  Config: TGPT2Config;
begin
  RandSeed := 424242;
  Reader := TNNetSafeTensorsReader.Create(FixturePath('tiny_gpt2.safetensors'));
  try
    Config := ReadGPT2Config(Reader, 2);
    AssertEquals('n_layer', 2, Config.NLayers);
    AssertEquals('n_head', 2, Config.NHeads);
    AssertEquals('n_embd', 8, Config.NEmbd);
    AssertEquals('n_ctx', 16, Config.NCtx);
    AssertEquals('vocab', 11, Config.VocabSize);
    AssertEquals('prefix', '', Config.Prefix);
  finally
    Reader.Free;
  end;
end;

procedure TTestNeuralPretrained.TestGPT2LogitParity;
var
  NN: TNNet;
  Config: TGPT2Config;
  RefRoot: TJSONData;
  Sequences, SeqArr, LogitsArr, PosArr, RowArr: TJSONArray;
  Input, Output: TNNetVolume;
  RefJson: TStringList;
  SeqCnt, PosCnt, TokCnt: integer;
  Diff, MaxDiff: double;
  SeqLen, Vocab: integer;
begin
  RandSeed := 424242;
  NN := BuildGPT2FromSafeTensorsEx(FixturePath('tiny_gpt2.safetensors'),
    Config, {SeqLen=}0, {NumHeads=}2);
  RefJson := TStringList.Create;
  Input := TNNetVolume.Create;
  Output := TNNetVolume.Create;
  RefRoot := nil;
  try
    AssertEquals('n_layer', 2, Config.NLayers);
    SeqLen := Config.NCtx;
    Vocab := Config.VocabSize;
    RefJson.LoadFromFile(FixturePath('tiny_gpt2_logits.json'));
    RefRoot := GetJSON(RefJson.Text);
    Sequences := TJSONArray(TJSONObject(RefRoot).Find('sequences'));
    LogitsArr := TJSONArray(TJSONObject(RefRoot).Find('logits'));
    AssertTrue('sequences present', Sequences <> nil);
    AssertTrue('logits present', LogitsArr <> nil);
    AssertTrue('at least 3 sequences', Sequences.Count >= 3);
    MaxDiff := 0;
    Input.ReSize(SeqLen, 1, 1);
    for SeqCnt := 0 to Sequences.Count - 1 do
    begin
      SeqArr := TJSONArray(Sequences.Items[SeqCnt]);
      AssertEquals('sequence length', SeqLen, SeqArr.Count);
      for PosCnt := 0 to SeqLen - 1 do
        Input.FData[PosCnt] := SeqArr.Items[PosCnt].AsInteger;
      NN.Compute(Input);
      NN.GetOutput(Output);
      AssertEquals('output size', SeqLen * Vocab, Output.Size);
      PosArr := TJSONArray(LogitsArr.Items[SeqCnt]);
      for PosCnt := 0 to SeqLen - 1 do
      begin
        RowArr := TJSONArray(PosArr.Items[PosCnt]);
        for TokCnt := 0 to Vocab - 1 do
        begin
          Diff := Abs(Output.FData[PosCnt * Vocab + TokCnt] -
            RowArr.Items[TokCnt].AsFloat);
          if Diff > MaxDiff then MaxDiff := Diff;
        end;
      end;
    end;
    // f32 end-to-end vs the float64 Python oracle on f32-rounded weights:
    // observed max |diff| is ~1.4e-6, so the 1e-4 gate has a ~70x margin
    // (the hard acceptance ceiling is 1e-3). NEVER loosen the gate past
    // 1e-3 - if parity breaks, fix the model, don't widen the tolerance.
    AssertTrue('GPT-2 logit parity: max |diff| = ' +
      FloatToStr(MaxDiff) + ' must be < 1e-4', MaxDiff < 1e-4);
  finally
    RefRoot.Free;
    Output.Free;
    Input.Free;
    RefJson.Free;
    NN.Free;
  end;
end;

// MakeInferenceOnly shrinks every neuron's Delta/BackInertia training
// volumes; the forward pass must be bit-for-bit unaffected, whether the
// shrink happens during construction (pInferenceOnly=True) or on an
// already-built net (TNNet.MakeInferenceOnly).
procedure TTestNeuralPretrained.TestMakeInferenceOnlyKeepsOutputs;
var
  NNTrain, NNInfer: TNNet;
  Config: TGPT2Config;
  Input, OutTrain, OutInfer: TNNetVolume;
  i: integer;
begin
  NNTrain := BuildGPT2FromSafeTensorsEx(FixturePath('tiny_gpt2.safetensors'),
    Config, {SeqLen=}0, {NumHeads=}2);
  NNInfer := BuildGPT2FromSafeTensorsEx(FixturePath('tiny_gpt2.safetensors'),
    Config, {SeqLen=}0, {NumHeads=}2, {pInferenceOnly=}true);
  Input := TNNetVolume.Create(Config.NCtx, 1, 1);
  OutTrain := TNNetVolume.Create;
  OutInfer := TNNetVolume.Create;
  try
    for i := 0 to Config.NCtx - 1 do
      Input.FData[i] := (i * 3 + 1) mod Config.VocabSize;
    NNTrain.Compute(Input);
    NNTrain.GetOutput(OutTrain);
    NNInfer.Compute(Input);
    NNInfer.GetOutput(OutInfer);
    AssertEquals('output size', OutTrain.Size, OutInfer.Size);
    for i := 0 to OutTrain.Size - 1 do
      AssertEquals('pInferenceOnly logit ' + IntToStr(i),
        OutTrain.FData[i], OutInfer.FData[i], 0);
    // Shrinking a finished net must not change its outputs either.
    NNTrain.MakeInferenceOnly();
    NNTrain.Compute(Input);
    NNTrain.GetOutput(OutInfer);
    for i := 0 to OutTrain.Size - 1 do
      AssertEquals('post-build MakeInferenceOnly logit ' + IntToStr(i),
        OutTrain.FData[i], OutInfer.FData[i], 0);
    AssertEquals('delta volume shrunk', 1,
      NNTrain.Layers[1].Neurons[0].Delta.Size);
    AssertEquals('inertia volume shrunk', 1,
      NNTrain.Layers[1].Neurons[0].BackInertia.Size);
  finally
    OutInfer.Free;
    OutTrain.Free;
    Input.Free;
    NNInfer.Free;
    NNTrain.Free;
  end;
end;

// Per-token RMSNorm (TNNetTokenRMSNorm) must match a hand-computed HF
// LlamaRMSNorm: per (x,y) token over Depth, no mean subtraction, learnable
// gain, no bias; and survive a save/load round-trip.
procedure TTestNeuralPretrained.TestTokenRMSNormForwardAndSaveLoad;
var
  NN, NN2: TNNet;
  RMSLayer: TNNetLayer;
  Input, Out1, Out2: TNNetVolume;
  i, t, c: integer;
  MeanSqr, Expected: double;
  TokenVals: array[0..3] of double;
begin
  RandSeed := 424242;
  // (SeqLen=3, 1, Depth=4) input; per-token normalization over Depth.
  NN := TNNet.Create();
  NN.AddLayer( TNNetInput.Create(3, 1, 4) );
  RMSLayer := NN.AddLayer( TNNetTokenRMSNorm.Create(1e-5) );
  for c := 0 to 3 do
    RMSLayer.Neurons[0].Weights.FData[c] := 0.5 + 0.25 * c; // gain
  RMSLayer.FlushWeightCache();
  Input := TNNetVolume.Create(3, 1, 4);
  Out1 := TNNetVolume.Create;
  Out2 := TNNetVolume.Create;
  NN2 := TNNet.Create();
  try
    for i := 0 to Input.Size - 1 do
      Input.FData[i] := Sin(i * 1.7) * 2 + 0.3 * i;
    NN.Compute(Input);
    NN.GetOutput(Out1);
    // Hand-computed per-token RMSNorm for each of the 3 tokens.
    for t := 0 to 2 do
    begin
      MeanSqr := 0;
      for c := 0 to 3 do
      begin
        TokenVals[c] := Input.FData[t * 4 + c];
        MeanSqr := MeanSqr + Sqr(TokenVals[c]);
      end;
      MeanSqr := MeanSqr / 4;
      for c := 0 to 3 do
      begin
        Expected := (0.5 + 0.25 * c) *
          (TokenVals[c] / Sqrt(MeanSqr + 1e-5));
        AssertEquals('per-token RMSNorm value t=' + IntToStr(t) + ' c=' +
          IntToStr(c), Expected, Out1.FData[t * 4 + c], 1e-5);
      end;
    end;
    // Save/load round-trip must preserve structure, eps and gains.
    NN2.LoadFromString(NN.SaveToString());
    AssertTrue('reloaded layer class',
      NN2.Layers[1] is TNNetTokenRMSNorm);
    NN2.Compute(Input);
    NN2.GetOutput(Out2);
    for i := 0 to Out1.Size - 1 do
      AssertEquals('save/load forward equality at ' + IntToStr(i),
        Out1.FData[i], Out2.FData[i], 1e-7);
  finally
    NN2.Free;
    Out2.Free;
    Out1.Free;
    Input.Free;
    NN.Free;
  end;
end;

// The Llama importer compensates for HF's rotate_half pair layout
// (pairs (i, i+hd/2)) by permuting q/k projection rows into
// TNNetRotaryEmbedding's interleaved (2k, 2k+1) layout:
//   CAI channel 2k <- HF row k;  CAI channel 2k+1 <- HF row k+hd/2.
// This test feeds a PERMUTED head vector through TNNetRotaryEmbedding and
// asserts the result equals the hand-computed HF rotate_half rotation of
// the ORIGINAL vector, re-read through the same permutation.
procedure TTestNeuralPretrained.TestRotaryHalfPermutationMatchesHFRotateHalf;
const
  SeqLen = 5;
  HeadDim = 6; // half = 3
  RopeBase = 10000.0;
var
  NN: TNNet;
  Input, Output: TNNetVolume;
  HFVec, HFRot: array[0..HeadDim - 1] of double;
  Freq, CosV, SinV: double;
  Pos, i, Half: integer;
begin
  RandSeed := 424242;
  Half := HeadDim div 2;
  NN := TNNet.Create();
  NN.AddLayer( TNNetInput.Create(SeqLen, 1, HeadDim) );
  NN.AddLayer( TNNetRotaryEmbedding.Create(RopeBase) );
  Input := TNNetVolume.Create(SeqLen, 1, HeadDim);
  Output := TNNetVolume.Create;
  try
    for i := 0 to Input.Size - 1 do
      Input.FData[i] := Cos(i * 0.9) + 0.1 * i;
    NN.Compute(Input);
    NN.GetOutput(Output);
    for Pos := 0 to SeqLen - 1 do
    begin
      // Re-read the CAI channels back into the HF half-split layout:
      // HF row k = CAI channel 2k; HF row k+half = CAI channel 2k+1.
      for i := 0 to Half - 1 do
      begin
        HFVec[i] := Input.FData[Pos * HeadDim + 2 * i];
        HFVec[i + Half] := Input.FData[Pos * HeadDim + 2 * i + 1];
      end;
      // Hand-computed HF rotate_half rotation:
      //   y[i]      = x[i]*cos - x[i+half]*sin
      //   y[i+half] = x[i+half]*cos + x[i]*sin,  angle = pos * base^(-2i/hd)
      for i := 0 to Half - 1 do
      begin
        Freq := Exp(-2.0 * i / HeadDim * Ln(RopeBase));
        CosV := Cos(Pos * Freq);
        SinV := Sin(Pos * Freq);
        HFRot[i] := HFVec[i] * CosV - HFVec[i + Half] * SinV;
        HFRot[i + Half] := HFVec[i + Half] * CosV + HFVec[i] * SinV;
      end;
      for i := 0 to Half - 1 do
      begin
        AssertEquals('rotate_half pos=' + IntToStr(Pos) + ' k=' + IntToStr(i),
          HFRot[i], Output.FData[Pos * HeadDim + 2 * i], 1e-5);
        AssertEquals('rotate_half pos=' + IntToStr(Pos) + ' k+half=' +
          IntToStr(i), HFRot[i + Half],
          Output.FData[Pos * HeadDim + 2 * i + 1], 1e-5);
      end;
    end;
  finally
    Output.Free;
    Input.Free;
    NN.Free;
  end;
end;

// TNNetSwiGLU computes FIRSTHALF * Swish(SECONDHALF); the Llama importer
// therefore loads up_proj into the first depth half and gate_proj into the
// second. This test checks the layer against hand-computed
// silu(gate) * up on a (SeqLen=2, 1, 2*I) tensor packed [up | gate].
procedure TTestNeuralPretrained.TestSwiGLUMatchesLlamaMLPGating;
const
  Inter = 3;
  SeqLen = 2;
var
  NN: TNNet;
  Input, Output: TNNetVolume;
  UpV, GateV, Expected: double;
  t, i: integer;
begin
  RandSeed := 424242;
  NN := TNNet.Create();
  NN.AddLayer( TNNetInput.Create(SeqLen, 1, 2 * Inter) );
  NN.AddLayer( TNNetSwiGLU.Create() );
  Input := TNNetVolume.Create(SeqLen, 1, 2 * Inter);
  Output := TNNetVolume.Create;
  try
    for i := 0 to Input.Size - 1 do
      Input.FData[i] := Sin(i * 1.3) * 1.5 - 0.2;
    NN.Compute(Input);
    NN.GetOutput(Output);
    AssertEquals('SwiGLU output size', SeqLen * Inter, Output.Size);
    for t := 0 to SeqLen - 1 do
      for i := 0 to Inter - 1 do
      begin
        UpV := Input.FData[t * 2 * Inter + i];              // first half
        GateV := Input.FData[t * 2 * Inter + Inter + i];    // second half
        Expected := UpV * (GateV / (1 + Exp(-GateV)));      // up * silu(gate)
        AssertEquals('SwiGLU t=' + IntToStr(t) + ' i=' + IntToStr(i),
          Expected, Output.FData[t * Inter + i], 1e-5);
      end;
  finally
    Output.Free;
    Input.Free;
    NN.Free;
  end;
end;

procedure TTestNeuralPretrained.TestLlamaConfigFromJSONFile;
var
  Config: TLlamaConfig;
begin
  RandSeed := 424242;
  Config := ReadLlamaConfigFromJSONFile(FixturePath('tiny_llama_config.json'));
  AssertEquals('hidden_size', 8, Config.HiddenSize);
  AssertEquals('intermediate_size', 12, Config.IntermediateSize);
  AssertEquals('num_hidden_layers', 2, Config.NumLayers);
  AssertEquals('num_attention_heads', 2, Config.NumHeads);
  AssertEquals('num_key_value_heads', 1, Config.NumKVHeads);
  AssertEquals('vocab_size', 11, Config.VocabSize);
  AssertEquals('max_position_embeddings', 16, Config.MaxPositions);
  AssertEquals('rms_norm_eps', 1e-5, Config.RmsNormEps, 1e-9);
  AssertEquals('rope_theta', 10000.0, Config.RopeTheta, 1e-3);
  AssertFalse('tie_word_embeddings', Config.TieWordEmbeddings);
end;

procedure TTestNeuralPretrained.TestLlamaImporterFailsOnMissingTensor;
var
  Path: string;
  NN: TNNet;
  Config: TLlamaConfig;
  Failed: boolean;
  Payload: array of byte;
  i: integer;
begin
  RandSeed := 424242;
  // A "checkpoint" containing ONLY model.embed_tokens.weight [4, 4]: the
  // importer must fail loudly on the first missing block tensor, not
  // import partially.
  SetLength(Payload, 4 * 4 * 4);
  for i := 0 to High(Payload) do Payload[i] := 0;
  Path := WriteTempSafeTensors(
    '{"model.embed_tokens.weight":{"dtype":"F32","shape":[4,4],' +
    '"data_offsets":[0,64]}}', Payload);
  Config.HiddenSize := 4;
  Config.IntermediateSize := 6;
  Config.NumLayers := 1;
  Config.NumHeads := 2;
  Config.NumKVHeads := 1;
  Config.VocabSize := 4;
  Config.MaxPositions := 8;
  Config.RmsNormEps := 1e-6;
  Config.RopeTheta := 10000;
  Config.TieWordEmbeddings := true;
  Config.ModelType := 'llama';
  Config.SlidingWindow := 0;
  Config.QKVBias := false;
  Config.Prefix := '';
  Failed := false;
  NN := nil;
  try
    try
      NN := BuildLlamaFromSafeTensorsWithConfig(Path, Config);
    except
      on EPretrainedImportError do Failed := true;
    end;
  finally
    NN.Free;
    DeleteFile(Path);
  end;
  AssertTrue('missing block tensors must abort the import', Failed);
end;

// The flagship Llama test: imports the committed tiny random Llama-shaped
// checkpoint and asserts logit parity with the independent pure-Python
// oracle (tools/llama_tiny_fixture.py, verified to match HF transformers'
// LlamaForCausalLM to ~9e-7). Covers the rotate_half row permutation, GQA
// head sharing, per-token RMSNorm, SwiGLU mapping and the untied LM head.
procedure TTestNeuralPretrained.TestLlamaLogitParity;
var
  NN: TNNet;
  Config: TLlamaConfig;
  RefRoot: TJSONData;
  Sequences, SeqArr, LogitsArr, PosArr, RowArr: TJSONArray;
  Input, Output: TNNetVolume;
  RefJson: TStringList;
  SeqCnt, PosCnt, TokCnt: integer;
  Diff, MaxDiff: double;
  SeqLen, Vocab: integer;
begin
  RandSeed := 424242;
  NN := BuildLlamaFromSafeTensorsEx(FixturePath('tiny_llama.safetensors'),
    Config, {SeqLen=}0, {pInferenceOnly=}false,
    FixturePath('tiny_llama_config.json'));
  RefJson := TStringList.Create;
  Input := TNNetVolume.Create;
  Output := TNNetVolume.Create;
  RefRoot := nil;
  try
    AssertEquals('layers', 2, Config.NumLayers);
    AssertEquals('prefix', 'model.', Config.Prefix);
    SeqLen := Config.MaxPositions;
    Vocab := Config.VocabSize;
    RefJson.LoadFromFile(FixturePath('tiny_llama_logits.json'));
    RefRoot := GetJSON(RefJson.Text);
    Sequences := TJSONArray(TJSONObject(RefRoot).Find('sequences'));
    LogitsArr := TJSONArray(TJSONObject(RefRoot).Find('logits'));
    AssertTrue('sequences present', Sequences <> nil);
    AssertTrue('logits present', LogitsArr <> nil);
    AssertTrue('at least 3 sequences', Sequences.Count >= 3);
    MaxDiff := 0;
    Input.ReSize(SeqLen, 1, 1);
    for SeqCnt := 0 to Sequences.Count - 1 do
    begin
      SeqArr := TJSONArray(Sequences.Items[SeqCnt]);
      AssertEquals('sequence length', SeqLen, SeqArr.Count);
      for PosCnt := 0 to SeqLen - 1 do
        Input.FData[PosCnt] := SeqArr.Items[PosCnt].AsInteger;
      NN.Compute(Input);
      NN.GetOutput(Output);
      AssertEquals('output size', SeqLen * Vocab, Output.Size);
      PosArr := TJSONArray(LogitsArr.Items[SeqCnt]);
      for PosCnt := 0 to SeqLen - 1 do
      begin
        RowArr := TJSONArray(PosArr.Items[PosCnt]);
        for TokCnt := 0 to Vocab - 1 do
        begin
          Diff := Abs(Output.FData[PosCnt * Vocab + TokCnt] -
            RowArr.Items[TokCnt].AsFloat);
          if Diff > MaxDiff then MaxDiff := Diff;
        end;
      end;
    end;
    // f32 end-to-end vs the float64 Python oracle on f32-rounded weights.
    // NEVER loosen the gate past 1e-3 - if parity breaks, fix the model,
    // don't widen the tolerance.
    AssertTrue('Llama logit parity: max |diff| = ' +
      FloatToStr(MaxDiff) + ' must be < 1e-4', MaxDiff < 1e-4);
  finally
    RefRoot.Free;
    Output.Free;
    Input.Free;
    RefJson.Free;
    NN.Free;
  end;
end;

// Reader-level sharded-checkpoint coverage: tiny_llama.safetensors.index.json
// (generated by tools/shard_tiny_llama_fixture.py) splits the tiny Llama
// fixture into 2 shards. The sharded reader must expose exactly the same
// tensor set, dtypes, shapes and bytes as the single-file reader.
procedure TTestNeuralPretrained.TestShardedReaderMatchesSingleFile;
var
  Single1, Sharded: TNNetSafeTensorsReader;
  V1, V2: TNNetVolume;
  i, j: integer;
  TName: string;
begin
  RandSeed := 424242;
  Single1 := TNNetSafeTensorsReader.Create(
    FixturePath('tiny_llama.safetensors'));
  Sharded := TNNetSafeTensorsReader.Create(
    FixturePath('tiny_llama.safetensors.index.json'));
  V1 := TNNetVolume.Create;
  V2 := TNNetVolume.Create;
  try
    AssertEquals('single-file shard count', 1, Single1.ShardCount);
    AssertEquals('sharded shard count', 2, Sharded.ShardCount);
    AssertEquals('tensor count', Single1.Count, Sharded.Count);
    for i := 0 to Single1.Count - 1 do
    begin
      TName := Single1.TensorName(i);
      AssertTrue('sharded has ' + TName, Sharded.HasTensor(TName));
      AssertEquals('dtype of ' + TName, Single1.GetDType(TName),
        Sharded.GetDType(TName));
      AssertEquals('shape of ' + TName, Single1.ShapeAsString(TName),
        Sharded.ShapeAsString(TName));
      Single1.LoadTensorFlat(TName, V1);
      Sharded.LoadTensorFlat(TName, V2);
      AssertEquals('size of ' + TName, V1.Size, V2.Size);
      for j := 0 to V1.Size - 1 do
        if V1.FData[j] <> V2.FData[j] then
          Fail('tensor ' + TName + ' differs at element ' + IntToStr(j));
    end;
  finally
    V2.Free;
    V1.Free;
    Sharded.Free;
    Single1.Free;
  end;
end;

// End-to-end sharded import: BuildLlamaFromSafeTensorsEx pointed at the
// 2-shard index.json (NO importer changes - the reader handles sharding
// transparently) must produce logits BIT-IDENTICAL to the single-file load,
// and both must keep parity with the pinned Python oracle logits.
procedure TTestNeuralPretrained.TestShardedLlamaLogitsBitIdentical;
var
  NNSingle, NNSharded: TNNet;
  ConfigSingle, ConfigSharded: TLlamaConfig;
  Input, OutSingle, OutSharded: TNNetVolume;
  i: integer;
begin
  RandSeed := 424242;
  NNSingle := BuildLlamaFromSafeTensorsEx(
    FixturePath('tiny_llama.safetensors'), ConfigSingle, {SeqLen=}0,
    {pInferenceOnly=}false, FixturePath('tiny_llama_config.json'));
  NNSharded := BuildLlamaFromSafeTensorsEx(
    FixturePath('tiny_llama.safetensors.index.json'), ConfigSharded,
    {SeqLen=}0, {pInferenceOnly=}false,
    FixturePath('tiny_llama_config.json'));
  Input := TNNetVolume.Create(ConfigSingle.MaxPositions, 1, 1);
  OutSingle := TNNetVolume.Create;
  OutSharded := TNNetVolume.Create;
  try
    AssertEquals('layers', ConfigSingle.NumLayers, ConfigSharded.NumLayers);
    AssertEquals('prefix', 'model.', ConfigSharded.Prefix);
    for i := 0 to ConfigSingle.MaxPositions - 1 do
      Input.FData[i] := (i * 5 + 2) mod ConfigSingle.VocabSize;
    NNSingle.Compute(Input);
    NNSingle.GetOutput(OutSingle);
    NNSharded.Compute(Input);
    NNSharded.GetOutput(OutSharded);
    AssertEquals('output size', OutSingle.Size, OutSharded.Size);
    for i := 0 to OutSingle.Size - 1 do
      AssertEquals('sharded vs single-file logit ' + IntToStr(i),
        OutSingle.FData[i], OutSharded.FData[i], 0); // BIT-identical
    // The sharded import must also keep oracle parity on its own.
    AssertLogitParityWithFixture(NNSharded,
      FixturePath('tiny_llama_logits.json'), ConfigSharded.MaxPositions,
      ConfigSharded.VocabSize);
  finally
    OutSharded.Free;
    OutSingle.Free;
    Input.Free;
    NNSharded.Free;
    NNSingle.Free;
  end;
end;

// Verifies the distilbert/distilgpt2 import target on REAL pretrained
// weights: tests/fixtures/tiny_distilgpt2.safetensors is a dimension-sliced
// sub-slab of the genuine distilgpt2 checkpoint (2 of 6 layers, 2 heads x 4
// dims, d_model 8, vocab 12, "transformer." tensor prefix - see
// examples/GPT2Import/make_pico_gpt2_fixture.py) and the reference logits
// come from HF transformers' GPT2LMHeadModel in float64 on the same slice.
// The full distilgpt2 loads with BuildGPT2FromSafeTensors unchanged
// (2026-06: 2-layer/8192-vocab real-weight slice max |logit diff| 4.2e-5
// vs transformers; the n_head = n_embd/64 rule holds - 768 -> 12 heads).
procedure TTestNeuralPretrained.TestDistilGPT2LogitParity;
var
  NN: TNNet;
  Config: TGPT2Config;
begin
  RandSeed := 424242;
  NN := BuildGPT2FromSafeTensorsEx(
    FixturePath('tiny_distilgpt2.safetensors'), Config, {SeqLen=}0,
    {NumHeads=}2);
  try
    AssertEquals('n_layer', 2, Config.NLayers);
    AssertEquals('n_embd', 8, Config.NEmbd);
    AssertEquals('n_ctx', 16, Config.NCtx);
    AssertEquals('vocab', 12, Config.VocabSize);
    AssertEquals('prefix', 'transformer.', Config.Prefix);
    AssertLogitParityWithFixture(NN,
      FixturePath('tiny_distilgpt2_logits.json'), Config.NCtx,
      Config.VocabSize);
  finally
    NN.Free;
  end;
end;

// Verifies the HuggingFaceTB/SmolLM2-135M import target on REAL pretrained
// weights: tests/fixtures/tiny_smollm2.safetensors is a dimension-sliced
// sub-slab of the genuine SmolLM2-135M checkpoint (2 of 30 layers, 2 query
// heads sharing 1 kv head x 4 dims, hidden 8, vocab 12 - see
// examples/LlamaImport/make_pico_llama_fixture.py) and the reference logits
// come from HF transformers' LlamaForCausalLM in float64 on the same slice.
// Distinctive coverage vs TestLlamaLogitParity: TIED embeddings (no
// lm_head tensor in the checkpoint), rope_theta=100000 and a BF16-dtype
// fixture (end-to-end DecodeBF16). The full SmolLM2-135M loads with
// BuildLlamaFromSafeTensors unchanged (2026-06: 2-layer/4096-vocab
// real-weight slice max |logit diff| 6.5e-5 vs transformers).
procedure TTestNeuralPretrained.TestSmolLM2LogitParity;
var
  NN: TNNet;
  Config: TLlamaConfig;
begin
  RandSeed := 424242;
  NN := BuildLlamaFromSafeTensorsEx(FixturePath('tiny_smollm2.safetensors'),
    Config, {SeqLen=}0, {pInferenceOnly=}false,
    FixturePath('tiny_smollm2_config.json'));
  try
    AssertEquals('layers', 2, Config.NumLayers);
    AssertEquals('heads', 2, Config.NumHeads);
    AssertEquals('kv_heads', 1, Config.NumKVHeads);
    AssertEquals('vocab', 12, Config.VocabSize);
    AssertEquals('rope_theta', 100000.0, Config.RopeTheta, 1e-3);
    AssertTrue('tie_word_embeddings', Config.TieWordEmbeddings);
    AssertEquals('prefix', 'model.', Config.Prefix);
    AssertLogitParityWithFixture(NN,
      FixturePath('tiny_smollm2_logits.json'), Config.MaxPositions,
      Config.VocabSize);
  finally
    NN.Free;
  end;
end;

// Verifies the Mistral import target: tests/fixtures/tiny_mistral.* is a
// pico randomly-initialized HF MistralForCausalLM (2 layers, 2 query heads
// sharing 1 kv head x 4 dims, hidden 8, vocab 11, untied lm_head) with
// sliding_window=4 SMALLER than the 16-token test sequences, so the
// sliding-window mask is genuinely exercised (the generator
// tools/mistral_qwen2_tiny_fixture.py asserts the windowed logits differ
// from full attention by ~1e-2 on the same weights). Reference logits come
// from HF transformers in float64.
procedure TTestNeuralPretrained.TestMistralLogitParity;
var
  NN: TNNet;
  Config: TLlamaConfig;
begin
  RandSeed := 424242;
  NN := BuildMistralFromSafeTensorsEx(FixturePath('tiny_mistral.safetensors'),
    Config, {SeqLen=}0, {pInferenceOnly=}false,
    FixturePath('tiny_mistral_config.json'));
  try
    AssertEquals('model_type', 'mistral', Config.ModelType);
    AssertEquals('layers', 2, Config.NumLayers);
    AssertEquals('heads', 2, Config.NumHeads);
    AssertEquals('kv_heads', 1, Config.NumKVHeads);
    AssertEquals('vocab', 11, Config.VocabSize);
    AssertEquals('sliding_window', 4, Config.SlidingWindow);
    AssertFalse('qkv_bias', Config.QKVBias);
    AssertEquals('prefix', 'model.', Config.Prefix);
    AssertLogitParityWithFixture(NN,
      FixturePath('tiny_mistral_logits.json'), Config.MaxPositions,
      Config.VocabSize);
  finally
    NN.Free;
  end;
end;

// Verifies the Qwen2 import target: tests/fixtures/tiny_qwen2.* is a pico
// randomly-initialized HF Qwen2ForCausalLM (2 layers, 2 query heads sharing
// 1 kv head x 4 dims, hidden 8, vocab 12, untied lm_head) whose q/k/v
// projection biases were re-randomized to NONZERO values (HF zero-inits
// them; the generator asserts zeroing the biases changes the logits by
// ~0.15), so the bias-loading path - including the rotate_half permutation
// of the q/k biases - is genuinely exercised. Reference logits come from
// HF transformers in float64.
procedure TTestNeuralPretrained.TestQwen2LogitParity;
var
  NN: TNNet;
  Config: TLlamaConfig;
begin
  RandSeed := 424242;
  NN := BuildQwen2FromSafeTensorsEx(FixturePath('tiny_qwen2.safetensors'),
    Config, {SeqLen=}0, {pInferenceOnly=}false,
    FixturePath('tiny_qwen2_config.json'));
  try
    AssertEquals('model_type', 'qwen2', Config.ModelType);
    AssertEquals('layers', 2, Config.NumLayers);
    AssertEquals('heads', 2, Config.NumHeads);
    AssertEquals('kv_heads', 1, Config.NumKVHeads);
    AssertEquals('vocab', 12, Config.VocabSize);
    AssertEquals('sliding_window', 0, Config.SlidingWindow);
    AssertTrue('qkv_bias', Config.QKVBias);
    AssertEquals('prefix', 'model.', Config.Prefix);
    AssertLogitParityWithFixture(NN,
      FixturePath('tiny_qwen2_logits.json'), Config.MaxPositions,
      Config.VocabSize);
  finally
    NN.Free;
  end;
end;

// Verifies the Qwen3 import target: tests/fixtures/tiny_qwen3.* is a pico
// randomly-initialized HF Qwen3ForCausalLM (2 layers, 2 query heads sharing
// 1 kv head, hidden 8, vocab 13, tied lm_head) exercising both Qwen3 deltas
// on the Qwen2 path: a DECOUPLED head_dim=6 (num_heads*head_dim = 12 !=
// hidden_size = 8, the Qwen3-0.6B shape quirk) and per-head q/k RMSNorm
// applied BEFORE RoPE whose shared [head_dim] gains were re-randomized to
// NON-ONE values (HF ones-inits them; the generator
// tools/qwen3_tiny_fixture.py asserts resetting them to ones changes the
// logits by ~1e-2). No q/k/v biases (Qwen3 dropped them). Reference logits
// come from HF transformers in float64.
procedure TTestNeuralPretrained.TestQwen3LogitParity;
var
  NN: TNNet;
  Config: TLlamaConfig;
begin
  RandSeed := 424242;
  NN := BuildQwen3FromSafeTensorsEx(FixturePath('tiny_qwen3.safetensors'),
    Config, {SeqLen=}0, {pInferenceOnly=}false,
    FixturePath('tiny_qwen3_config.json'));
  try
    AssertEquals('model_type', 'qwen3', Config.ModelType);
    AssertEquals('layers', 2, Config.NumLayers);
    AssertEquals('heads', 2, Config.NumHeads);
    AssertEquals('kv_heads', 1, Config.NumKVHeads);
    AssertEquals('vocab', 13, Config.VocabSize);
    AssertEquals('head_dim', 6, Config.HeadDim);
    AssertFalse('qkv_bias', Config.QKVBias);
    AssertTrue('qk_norm', Config.QKNorm);
    AssertTrue('tied', Config.TieWordEmbeddings);
    AssertEquals('prefix', 'model.', Config.Prefix);
    AssertLogitParityWithFixture(NN,
      FixturePath('tiny_qwen3_logits.json'), Config.MaxPositions,
      Config.VocabSize);
  finally
    NN.Free;
  end;
end;

procedure TTestNeuralPretrained.TestGPTNeoConfigFromJSONFile;
var
  Config: TGPTNeoConfig;
begin
  RandSeed := 424242;
  Config := ReadGPTNeoConfigFromJSONFile(
    FixturePath('tiny_gptneo_config.json'));
  AssertEquals('hidden_size', 8, Config.HiddenSize);
  // intermediate_size is null in the config: the 4*hidden default applies.
  AssertEquals('intermediate_size', 32, Config.IntermediateSize);
  AssertEquals('num_layers', 2, Config.NumLayers);
  AssertEquals('num_heads', 2, Config.NumHeads);
  AssertEquals('vocab_size', 11, Config.VocabSize);
  AssertEquals('max_position_embeddings', 16, Config.MaxPositions);
  AssertEquals('window_size', 4, Config.WindowSize);
  AssertEquals('layer_norm_epsilon', 1e-5, Config.LayerNormEps, 1e-9);
  AssertTrue('tie_word_embeddings', Config.TieWordEmbeddings);
  AssertEquals('attention pattern length', 2, Length(Config.LayerIsLocal));
  AssertFalse('layer 0 is global', Config.LayerIsLocal[0]);
  AssertTrue('layer 1 is local', Config.LayerIsLocal[1]);
end;

// Verifies the GPT-Neo import target: tests/fixtures/tiny_gptneo.* is a pico
// randomly-initialized HF GPTNeoForCausalLM (2 layers, 2 heads x 4 dims,
// hidden 8, vocab 11, tied lm_head) covering all three GPT-Neo quirks:
// ALTERNATING ["global", "local"] attention with window_size=4 SMALLER than
// the 16-token test sequences (the generator tools/gptneo_tiny_fixture.py
// asserts the band changes the logits by ~1.4e-2 vs a sequence-wide window),
// UNSCALED attention (the generator asserts that pretending GPT-Neo scaled
// by 1/sqrt(d_head) changes the logits by ~8e-3; the importer folds
// sqrt(d_head) into W_q), and separate bias-free nn.Linear q/k/v ([out, in]
// orientation, NOT GPT-2's transposed Conv1D; out_proj and the MLP carry
// biases). Reference logits come from HF transformers in float64.
procedure TTestNeuralPretrained.TestGPTNeoLogitParity;
var
  NN: TNNet;
  Config: TGPTNeoConfig;
begin
  RandSeed := 424242;
  NN := BuildGPTNeoFromSafeTensorsEx(FixturePath('tiny_gptneo.safetensors'),
    Config, {SeqLen=}0, {pInferenceOnly=}false,
    FixturePath('tiny_gptneo_config.json'));
  try
    AssertEquals('layers', 2, Config.NumLayers);
    AssertEquals('heads', 2, Config.NumHeads);
    AssertEquals('vocab', 11, Config.VocabSize);
    AssertEquals('window_size', 4, Config.WindowSize);
    AssertTrue('tie_word_embeddings', Config.TieWordEmbeddings);
    AssertEquals('prefix', 'transformer.', Config.Prefix);
    AssertLogitParityWithFixture(NN,
      FixturePath('tiny_gptneo_logits.json'), Config.MaxPositions,
      Config.VocabSize);
  finally
    NN.Free;
  end;
end;

procedure TTestNeuralPretrained.TestGPTNeoXConfigFromJSONFile;
var
  Config: TGPTNeoXConfig;
begin
  RandSeed := 424242;
  Config := ReadGPTNeoXConfigFromJSONFile(
    FixturePath('tiny_gptneox_config.json'));
  AssertEquals('hidden_size', 16, Config.HiddenSize);
  // 24, deliberately NOT 4*hidden in the fixture.
  AssertEquals('intermediate_size', 24, Config.IntermediateSize);
  AssertEquals('num_hidden_layers', 2, Config.NumLayers);
  AssertEquals('num_attention_heads', 2, Config.NumHeads);
  AssertEquals('vocab_size', 11, Config.VocabSize);
  AssertEquals('max_position_embeddings', 16, Config.MaxPositions);
  AssertEquals('layer_norm_eps', 1e-5, Config.LayerNormEps, 1e-9);
  AssertEquals('rotary_pct', 0.25, Config.RotaryPct, 1e-9);
  AssertEquals('rotary_emb_base', 10000.0, Config.RopeTheta, 1e-6);
  AssertTrue('use_parallel_residual', Config.UseParallelResidual);
  AssertFalse('tie_word_embeddings (Pythia untied)',
    Config.TieWordEmbeddings);
  AssertFalse('hidden_act gelu = exact erf form', Config.HiddenActTanh);
  // The sequential-variant config flips ONLY use_parallel_residual.
  Config := ReadGPTNeoXConfigFromJSONFile(
    FixturePath('tiny_gptneox_seq_config.json'));
  AssertFalse('seq variant use_parallel_residual',
    Config.UseParallelResidual);
end;

// Verifies the GPT-NeoX (Pythia-architecture) import:
// tests/fixtures/tiny_gptneox.* is a pico randomly-initialized HF
// GPTNeoXForCausalLM (2 layers, 2 heads x 8 dims, hidden 16,
// intermediate 24 deliberately != 4*hidden, vocab 11) covering the
// GPT-NeoX quirks: PARALLEL two-LayerNorm residual
// (x + Attn(LN1(x)) + MLP(LN2(x))), PARTIAL rotary (rotary_pct=0.25 ->
// RoPE on only the first 2 of 8 head dims; the generator
// tools/gptneox_tiny_fixture.py asserts rotary_pct=1.0 would change the
// logits by ~0.12), the fused per-head-interleaved query_key_value
// projection, the exact erf "gelu" and the UNTIED embed_in/embed_out
// pair. Reference logits come from HF transformers in float64.
procedure TTestNeuralPretrained.TestGPTNeoXLogitParity;
var
  NN: TNNet;
  Config: TGPTNeoXConfig;
begin
  RandSeed := 424242;
  NN := BuildGPTNeoXFromSafeTensorsEx(
    FixturePath('tiny_gptneox.safetensors'),
    Config, {SeqLen=}0, {pInferenceOnly=}false,
    FixturePath('tiny_gptneox_config.json'));
  try
    AssertEquals('layers', 2, Config.NumLayers);
    AssertEquals('heads', 2, Config.NumHeads);
    AssertEquals('vocab', 11, Config.VocabSize);
    AssertTrue('use_parallel_residual', Config.UseParallelResidual);
    AssertFalse('untied', Config.TieWordEmbeddings);
    AssertEquals('prefix', 'gpt_neox.', Config.Prefix);
    AssertLogitParityWithFixture(NN,
      FixturePath('tiny_gptneox_logits.json'), Config.MaxPositions,
      Config.VocabSize);
  finally
    NN.Free;
  end;
end;

// use_parallel_residual=false (the sequential pre-LN fallback): the SAME
// tiny_gptneox.safetensors weights under the flipped config must match the
// HF sequential-forward logits (the generator asserts the two residual
// wirings differ by ~2.5e-2 on these weights, so this parity run genuinely
// pins the sequential path).
procedure TTestNeuralPretrained.TestGPTNeoXSequentialLogitParity;
var
  NN: TNNet;
  Config: TGPTNeoXConfig;
begin
  RandSeed := 424242;
  NN := BuildGPTNeoXFromSafeTensorsEx(
    FixturePath('tiny_gptneox.safetensors'),
    Config, {SeqLen=}0, {pInferenceOnly=}false,
    FixturePath('tiny_gptneox_seq_config.json'));
  try
    AssertFalse('sequential residual', Config.UseParallelResidual);
    AssertLogitParityWithFixture(NN,
      FixturePath('tiny_gptneox_seq_logits.json'), Config.MaxPositions,
      Config.VocabSize);
  finally
    NN.Free;
  end;
end;

procedure TTestNeuralPretrained.TestGPTJConfigFromJSONFile;
var
  Config: TGPTJConfig;
begin
  RandSeed := 424242;
  Config := ReadGPTJConfigFromJSONFile(
    FixturePath('tiny_gptj_config.json'));
  AssertEquals('n_embd', 16, Config.HiddenSize);
  // 24, deliberately NOT 4*hidden in the fixture.
  AssertEquals('n_inner', 24, Config.IntermediateSize);
  AssertEquals('n_layer', 2, Config.NumLayers);
  AssertEquals('n_head', 2, Config.NumHeads);
  AssertEquals('vocab_size', 11, Config.VocabSize);
  AssertEquals('n_positions', 16, Config.MaxPositions);
  AssertEquals('layer_norm_epsilon', 1e-5, Config.LayerNormEps, 1e-9);
  AssertEquals('rotary_dim', 4, Config.RotaryDim);
  AssertEquals('rope_theta (GPT-J hardcodes 10000)', 10000.0,
    Config.RopeTheta, 1e-6);
  AssertFalse('tie_word_embeddings (GPT-J untied)',
    Config.TieWordEmbeddings);
  AssertTrue('activation_function gelu_new = tanh form',
    Config.HiddenActTanh);
end;

// Verifies the GPT-J import: tests/fixtures/tiny_gptj.* is a pico
// randomly-initialized HF GPTJForCausalLM (2 layers, 2 heads x 8 dims,
// hidden 16, n_inner 24 deliberately != 4*hidden, vocab 11) covering the
// GPT-J quirks: SHARED-LN parallel residual (ONE ln_1 feeds both branches,
// x + Attn(LN(x)) + MLP(LN(x))), PARTIAL rotary with the INTERLEAVED
// GPT-J pair layout (rotary_dim=4 of head_dim 8, rows loaded STRAIGHT -
// no rotate_half permutation; the generator tools/gptj_tiny_fixture.py
// asserts rotary_dim 2 and 8 would both change the logits), SEPARATE
// bias-free q/k/v + out_proj projections, gelu_new and the UNTIED
// lm_head WITH bias. Reference logits come from HF transformers in
// float64.
procedure TTestNeuralPretrained.TestGPTJLogitParity;
var
  NN: TNNet;
  Config: TGPTJConfig;
begin
  RandSeed := 424242;
  NN := BuildGPTJFromSafeTensorsEx(
    FixturePath('tiny_gptj.safetensors'),
    Config, {SeqLen=}0, {pInferenceOnly=}false,
    FixturePath('tiny_gptj_config.json'));
  try
    AssertEquals('layers', 2, Config.NumLayers);
    AssertEquals('heads', 2, Config.NumHeads);
    AssertEquals('vocab', 11, Config.VocabSize);
    AssertEquals('rotary_dim', 4, Config.RotaryDim);
    AssertFalse('untied', Config.TieWordEmbeddings);
    AssertEquals('prefix', 'transformer.', Config.Prefix);
    AssertLogitParityWithFixture(NN,
      FixturePath('tiny_gptj_logits.json'), Config.MaxPositions,
      Config.VocabSize);
  finally
    NN.Free;
  end;
end;

procedure TTestNeuralPretrained.TestPhiConfigFromJSONFile;
var
  Config: TPhiConfig;
begin
  RandSeed := 424242;
  Config := ReadPhiConfigFromJSONFile(
    FixturePath('tiny_phi_config.json'));
  AssertEquals('hidden_size', 16, Config.HiddenSize);
  // 24, deliberately NOT 4*hidden in the fixture.
  AssertEquals('intermediate_size', 24, Config.IntermediateSize);
  AssertEquals('num_hidden_layers', 2, Config.NumLayers);
  AssertEquals('num_attention_heads', 2, Config.NumHeads);
  AssertEquals('vocab_size', 11, Config.VocabSize);
  AssertEquals('max_position_embeddings', 16, Config.MaxPositions);
  AssertEquals('layer_norm_eps', 1e-5, Config.LayerNormEps, 1e-9);
  AssertEquals('partial_rotary_factor', 0.5,
    Config.PartialRotaryFactor, 1e-9);
  AssertEquals('rope_theta', 10000.0, Config.RopeTheta, 1e-6);
  AssertFalse('tie_word_embeddings (Phi untied)',
    Config.TieWordEmbeddings);
  AssertTrue('hidden_act gelu_new = tanh form', Config.HiddenActTanh);
end;

// Verifies the Phi (phi-1/phi-1_5/phi-2 architecture) import:
// tests/fixtures/tiny_phi.* is a pico randomly-initialized HF
// PhiForCausalLM (2 layers, 2 heads x 8 dims, hidden 16, intermediate 24
// deliberately != 4*hidden, vocab 11) covering the Phi quirks: SHARED-LN
// parallel residual (ONE input_layernorm feeds both branches,
// x + Attn(LN(x)) + MLP(LN(x))), PARTIAL rotary with the NeoX rotate_half
// pair layout (partial_rotary_factor=0.5 -> RoPE on the first 4 of 8 head
// dims, q/k rows PERMUTED at load time; the generator
// tools/phi_tiny_fixture.py asserts factors 0.25 and 1.0 would both
// change the logits), SEPARATE BIASED q/k/v + dense projections, biased
// mlp fc1/fc2 with gelu_new and the UNTIED lm_head WITH bias. Reference
// logits come from HF transformers in float64.
procedure TTestNeuralPretrained.TestPhiLogitParity;
var
  NN: TNNet;
  Config: TPhiConfig;
begin
  RandSeed := 424242;
  NN := BuildPhiFromSafeTensorsEx(
    FixturePath('tiny_phi.safetensors'),
    Config, {SeqLen=}0, {pInferenceOnly=}false,
    FixturePath('tiny_phi_config.json'));
  try
    AssertEquals('layers', 2, Config.NumLayers);
    AssertEquals('heads', 2, Config.NumHeads);
    AssertEquals('vocab', 11, Config.VocabSize);
    AssertEquals('partial_rotary_factor', 0.5,
      Config.PartialRotaryFactor, 1e-9);
    AssertFalse('untied', Config.TieWordEmbeddings);
    AssertEquals('prefix', 'model.', Config.Prefix);
    AssertLogitParityWithFixture(NN,
      FixturePath('tiny_phi_logits.json'), Config.MaxPositions,
      Config.VocabSize);
  finally
    NN.Free;
  end;
end;

procedure TTestNeuralPretrained.TestBertConfigFromJSONFile;
var
  Config: TBertConfig;
begin
  Config := ReadBertConfigFromJSONFile(
    FixturePath('tiny_bert_config.json'));
  AssertEquals('hidden_size', 8, Config.HiddenSize);
  AssertEquals('intermediate_size', 16, Config.IntermediateSize);
  AssertEquals('num_hidden_layers', 2, Config.NumLayers);
  AssertEquals('num_attention_heads', 2, Config.NumHeads);
  AssertEquals('vocab_size', 11, Config.VocabSize);
  AssertEquals('max_position_embeddings', 16, Config.MaxPositions);
  AssertEquals('type_vocab_size', 2, Config.TypeVocabSize);
  AssertTrue('layer_norm_eps = 1e-12',
    Abs(Config.LayerNormEps - 1e-12) < 1e-18);
  AssertFalse('hidden_act gelu = exact erf form', Config.HiddenActTanh);
end;

// Flagship encoder test: the imported BertModel's final hidden states must
// match HF transformers' float64 last_hidden_state on sequences with a
// NONZERO token-type segment boundary (the fixture asserts the segment
// embeddings, the bidirectional attention AND the exact-vs-tanh GELU all
// visibly shape this reference - see tools/bert_tiny_fixture.py).
procedure TTestNeuralPretrained.TestBertHiddenStateParity;
var
  NN: TNNet;
  Config: TBertConfig;
begin
  RandSeed := 424242;
  NN := BuildBertFromSafeTensorsEx(FixturePath('tiny_bert.safetensors'),
    Config, {SeqLen=}0, {pInferenceOnly=}false, {pIncludePooler=}false,
    FixturePath('tiny_bert_config.json'));
  try
    AssertEquals('layers', 2, Config.NumLayers);
    AssertEquals('prefix', '', Config.Prefix);
    AssertBertParityWithFixture(NN, FixturePath('tiny_bert_hidden.json'),
      Config.MaxPositions, Config.HiddenSize, {PoolerRow0Only=}false);
  finally
    NN.Free;
  end;
end;

// With pIncludePooler=true the output row 0 (the [CLS] position) must equal
// HF's pooler_output = tanh(pooler.dense(h[CLS])).
procedure TTestNeuralPretrained.TestBertPoolerParity;
var
  NN: TNNet;
  Config: TBertConfig;
begin
  RandSeed := 424242;
  NN := BuildBertFromSafeTensorsEx(FixturePath('tiny_bert.safetensors'),
    Config, {SeqLen=}0, {pInferenceOnly=}false, {pIncludePooler=}true,
    FixturePath('tiny_bert_config.json'));
  try
    AssertBertParityWithFixture(NN, FixturePath('tiny_bert_hidden.json'),
      Config.MaxPositions, Config.HiddenSize, {PoolerRow0Only=}true);
  finally
    NN.Free;
  end;
end;

procedure TTestNeuralPretrained.TestDistilBertConfigFromJSONFile;
var
  Config: TBertConfig;
begin
  Config := ReadBertConfigFromJSONFile(
    FixturePath('tiny_distilbert_config.json'));
  AssertTrue('family is distilbert', Config.Family = bfDistilBert);
  AssertEquals('dim', 8, Config.HiddenSize);
  AssertEquals('hidden_dim', 16, Config.IntermediateSize);
  AssertEquals('n_layers', 2, Config.NumLayers);
  AssertEquals('n_heads', 2, Config.NumHeads);
  AssertEquals('vocab_size', 11, Config.VocabSize);
  AssertEquals('max_position_embeddings', 16, Config.MaxPositions);
  AssertEquals('no token-type embeddings', 0, Config.TypeVocabSize);
  AssertTrue('layer_norm_eps = 1e-12 (hardcoded by modeling_distilbert)',
    Abs(Config.LayerNormEps - 1e-12) < 1e-18);
  AssertFalse('activation gelu = exact erf form', Config.HiddenActTanh);
end;

// The imported DistilBertModel's final hidden states must match HF
// transformers' float64 last_hidden_state: same post-LN math as BERT but
// loaded through the DistilBERT tensor-name map (transformer.layer.N.
// attention.q_lin/k_lin/v_lin/out_lin, sa_layer_norm, ffn.lin1/lin2,
// output_layer_norm), with NO token-type branch (input channel 1 is fed
// zeros and ignored) and no pooler - which pIncludePooler must REJECT.
procedure TTestNeuralPretrained.TestDistilBertHiddenStateParity;
var
  NN: TNNet;
  Config: TBertConfig;
  Rejected: boolean;
begin
  RandSeed := 424242;
  NN := BuildBertFromSafeTensorsEx(
    FixturePath('tiny_distilbert.safetensors'),
    Config, {SeqLen=}0, {pInferenceOnly=}false, {pIncludePooler=}false,
    FixturePath('tiny_distilbert_config.json'));
  try
    AssertTrue('family', Config.Family = bfDistilBert);
    AssertEquals('layers', 2, Config.NumLayers);
    AssertEquals('prefix (DistilBertModel exports unprefixed)', '',
      Config.Prefix);
    AssertBertParityWithFixture(NN,
      FixturePath('tiny_distilbert_hidden.json'),
      Config.MaxPositions, Config.HiddenSize, {PoolerRow0Only=}false);
  finally
    NN.Free;
  end;
  // DistilBERT has no pooler head: asking for one must fail loudly.
  Rejected := false;
  NN := nil;
  try
    try
      NN := BuildBertFromSafeTensorsEx(
        FixturePath('tiny_distilbert.safetensors'),
        Config, 0, false, {pIncludePooler=}true,
        FixturePath('tiny_distilbert_config.json'));
    except
      on E: EPretrainedImportError do Rejected := true;
    end;
  finally
    NN.Free;
  end;
  AssertTrue('pIncludePooler rejected for distilbert', Rejected);
end;

procedure TTestNeuralPretrained.TestRobertaConfigFromJSONFile;
var
  Config: TBertConfig;
begin
  Config := ReadBertConfigFromJSONFile(
    FixturePath('tiny_roberta_config.json'));
  AssertTrue('family is roberta', Config.Family = bfRoberta);
  AssertEquals('hidden_size', 8, Config.HiddenSize);
  AssertEquals('intermediate_size', 16, Config.IntermediateSize);
  AssertEquals('num_hidden_layers', 2, Config.NumLayers);
  AssertEquals('num_attention_heads', 2, Config.NumHeads);
  AssertEquals('vocab_size', 11, Config.VocabSize);
  AssertEquals('max_position_embeddings', 16, Config.MaxPositions);
  AssertEquals('type_vocab_size degenerates to 1', 1, Config.TypeVocabSize);
  AssertEquals('position offset = pad_token_id + 1', 2,
    Config.PositionOffset);
  AssertEquals('layer_norm_eps', 1e-5, Config.LayerNormEps, 1e-12);
  AssertFalse('hidden_act gelu = exact erf form', Config.HiddenActTanh);
end;

// THE RoBERTa bug to catch is the position-id offset:
// create_position_ids_from_input_ids starts real-token positions at
// padding_idx+1 = 2, so the importer must read checkpoint position rows
// 2..SeqLen+1 (rows 0/1 are NEVER used - the fixture generator rewrites
// them to huge values, so reading them blows the 2e-5 gate by 5 orders of
// magnitude) and cap the usable context at max_position_embeddings - 2
// (here 14). type_vocab_size is 1: the token-type branch is a constant
// row.
procedure TTestNeuralPretrained.TestRobertaHiddenStateParity;
var
  NN: TNNet;
  Config: TBertConfig;
  Rejected: boolean;
begin
  RandSeed := 424242;
  NN := BuildBertFromSafeTensorsEx(FixturePath('tiny_roberta.safetensors'),
    Config, {SeqLen=}0, {pInferenceOnly=}false, {pIncludePooler=}false,
    FixturePath('tiny_roberta_config.json'));
  try
    AssertTrue('family', Config.Family = bfRoberta);
    AssertEquals('position offset', 2, Config.PositionOffset);
    AssertEquals('prefix (RobertaModel exports unprefixed)', '',
      Config.Prefix);
    // SeqLen=0 must default to the USABLE context, not the table size.
    AssertEquals('input defaults to max_pos - 2',
      Config.MaxPositions - 2, NN.Layers[0].Output.SizeX);
    AssertBertParityWithFixture(NN, FixturePath('tiny_roberta_hidden.json'),
      Config.MaxPositions - 2, Config.HiddenSize, {PoolerRow0Only=}false);
  finally
    NN.Free;
  end;
  // Requesting more than max_position_embeddings - 2 positions must fail:
  // rows 0/1 of the table cannot back real positions.
  Rejected := false;
  NN := nil;
  try
    try
      NN := BuildBertFromSafeTensorsEx(
        FixturePath('tiny_roberta.safetensors'), Config,
        {SeqLen=}15, false, false,
        FixturePath('tiny_roberta_config.json'));
    except
      on E: EPretrainedImportError do Rejected := true;
    end;
  finally
    NN.Free;
  end;
  AssertTrue('SeqLen > max_pos - 2 rejected for roberta', Rejected);
end;

// RobertaModel carries a BERT-style pooler: with pIncludePooler=true the
// output row 0 must equal HF's pooler_output.
procedure TTestNeuralPretrained.TestRobertaPoolerParity;
var
  NN: TNNet;
  Config: TBertConfig;
begin
  RandSeed := 424242;
  NN := BuildBertFromSafeTensorsEx(FixturePath('tiny_roberta.safetensors'),
    Config, {SeqLen=}0, {pInferenceOnly=}false, {pIncludePooler=}true,
    FixturePath('tiny_roberta_config.json'));
  try
    AssertBertParityWithFixture(NN, FixturePath('tiny_roberta_hidden.json'),
      Config.MaxPositions - 2, Config.HiddenSize, {PoolerRow0Only=}true);
  finally
    NN.Free;
  end;
end;

// Fine-tuned classifier import, encoder family: HF
// BertForSequenceClassification pools the FIRST token - logits =
// classifier(pooler(hidden[:, 0])), the dense+tanh pooler over the [CLS]
// position (the OPPOSITE pooling convention to GPT-2's last-token, see
// TestGPT2SeqClsLogitParity). The imported net outputs (SeqLen,1,3) and
// row 0 must match HF's float64 class logits
// (tools/bert_seqcls_tiny_fixture.py asserts the oracle really is the
// [CLS]-pooled path); argmax indices must round-trip through id2label to
// the pinned 'neg'/'neu'/'pos' strings.
procedure TTestNeuralPretrained.TestBertSeqClsLogitParity;
var
  NN: TNNet;
  Config: TBertConfig;
  Id2Label: TStringList;
begin
  RandSeed := 424242;
  Id2Label := TStringList.Create;
  try
    NN := BuildBertForSequenceClassificationFromSafeTensorsEx(
      FixturePath('tiny_bert_seqcls.safetensors'), Config, Id2Label,
      {SeqLen=}0, {pInferenceOnly=}false,
      FixturePath('tiny_bert_seqcls_config.json'));
    try
      AssertEquals('prefix (BertFor* exports carry "bert.")', 'bert.',
        Config.Prefix);
      AssertEquals('id2label size', 3, Id2Label.Count);
      AssertEquals('id2label[0]', 'neg', Id2Label[0]);
      AssertEquals('id2label[2]', 'pos', Id2Label[2]);
      AssertEquals('num_labels output depth', 3,
        NN.GetLastLayer().Output.Depth);
      AssertSeqClsParityWithFixture(NN,
        FixturePath('tiny_bert_seqcls_logits.json'), Config.MaxPositions,
        {BertStyle=}true, Id2Label);
    finally
      NN.Free;
    end;
  finally
    Id2Label.Free;
  end;
end;

// Fine-tuned classifier import, decoder family: HF
// GPT2ForSequenceClassification applies the bias-free score head to every
// hidden state and pools the LAST NON-PAD token (only the final position
// of a causal trunk has seen the whole text). The imported net outputs
// per-position (SeqLen,1,3) class logits; SelectTokenLogits at the
// fixture's pooled_position (= SeqLen-1, full-length input) must match
// HF's float64 logits (tools/gpt2_seqcls_tiny_fixture.py asserts
// position-0 pooling would visibly differ, so this test discriminates
// the two pooling conventions); argmax round-trips through id2label.
procedure TTestNeuralPretrained.TestGPT2SeqClsLogitParity;
var
  NN: TNNet;
  Config: TGPT2Config;
  Id2Label: TStringList;
begin
  RandSeed := 424242;
  Id2Label := TStringList.Create;
  try
    NN := BuildGPT2ForSequenceClassificationFromSafeTensorsEx(
      FixturePath('tiny_gpt2_seqcls.safetensors'), Config, Id2Label,
      {SeqLen=}0, {pNumHeads=}2, {pInferenceOnly=}false,
      FixturePath('tiny_gpt2_seqcls_config.json'));
    try
      AssertEquals('prefix (GPT2For* exports carry "transformer.")',
        'transformer.', Config.Prefix);
      AssertEquals('id2label size', 3, Id2Label.Count);
      AssertEquals('id2label[1]', 'neu', Id2Label[1]);
      AssertEquals('num_labels output depth', 3,
        NN.GetLastLayer().Output.Depth);
      AssertSeqClsParityWithFixture(NN,
        FixturePath('tiny_gpt2_seqcls_logits.json'), Config.NCtx,
        {BertStyle=}false, Id2Label);
    finally
      NN.Free;
    end;
  finally
    Id2Label.Free;
  end;
end;

// BuildFromPretrained must read config.json's "architectures" array and
// route *ForSequenceClassification checkpoints to the classifier builders
// (the base-LM/encoder default for the same model_types is covered by
// TestBuildFromPretrainedDispatch). Full logit parity through both routes
// proves the dispatch reached the classifier heads; also covers the
// standalone ReadId2LabelFromJSONFile helper and the LABEL_i fallback of
// ClassIndexToLabel.
procedure TTestNeuralPretrained.TestBuildFromPretrainedSeqClsDispatch;
var
  NN: TNNet;
  Id2Label: TStringList;
begin
  RandSeed := 424242;
  // ClassIndexToLabel falls back to HF's default naming without a map.
  AssertEquals('LABEL_i fallback', 'LABEL_7', ClassIndexToLabel(nil, 7));
  // ---- BertForSequenceClassification route ----
  Id2Label := ReadId2LabelFromJSONFile(
    FixturePath('tiny_bert_seqcls_config.json'));
  try
    AssertEquals('bert id2label size', 3, Id2Label.Count);
    NN := BuildFromPretrained(FixturePath('tiny_bert_seqcls.safetensors'),
      0, false, FixturePath('tiny_bert_seqcls_config.json'));
    try
      AssertEquals('bert seqcls output depth', 3,
        NN.GetLastLayer().Output.Depth);
      AssertSeqClsParityWithFixture(NN,
        FixturePath('tiny_bert_seqcls_logits.json'), 16,
        {BertStyle=}true, Id2Label);
    finally
      NN.Free;
    end;
  finally
    Id2Label.Free;
  end;
  // ---- GPT2ForSequenceClassification route (n_head from the config) ----
  Id2Label := ReadId2LabelFromJSONFile(
    FixturePath('tiny_gpt2_seqcls_config.json'));
  try
    AssertEquals('gpt2 id2label size', 3, Id2Label.Count);
    NN := BuildFromPretrained(FixturePath('tiny_gpt2_seqcls.safetensors'),
      0, false, FixturePath('tiny_gpt2_seqcls_config.json'));
    try
      AssertEquals('gpt2 seqcls output depth', 3,
        NN.GetLastLayer().Output.Depth);
      AssertSeqClsParityWithFixture(NN,
        FixturePath('tiny_gpt2_seqcls_logits.json'), 16,
        {BertStyle=}false, Id2Label);
    finally
      NN.Free;
    end;
  finally
    Id2Label.Free;
  end;
end;

// BuildFromPretrained must route on config.json's model_type:
//   - gpt2 via a HF-style checkpoint DIRECTORY (config.json +
//     model.safetensors; n_head read from the config),
//   - mistral via a directory,
//   - llama, qwen2 and qwen3 via an explicit .safetensors file + config
//     path.
// Each route must reproduce the family's pinned oracle logits, proving the
// dispatch reached the correct builder with the correct config.
procedure TTestNeuralPretrained.TestBuildFromPretrainedDispatch;
var
  NN: TNNet;
  Dir: string;
  ConfigJson: TStringList;
begin
  RandSeed := 424242;
  // ---- gpt2 through the directory route ----
  Dir := IncludeTrailingPathDelimiter(GetTempDir(false)) +
    'cai_bfp_gpt2_' + IntToStr(Random(1000000)) + DirectorySeparator;
  ForceDirectories(Dir);
  ConfigJson := TStringList.Create;
  try
    CopyFileTo(FixturePath('tiny_gpt2.safetensors'),
      Dir + 'model.safetensors');
    ConfigJson.Text := '{"model_type": "gpt2", "n_head": 2}';
    ConfigJson.SaveToFile(Dir + 'config.json');
    NN := BuildFromPretrained(Dir);
    try
      AssertLogitParityWithFixture(NN, FixturePath('tiny_gpt2_logits.json'),
        16, 11);
    finally
      NN.Free;
    end;
    // ---- mistral through the directory route ----
    CopyFileTo(FixturePath('tiny_mistral.safetensors'),
      Dir + 'model.safetensors');
    CopyFileTo(FixturePath('tiny_mistral_config.json'), Dir + 'config.json');
    NN := BuildFromPretrained(Dir);
    try
      AssertLogitParityWithFixture(NN,
        FixturePath('tiny_mistral_logits.json'), 16, 11);
    finally
      NN.Free;
    end;
  finally
    ConfigJson.Free;
    DeleteFile(Dir + 'model.safetensors');
    DeleteFile(Dir + 'config.json');
    RemoveDir(Dir);
  end;
  // ---- llama through the file route (explicit config path) ----
  NN := BuildFromPretrained(FixturePath('tiny_llama.safetensors'), 0, false,
    FixturePath('tiny_llama_config.json'));
  try
    AssertLogitParityWithFixture(NN, FixturePath('tiny_llama_logits.json'),
      16, 11);
  finally
    NN.Free;
  end;
  // ---- qwen2 through the file route ----
  NN := BuildFromPretrained(FixturePath('tiny_qwen2.safetensors'), 0, false,
    FixturePath('tiny_qwen2_config.json'));
  try
    AssertLogitParityWithFixture(NN, FixturePath('tiny_qwen2_logits.json'),
      16, 12);
  finally
    NN.Free;
  end;
  // ---- qwen3 through the file route ----
  NN := BuildFromPretrained(FixturePath('tiny_qwen3.safetensors'), 0, false,
    FixturePath('tiny_qwen3_config.json'));
  try
    AssertLogitParityWithFixture(NN, FixturePath('tiny_qwen3_logits.json'),
      16, 13);
  finally
    NN.Free;
  end;
  // ---- gpt_neo through the file route ----
  NN := BuildFromPretrained(FixturePath('tiny_gptneo.safetensors'), 0, false,
    FixturePath('tiny_gptneo_config.json'));
  try
    AssertLogitParityWithFixture(NN, FixturePath('tiny_gptneo_logits.json'),
      16, 11);
  finally
    NN.Free;
  end;
  // ---- gpt_neox through the file route ----
  NN := BuildFromPretrained(FixturePath('tiny_gptneox.safetensors'), 0,
    false, FixturePath('tiny_gptneox_config.json'));
  try
    AssertLogitParityWithFixture(NN,
      FixturePath('tiny_gptneox_logits.json'), 16, 11);
  finally
    NN.Free;
  end;
  // ---- bert through the file route (ENCODER: hidden states, no pooler) ----
  NN := BuildFromPretrained(FixturePath('tiny_bert.safetensors'), 0, false,
    FixturePath('tiny_bert_config.json'));
  try
    AssertBertParityWithFixture(NN, FixturePath('tiny_bert_hidden.json'),
      16, 8, {PoolerRow0Only=}false);
  finally
    NN.Free;
  end;
  // ---- distilbert through the file route (the bert-family dispatch must
  // pick the DistilBERT tensor-name map from model_type) ----
  NN := BuildFromPretrained(FixturePath('tiny_distilbert.safetensors'), 0,
    false, FixturePath('tiny_distilbert_config.json'));
  try
    AssertBertParityWithFixture(NN,
      FixturePath('tiny_distilbert_hidden.json'), 16, 8,
      {PoolerRow0Only=}false);
  finally
    NN.Free;
  end;
  // ---- roberta through the file route (must apply the +2 position
  // offset; SeqLen is the usable 14, not the 16-row table) ----
  NN := BuildFromPretrained(FixturePath('tiny_roberta.safetensors'), 0,
    false, FixturePath('tiny_roberta_config.json'));
  try
    AssertBertParityWithFixture(NN,
      FixturePath('tiny_roberta_hidden.json'), 14, 8,
      {PoolerRow0Only=}false);
  finally
    NN.Free;
  end;
end;

// An unsupported model_type must raise EPretrainedImportError with a
// message that NAMES the offending type and LISTS the supported ones.
procedure TTestNeuralPretrained.TestBuildFromPretrainedRejectsUnsupportedModelType;
var
  NN: TNNet;
  ConfigPath, Msg: string;
  ConfigJson: TStringList;
  Failed: boolean;
begin
  RandSeed := 424242;
  ConfigPath := IncludeTrailingPathDelimiter(GetTempDir(false)) +
    'cai_bfp_t5_config_' + IntToStr(Random(1000000)) + '.json';
  ConfigJson := TStringList.Create;
  NN := nil;
  Msg := '';
  Failed := false;
  try
    ConfigJson.Text := '{"model_type": "t5"}';
    ConfigJson.SaveToFile(ConfigPath);
    try
      NN := BuildFromPretrained(FixturePath('tiny_llama.safetensors'), 0,
        false, ConfigPath);
    except
      on E: EPretrainedImportError do
      begin
        Failed := true;
        Msg := E.Message;
      end;
    end;
  finally
    NN.Free;
    ConfigJson.Free;
    DeleteFile(ConfigPath);
  end;
  AssertTrue('unsupported model_type must raise', Failed);
  AssertTrue('error names the offending type: ' + Msg,
    Pos('"t5"', Msg) > 0);
  AssertTrue('error lists the supported types: ' + Msg,
    (Pos('gpt2', Msg) > 0) and (Pos('gpt_neo', Msg) > 0) and
    (Pos('llama', Msg) > 0) and (Pos('mistral', Msg) > 0) and
    (Pos('qwen2', Msg) > 0));
end;

// The sentence-transformers pooling head: mean over the REAL token rows
// only (pads excluded), then L2 normalize. Pinned by hand on a (4,1,2)
// hidden volume where the pad rows carry large garbage that MUST NOT leak
// into the embedding.
procedure TTestNeuralPretrained.TestBertPoolSentenceEmbedding;
var
  Hidden, Embedding: TNNetVolume;
  Norm: double;
begin
  Hidden := TNNetVolume.Create();
  Embedding := TNNetVolume.Create();
  try
    Hidden.ReSize(4, 1, 2);
    // row 0: (1, 2); row 1: (3, 10); rows 2-3: pad garbage
    Hidden.FData[0] := 1; Hidden.FData[1] := 2;
    Hidden.FData[2] := 3; Hidden.FData[3] := 10;
    Hidden.FData[4] := 1000; Hidden.FData[5] := -1000;
    Hidden.FData[6] := -777; Hidden.FData[7] := 777;
    BertPoolSentenceEmbedding(Hidden, 2, Embedding);
    AssertEquals('embedding depth', 2, Embedding.Size);
    // mean of rows 0..1 = (2, 6); L2 norm = sqrt(40)
    AssertEquals('channel 0', 2 / Sqrt(40), Embedding.FData[0], 1e-6);
    AssertEquals('channel 1', 6 / Sqrt(40), Embedding.FData[1], 1e-6);
    Norm := Sqrt(Sqr(Embedding.FData[0]) + Sqr(Embedding.FData[1]));
    AssertEquals('unit L2 norm', 1.0, Norm, 1e-6);
    // all four rows real: pads now included by design
    BertPoolSentenceEmbedding(Hidden, 4, Embedding);
    AssertEquals('full-length mean ch0',
      (1 + 3 + 1000 - 777) / 4.0 / Sqrt(Sqr((1 + 3 + 1000 - 777) / 4.0) +
      Sqr((2 + 10 - 1000 + 777) / 4.0)), Embedding.FData[0], 1e-6);
  finally
    Embedding.Free;
    Hidden.Free;
  end;
end;

// BertTokenizeSentence must wrap the WordPiece content ids in [CLS]/[SEP]
// (ids 2/3 in the tiny fixture) and truncate the CONTENT to MaxTokens-2,
// matching HF encode(add_special_tokens=True) + truncation.
procedure TTestNeuralPretrained.TestBertTokenizeSentence;
var
  Tok: TNeuralHFTokenizer;
  Ids, Truncated: TNeuralIntegerArray;
  ContentIds: TNeuralIntegerArray;
  Cnt: integer;
begin
  Tok := TNeuralHFTokenizer.Create();
  try
    Tok.LoadFromFile(FixturePath('tiny_wordpiece_tokenizer.json'));
    Ids := BertTokenizeSentence(Tok, 'the quick brown fox');
    AssertTrue('has content', Length(Ids) > 2);
    AssertEquals('starts with [CLS]', Tok.TokenToId('[CLS]'), Ids[0]);
    AssertEquals('ends with [SEP]', Tok.TokenToId('[SEP]'),
      Ids[High(Ids)]);
    ContentIds := Tok.Encode('the quick brown fox');
    AssertEquals('content length', Length(ContentIds), Length(Ids) - 2);
    for Cnt := 0 to High(ContentIds) do
      AssertEquals('content id ' + IntToStr(Cnt), ContentIds[Cnt],
        Ids[Cnt + 1]);
    // truncation: keep [CLS] + first (MaxTokens-2) content ids + [SEP]
    Truncated := BertTokenizeSentence(Tok, 'the quick brown fox', 4);
    AssertEquals('truncated to MaxTokens', 4, Length(Truncated));
    AssertEquals('truncated [CLS]', Ids[0], Truncated[0]);
    AssertEquals('truncated content 0', Ids[1], Truncated[1]);
    AssertEquals('truncated content 1', Ids[2], Truncated[2]);
    AssertEquals('truncated [SEP]', Tok.TokenToId('[SEP]'),
      Truncated[3]);
  finally
    Tok.Free;
  end;
end;

initialization
  RegisterTest(TTestNeuralPretrained);
end.
