unit TestNeuralPretrained;
// Tests for the safetensors reader (neuralsafetensors.pas) and the GPT-2
// and Llama pretrained-checkpoint importers (neuralpretrained.pas).
//
// The flagship tests are TestGPT2LogitParity and TestLlamaLogitParity: each
// loads a committed tiny random checkpoint (tests/fixtures/tiny_gpt2 /
// tiny_llama .safetensors, generated by tools/gpt2_tiny_fixture.py /
// tools/llama_tiny_fixture.py) and asserts that the imported TNNet's logits
// match the INDEPENDENT pure-Python forward (the oracle, same generator
// script; the Llama oracle is itself verified against HF transformers'
// LlamaForCausalLM to ~9e-7) to < 1e-3 (typically ~1e-5 end-to-end f32).
//
// This unit is coded by Claude (AI).
{$mode objfpc}{$H+}

interface

uses
  Classes, SysUtils, fpcunit, testregistry, fpjson, jsonparser,
  neuralvolume, neuralnetwork, neuralsafetensors, neuralpretrained;

type
  TTestNeuralPretrained = class(TTestCase)
  private
    function FixturePath(const FileName: string): string;
    // Composes a minimal safetensors byte stream into a temp file and
    // returns its path. HeaderJson is written verbatim (preceded by its
    // 8-byte little-endian length); Payload is the raw data section.
    function WriteTempSafeTensors(const HeaderJson: string;
      const Payload: array of byte): string;
    // Byte-for-byte file copy (used to assemble HF-style checkpoint
    // directories - config.json + model.safetensors - in a temp dir for
    // the BuildFromPretrained directory-dispatch tests).
    procedure CopyFileTo(const Src, Dst: string);
    // Shared parity loop: feeds every "sequences" row of the reference
    // logits fixture (JSON {"sequences": [[ids..]..], "logits": [[[..]]]})
    // through NN and asserts max |logit diff| < 1e-4 (hard ceiling 1e-3 -
    // NEVER loosen past it; fix the model instead).
    procedure AssertLogitParityWithFixture(NN: TNNet;
      const LogitsFileName: string; SeqLen, Vocab: integer);
  published
    procedure TestTokenLayerNormForwardAndSaveLoad;
    procedure TestLearnedPositionalEmbeddingForwardAndSaveLoad;
    procedure TestF16Decode;
    procedure TestBF16Decode;
    procedure TestReaderReadsF16AndBF16Tensors;
    procedure TestReaderRejectsGarbage;
    procedure TestReaderReadsTinyFixture;
    procedure TestImporterFailsOnMissingTensor;
    procedure TestGPT2ConfigFromFixture;
    procedure TestGPT2LogitParity;
    procedure TestMakeInferenceOnlyKeepsOutputs;
    procedure TestTokenRMSNormForwardAndSaveLoad;
    procedure TestRotaryHalfPermutationMatchesHFRotateHalf;
    procedure TestSwiGLUMatchesLlamaMLPGating;
    procedure TestLlamaConfigFromJSONFile;
    procedure TestLlamaImporterFailsOnMissingTensor;
    procedure TestLlamaLogitParity;
    procedure TestShardedReaderMatchesSingleFile;
    procedure TestShardedLlamaLogitsBitIdentical;
    procedure TestDistilGPT2LogitParity;
    procedure TestSmolLM2LogitParity;
    procedure TestMistralLogitParity;
    procedure TestQwen2LogitParity;
    procedure TestBuildFromPretrainedDispatch;
    procedure TestBuildFromPretrainedRejectsUnsupportedModelType;
  end;

implementation

function TTestNeuralPretrained.FixturePath(const FileName: string): string;
begin
  // RunAll.sh runs the suite from the tests/ directory; also probe the repo
  // root in case the binary is started from there.
  Result := 'fixtures' + DirectorySeparator + FileName;
  if not FileExists(Result) then
    Result := 'tests' + DirectorySeparator + 'fixtures' + DirectorySeparator +
      FileName;
  if not FileExists(Result) then
    Fail('Fixture not found: ' + FileName +
      ' (run python3 tools/gpt2_tiny_fixture.py from the repo root).');
end;

function TTestNeuralPretrained.WriteTempSafeTensors(const HeaderJson: string;
  const Payload: array of byte): string;
var
  FS: TFileStream;
  HeaderLen: QWord;
begin
  Result := GetTempDir(false) + 'cai_st_test_' + IntToStr(Random(1000000)) +
    '.safetensors';
  FS := TFileStream.Create(Result, fmCreate);
  try
    HeaderLen := Length(HeaderJson);
    FS.WriteBuffer(HeaderLen, 8);
    if HeaderJson <> '' then
      FS.WriteBuffer(HeaderJson[1], Length(HeaderJson));
    if Length(Payload) > 0 then
      FS.WriteBuffer(Payload[0], Length(Payload));
  finally
    FS.Free;
  end;
end;

procedure TTestNeuralPretrained.CopyFileTo(const Src, Dst: string);
var
  SrcStream, DstStream: TFileStream;
begin
  SrcStream := TFileStream.Create(Src, fmOpenRead);
  try
    DstStream := TFileStream.Create(Dst, fmCreate);
    try
      DstStream.CopyFrom(SrcStream, SrcStream.Size);
    finally
      DstStream.Free;
    end;
  finally
    SrcStream.Free;
  end;
end;

procedure TTestNeuralPretrained.AssertLogitParityWithFixture(NN: TNNet;
  const LogitsFileName: string; SeqLen, Vocab: integer);
var
  RefRoot: TJSONData;
  Sequences, SeqArr, LogitsArr, PosArr, RowArr: TJSONArray;
  Input, Output: TNNetVolume;
  RefJson: TStringList;
  SeqCnt, PosCnt, TokCnt: integer;
  Diff, MaxDiff: double;
begin
  RefJson := TStringList.Create;
  Input := TNNetVolume.Create;
  Output := TNNetVolume.Create;
  RefRoot := nil;
  try
    RefJson.LoadFromFile(LogitsFileName);
    RefRoot := GetJSON(RefJson.Text);
    Sequences := TJSONArray(TJSONObject(RefRoot).Find('sequences'));
    LogitsArr := TJSONArray(TJSONObject(RefRoot).Find('logits'));
    AssertTrue('sequences present', Sequences <> nil);
    AssertTrue('logits present', LogitsArr <> nil);
    AssertTrue('at least 3 sequences', Sequences.Count >= 3);
    MaxDiff := 0;
    Input.ReSize(SeqLen, 1, 1);
    for SeqCnt := 0 to Sequences.Count - 1 do
    begin
      SeqArr := TJSONArray(Sequences.Items[SeqCnt]);
      AssertEquals('sequence length', SeqLen, SeqArr.Count);
      for PosCnt := 0 to SeqLen - 1 do
        Input.FData[PosCnt] := SeqArr.Items[PosCnt].AsInteger;
      NN.Compute(Input);
      NN.GetOutput(Output);
      AssertEquals('output size', SeqLen * Vocab, Output.Size);
      PosArr := TJSONArray(LogitsArr.Items[SeqCnt]);
      for PosCnt := 0 to SeqLen - 1 do
      begin
        RowArr := TJSONArray(PosArr.Items[PosCnt]);
        for TokCnt := 0 to Vocab - 1 do
        begin
          Diff := Abs(Output.FData[PosCnt * Vocab + TokCnt] -
            RowArr.Items[TokCnt].AsFloat);
          if Diff > MaxDiff then MaxDiff := Diff;
        end;
      end;
    end;
    // f32 end-to-end vs the float64 oracle on f32-rounded weights. NEVER
    // loosen the gate past 1e-3 - if parity breaks, fix the model, don't
    // widen the tolerance.
    AssertTrue('logit parity vs ' + LogitsFileName + ': max |diff| = ' +
      FloatToStr(MaxDiff) + ' must be < 1e-4', MaxDiff < 1e-4);
  finally
    RefRoot.Free;
    Output.Free;
    Input.Free;
    RefJson.Free;
  end;
end;

procedure TTestNeuralPretrained.TestTokenLayerNormForwardAndSaveLoad;
var
  NN, NN2: TNNet;
  LN: TNNetLayer;
  Input, Out1, Out2: TNNetVolume;
  i, t, c: integer;
  Mean, Variance, Expected: double;
  TokenVals: array[0..3] of double;
begin
  RandSeed := 424242;
  // (SeqLen=3, 1, Depth=4) input; per-token normalization over Depth.
  NN := TNNet.Create();
  NN.AddLayer( TNNetInput.Create(3, 1, 4) );
  LN := NN.AddLayer( TNNetTokenLayerNorm.Create(1e-5) );
  // Distinct gamma/beta per channel.
  for c := 0 to 3 do
  begin
    LN.Neurons[0].Weights.FData[c] := 0.5 + 0.25 * c; // gamma
    LN.Neurons[1].Weights.FData[c] := 0.1 * c - 0.2;  // beta
  end;
  LN.FlushWeightCache();
  Input := TNNetVolume.Create(3, 1, 4);
  Out1 := TNNetVolume.Create;
  Out2 := TNNetVolume.Create;
  NN2 := TNNet.Create();
  try
    for i := 0 to Input.Size - 1 do
      Input.FData[i] := Sin(i * 1.7) * 2 + 0.3 * i;
    NN.Compute(Input);
    NN.GetOutput(Out1);
    // Hand-computed per-token LayerNorm for each of the 3 tokens.
    for t := 0 to 2 do
    begin
      Mean := 0;
      for c := 0 to 3 do
      begin
        TokenVals[c] := Input.FData[t * 4 + c];
        Mean := Mean + TokenVals[c];
      end;
      Mean := Mean / 4;
      Variance := 0;
      for c := 0 to 3 do
        Variance := Variance + Sqr(TokenVals[c] - Mean);
      Variance := Variance / 4;
      for c := 0 to 3 do
      begin
        Expected := (0.5 + 0.25 * c) *
          ((TokenVals[c] - Mean) / Sqrt(Variance + 1e-5)) + (0.1 * c - 0.2);
        AssertEquals('per-token LN value t=' + IntToStr(t) + ' c=' +
          IntToStr(c), Expected, Out1.FData[t * 4 + c], 1e-5);
      end;
    end;
    // Save/load round-trip must preserve structure and weights.
    NN2.LoadFromString(NN.SaveToString());
    AssertTrue('reloaded layer class',
      NN2.Layers[1] is TNNetTokenLayerNorm);
    NN2.Compute(Input);
    NN2.GetOutput(Out2);
    for i := 0 to Out1.Size - 1 do
      AssertEquals('save/load forward equality at ' + IntToStr(i),
        Out1.FData[i], Out2.FData[i], 1e-7);
  finally
    NN2.Free;
    Out2.Free;
    Out1.Free;
    Input.Free;
    NN.Free;
  end;
end;

procedure TTestNeuralPretrained.TestLearnedPositionalEmbeddingForwardAndSaveLoad;
var
  NN, NN2: TNNet;
  PosLayer: TNNetLayer;
  Input, Out1, Out2: TNNetVolume;
  i, x, c: integer;
begin
  RandSeed := 424242;
  // (SeqLen=3, 1, Depth=2) input with a MaxPosition=5 table: only the first
  // 3 rows participate.
  NN := TNNet.Create();
  NN.AddLayer( TNNetInput.Create(3, 1, 2) );
  PosLayer := NN.AddLayer( TNNetLearnedPositionalEmbedding.Create(5) );
  for x := 0 to 4 do
    for c := 0 to 1 do
      PosLayer.Neurons[0].Weights[x, 0, c] := 10 * x + c;
  PosLayer.FlushWeightCache();
  Input := TNNetVolume.Create(3, 1, 2);
  Out1 := TNNetVolume.Create;
  Out2 := TNNetVolume.Create;
  NN2 := TNNet.Create();
  try
    for i := 0 to Input.Size - 1 do Input.FData[i] := 0.5 * i;
    NN.Compute(Input);
    NN.GetOutput(Out1);
    for x := 0 to 2 do
      for c := 0 to 1 do
        AssertEquals('pos add x=' + IntToStr(x) + ' c=' + IntToStr(c),
          0.5 * (x * 2 + c) + 10 * x + c, Out1.FData[x * 2 + c], 1e-6);
    NN2.LoadFromString(NN.SaveToString());
    AssertTrue('reloaded layer class',
      NN2.Layers[1] is TNNetLearnedPositionalEmbedding);
    AssertEquals('MaxPosition round-trip', 5,
      TNNetLearnedPositionalEmbedding(NN2.Layers[1]).MaxPosition);
    NN2.Compute(Input);
    NN2.GetOutput(Out2);
    for i := 0 to Out1.Size - 1 do
      AssertEquals('save/load forward equality at ' + IntToStr(i),
        Out1.FData[i], Out2.FData[i], 1e-7);
  finally
    NN2.Free;
    Out2.Free;
    Out1.Free;
    Input.Free;
    NN.Free;
  end;
end;

procedure TTestNeuralPretrained.TestF16Decode;
begin
  RandSeed := 424242;
  // Hand-computed IEEE binary16 bit patterns.
  AssertEquals('f16 1.0', 1.0, DecodeF16($3C00), 0);
  AssertEquals('f16 -2.0', -2.0, DecodeF16($C000), 0);
  AssertEquals('f16 0.5', 0.5, DecodeF16($3800), 0);
  AssertEquals('f16 65504 (max normal)', 65504.0, DecodeF16($7BFF), 0);
  // 0x3555: exp=13 -> 2^-2, mantissa=0x155=341 -> (1+341/1024)*0.25
  AssertEquals('f16 0x3555', (1.0 + 341.0 / 1024.0) * 0.25,
    DecodeF16($3555), 0);
  // Subnormals: value = mantissa * 2^-24.
  AssertEquals('f16 smallest subnormal', 5.9604644775390625e-8,
    DecodeF16($0001), 0);
  AssertEquals('f16 largest subnormal', 1023.0 * 5.9604644775390625e-8,
    DecodeF16($03FF), 0);
  // Signed zero.
  AssertEquals('f16 +0', 0.0, DecodeF16($0000), 0);
  AssertEquals('f16 -0', 0.0, DecodeF16($8000), 0);
end;

procedure TTestNeuralPretrained.TestBF16Decode;
begin
  RandSeed := 424242;
  // bf16 is the upper half of a single's bit pattern.
  AssertEquals('bf16 1.0', 1.0, DecodeBF16($3F80), 0);
  AssertEquals('bf16 -1.0', -1.0, DecodeBF16($BF80), 0);
  AssertEquals('bf16 3.140625', 3.140625, DecodeBF16($4049), 0);
  AssertEquals('bf16 -0.5', -0.5, DecodeBF16($BF00), 0);
  AssertEquals('bf16 256', 256.0, DecodeBF16($4380), 0);
  AssertEquals('bf16 +0', 0.0, DecodeBF16($0000), 0);
  // Smallest bf16 normal = 2^-126.
  AssertEquals('bf16 2^-126', 1.1754943508222875e-38, DecodeBF16($0080), 0);
end;

procedure TTestNeuralPretrained.TestReaderReadsF16AndBF16Tensors;
var
  Path: string;
  Reader: TNNetSafeTensorsReader;
  V: TNNetVolume;
begin
  RandSeed := 424242;
  // Two tensors: "a" = F16 [2] = {1.0 (0x3C00), -2.0 (0xC000)},
  //              "b" = BF16 [2] = {1.0 (0x3F80), 3.140625 (0x4049)}.
  // Bytes are little-endian.
  Path := WriteTempSafeTensors(
    '{"a":{"dtype":"F16","shape":[2],"data_offsets":[0,4]},' +
    '"b":{"dtype":"BF16","shape":[2],"data_offsets":[4,8]}}',
    [$00, $3C, $00, $C0, $80, $3F, $49, $40]);
  try
    Reader := TNNetSafeTensorsReader.Create(Path);
    try
      AssertEquals('tensor count', 2, Reader.Count);
      AssertEquals('a dtype', 'F16', Reader.GetDType('a'));
      AssertEquals('b dtype', 'BF16', Reader.GetDType('b'));
      V := TNNetVolume.Create;
      try
        Reader.LoadTensorFlat('a', V);
        AssertEquals('a size', 2, V.Size);
        AssertEquals('a[0]', 1.0, V.FData[0], 0);
        AssertEquals('a[1]', -2.0, V.FData[1], 0);
        Reader.LoadTensorFlat('b', V);
        AssertEquals('b[0]', 1.0, V.FData[0], 0);
        AssertEquals('b[1]', 3.140625, V.FData[1], 0);
      finally
        V.Free;
      end;
    finally
      Reader.Free;
    end;
  finally
    DeleteFile(Path);
  end;
end;

procedure TTestNeuralPretrained.TestReaderRejectsGarbage;
var
  Path: string;
  Reader: TNNetSafeTensorsReader;
  FS: TFileStream;
  Failed: boolean;
begin
  RandSeed := 424242;
  // (a) File shorter than the 8-byte header length.
  Path := GetTempDir(false) + 'cai_st_trunc.safetensors';
  FS := TFileStream.Create(Path, fmCreate);
  FS.WriteBuffer(Path[1], 4);
  FS.Free;
  Failed := false;
  try
    Reader := TNNetSafeTensorsReader.Create(Path);
    Reader.Free;
  except
    on ESafeTensorsError do Failed := true;
  end;
  DeleteFile(Path);
  AssertTrue('truncated file must be rejected', Failed);

  // (b) Header length exceeding the file size.
  Path := WriteTempSafeTensors('', []);
  // Rewrite the first 8 bytes with a huge length.
  FS := TFileStream.Create(Path, fmOpenReadWrite);
  FS.Position := 0;
  FS.WriteDWord($FFFFFF);
  FS.Free;
  Failed := false;
  try
    Reader := TNNetSafeTensorsReader.Create(Path);
    Reader.Free;
  except
    on ESafeTensorsError do Failed := true;
  end;
  DeleteFile(Path);
  AssertTrue('oversized header length must be rejected', Failed);

  // (c) Header is not JSON.
  Path := WriteTempSafeTensors('this is not json at all!!', []);
  Failed := false;
  try
    Reader := TNNetSafeTensorsReader.Create(Path);
    Reader.Free;
  except
    on ESafeTensorsError do Failed := true;
  end;
  DeleteFile(Path);
  AssertTrue('non-JSON header must be rejected', Failed);

  // (d) data_offsets pointing beyond the data section.
  Path := WriteTempSafeTensors(
    '{"t":{"dtype":"F32","shape":[4],"data_offsets":[0,16]}}',
    [$00, $00, $80, $3F]); // only 4 payload bytes, 16 promised
  Failed := false;
  try
    Reader := TNNetSafeTensorsReader.Create(Path);
    Reader.Free;
  except
    on ESafeTensorsError do Failed := true;
  end;
  DeleteFile(Path);
  AssertTrue('out-of-bounds data_offsets must be rejected', Failed);

  // (e) Element count inconsistent with the byte span.
  Path := WriteTempSafeTensors(
    '{"t":{"dtype":"F32","shape":[2],"data_offsets":[0,4]}}',
    [$00, $00, $80, $3F]);
  Failed := false;
  try
    Reader := TNNetSafeTensorsReader.Create(Path);
    Reader.Free;
  except
    on ESafeTensorsError do Failed := true;
  end;
  DeleteFile(Path);
  AssertTrue('shape/byte-span mismatch must be rejected', Failed);
end;

procedure TTestNeuralPretrained.TestReaderReadsTinyFixture;
var
  Reader: TNNetSafeTensorsReader;
begin
  RandSeed := 424242;
  Reader := TNNetSafeTensorsReader.Create(FixturePath('tiny_gpt2.safetensors'));
  try
    AssertTrue('wte present', Reader.HasTensor('wte.weight'));
    AssertEquals('wte dtype', 'F32', Reader.GetDType('wte.weight'));
    AssertEquals('wte dims', 2, Reader.DimCount('wte.weight'));
    AssertEquals('vocab', 11, Reader.DimSize('wte.weight', 0));
    AssertEquals('d_model', 8, Reader.DimSize('wte.weight', 1));
    AssertEquals('wpe rows', 16, Reader.DimSize('wpe.weight', 0));
    AssertEquals('c_attn shape', '[8, 24]',
      Reader.ShapeAsString('h.0.attn.c_attn.weight'));
    AssertTrue('block 1 present', Reader.HasTensor('h.1.ln_1.weight'));
    AssertTrue('block 2 absent', not Reader.HasTensor('h.2.ln_1.weight'));
  finally
    Reader.Free;
  end;
end;

procedure TTestNeuralPretrained.TestImporterFailsOnMissingTensor;
var
  Path: string;
  NN: TNNet;
  Failed: boolean;
  Payload: array of byte;
  i: integer;
begin
  RandSeed := 424242;
  // A "checkpoint" containing ONLY wte.weight [2, 4]: the importer must
  // fail loudly on the missing wpe.weight, not import partially.
  SetLength(Payload, 2 * 4 * 4);
  for i := 0 to High(Payload) do Payload[i] := 0;
  Path := WriteTempSafeTensors(
    '{"wte.weight":{"dtype":"F32","shape":[2,4],"data_offsets":[0,32]}}',
    Payload);
  Failed := false;
  NN := nil;
  try
    try
      NN := BuildGPT2FromSafeTensors(Path, 4, 2);
    except
      on EPretrainedImportError do Failed := true;
    end;
  finally
    NN.Free;
    DeleteFile(Path);
  end;
  AssertTrue('missing wpe.weight must abort the import', Failed);
end;

procedure TTestNeuralPretrained.TestGPT2ConfigFromFixture;
var
  Reader: TNNetSafeTensorsReader;
  Config: TGPT2Config;
begin
  RandSeed := 424242;
  Reader := TNNetSafeTensorsReader.Create(FixturePath('tiny_gpt2.safetensors'));
  try
    Config := ReadGPT2Config(Reader, 2);
    AssertEquals('n_layer', 2, Config.NLayers);
    AssertEquals('n_head', 2, Config.NHeads);
    AssertEquals('n_embd', 8, Config.NEmbd);
    AssertEquals('n_ctx', 16, Config.NCtx);
    AssertEquals('vocab', 11, Config.VocabSize);
    AssertEquals('prefix', '', Config.Prefix);
  finally
    Reader.Free;
  end;
end;

procedure TTestNeuralPretrained.TestGPT2LogitParity;
var
  NN: TNNet;
  Config: TGPT2Config;
  RefRoot: TJSONData;
  Sequences, SeqArr, LogitsArr, PosArr, RowArr: TJSONArray;
  Input, Output: TNNetVolume;
  RefJson: TStringList;
  SeqCnt, PosCnt, TokCnt: integer;
  Diff, MaxDiff: double;
  SeqLen, Vocab: integer;
begin
  RandSeed := 424242;
  NN := BuildGPT2FromSafeTensorsEx(FixturePath('tiny_gpt2.safetensors'),
    Config, {SeqLen=}0, {NumHeads=}2);
  RefJson := TStringList.Create;
  Input := TNNetVolume.Create;
  Output := TNNetVolume.Create;
  RefRoot := nil;
  try
    AssertEquals('n_layer', 2, Config.NLayers);
    SeqLen := Config.NCtx;
    Vocab := Config.VocabSize;
    RefJson.LoadFromFile(FixturePath('tiny_gpt2_logits.json'));
    RefRoot := GetJSON(RefJson.Text);
    Sequences := TJSONArray(TJSONObject(RefRoot).Find('sequences'));
    LogitsArr := TJSONArray(TJSONObject(RefRoot).Find('logits'));
    AssertTrue('sequences present', Sequences <> nil);
    AssertTrue('logits present', LogitsArr <> nil);
    AssertTrue('at least 3 sequences', Sequences.Count >= 3);
    MaxDiff := 0;
    Input.ReSize(SeqLen, 1, 1);
    for SeqCnt := 0 to Sequences.Count - 1 do
    begin
      SeqArr := TJSONArray(Sequences.Items[SeqCnt]);
      AssertEquals('sequence length', SeqLen, SeqArr.Count);
      for PosCnt := 0 to SeqLen - 1 do
        Input.FData[PosCnt] := SeqArr.Items[PosCnt].AsInteger;
      NN.Compute(Input);
      NN.GetOutput(Output);
      AssertEquals('output size', SeqLen * Vocab, Output.Size);
      PosArr := TJSONArray(LogitsArr.Items[SeqCnt]);
      for PosCnt := 0 to SeqLen - 1 do
      begin
        RowArr := TJSONArray(PosArr.Items[PosCnt]);
        for TokCnt := 0 to Vocab - 1 do
        begin
          Diff := Abs(Output.FData[PosCnt * Vocab + TokCnt] -
            RowArr.Items[TokCnt].AsFloat);
          if Diff > MaxDiff then MaxDiff := Diff;
        end;
      end;
    end;
    // f32 end-to-end vs the float64 Python oracle on f32-rounded weights:
    // observed max |diff| is ~1.4e-6, so the 1e-4 gate has a ~70x margin
    // (the hard acceptance ceiling is 1e-3). NEVER loosen the gate past
    // 1e-3 - if parity breaks, fix the model, don't widen the tolerance.
    AssertTrue('GPT-2 logit parity: max |diff| = ' +
      FloatToStr(MaxDiff) + ' must be < 1e-4', MaxDiff < 1e-4);
  finally
    RefRoot.Free;
    Output.Free;
    Input.Free;
    RefJson.Free;
    NN.Free;
  end;
end;

// MakeInferenceOnly shrinks every neuron's Delta/BackInertia training
// volumes; the forward pass must be bit-for-bit unaffected, whether the
// shrink happens during construction (pInferenceOnly=True) or on an
// already-built net (TNNet.MakeInferenceOnly).
procedure TTestNeuralPretrained.TestMakeInferenceOnlyKeepsOutputs;
var
  NNTrain, NNInfer: TNNet;
  Config: TGPT2Config;
  Input, OutTrain, OutInfer: TNNetVolume;
  i: integer;
begin
  NNTrain := BuildGPT2FromSafeTensorsEx(FixturePath('tiny_gpt2.safetensors'),
    Config, {SeqLen=}0, {NumHeads=}2);
  NNInfer := BuildGPT2FromSafeTensorsEx(FixturePath('tiny_gpt2.safetensors'),
    Config, {SeqLen=}0, {NumHeads=}2, {pInferenceOnly=}true);
  Input := TNNetVolume.Create(Config.NCtx, 1, 1);
  OutTrain := TNNetVolume.Create;
  OutInfer := TNNetVolume.Create;
  try
    for i := 0 to Config.NCtx - 1 do
      Input.FData[i] := (i * 3 + 1) mod Config.VocabSize;
    NNTrain.Compute(Input);
    NNTrain.GetOutput(OutTrain);
    NNInfer.Compute(Input);
    NNInfer.GetOutput(OutInfer);
    AssertEquals('output size', OutTrain.Size, OutInfer.Size);
    for i := 0 to OutTrain.Size - 1 do
      AssertEquals('pInferenceOnly logit ' + IntToStr(i),
        OutTrain.FData[i], OutInfer.FData[i], 0);
    // Shrinking a finished net must not change its outputs either.
    NNTrain.MakeInferenceOnly();
    NNTrain.Compute(Input);
    NNTrain.GetOutput(OutInfer);
    for i := 0 to OutTrain.Size - 1 do
      AssertEquals('post-build MakeInferenceOnly logit ' + IntToStr(i),
        OutTrain.FData[i], OutInfer.FData[i], 0);
    AssertEquals('delta volume shrunk', 1,
      NNTrain.Layers[1].Neurons[0].Delta.Size);
    AssertEquals('inertia volume shrunk', 1,
      NNTrain.Layers[1].Neurons[0].BackInertia.Size);
  finally
    OutInfer.Free;
    OutTrain.Free;
    Input.Free;
    NNInfer.Free;
    NNTrain.Free;
  end;
end;

// Per-token RMSNorm (TNNetTokenRMSNorm) must match a hand-computed HF
// LlamaRMSNorm: per (x,y) token over Depth, no mean subtraction, learnable
// gain, no bias; and survive a save/load round-trip.
procedure TTestNeuralPretrained.TestTokenRMSNormForwardAndSaveLoad;
var
  NN, NN2: TNNet;
  RMSLayer: TNNetLayer;
  Input, Out1, Out2: TNNetVolume;
  i, t, c: integer;
  MeanSqr, Expected: double;
  TokenVals: array[0..3] of double;
begin
  RandSeed := 424242;
  // (SeqLen=3, 1, Depth=4) input; per-token normalization over Depth.
  NN := TNNet.Create();
  NN.AddLayer( TNNetInput.Create(3, 1, 4) );
  RMSLayer := NN.AddLayer( TNNetTokenRMSNorm.Create(1e-5) );
  for c := 0 to 3 do
    RMSLayer.Neurons[0].Weights.FData[c] := 0.5 + 0.25 * c; // gain
  RMSLayer.FlushWeightCache();
  Input := TNNetVolume.Create(3, 1, 4);
  Out1 := TNNetVolume.Create;
  Out2 := TNNetVolume.Create;
  NN2 := TNNet.Create();
  try
    for i := 0 to Input.Size - 1 do
      Input.FData[i] := Sin(i * 1.7) * 2 + 0.3 * i;
    NN.Compute(Input);
    NN.GetOutput(Out1);
    // Hand-computed per-token RMSNorm for each of the 3 tokens.
    for t := 0 to 2 do
    begin
      MeanSqr := 0;
      for c := 0 to 3 do
      begin
        TokenVals[c] := Input.FData[t * 4 + c];
        MeanSqr := MeanSqr + Sqr(TokenVals[c]);
      end;
      MeanSqr := MeanSqr / 4;
      for c := 0 to 3 do
      begin
        Expected := (0.5 + 0.25 * c) *
          (TokenVals[c] / Sqrt(MeanSqr + 1e-5));
        AssertEquals('per-token RMSNorm value t=' + IntToStr(t) + ' c=' +
          IntToStr(c), Expected, Out1.FData[t * 4 + c], 1e-5);
      end;
    end;
    // Save/load round-trip must preserve structure, eps and gains.
    NN2.LoadFromString(NN.SaveToString());
    AssertTrue('reloaded layer class',
      NN2.Layers[1] is TNNetTokenRMSNorm);
    NN2.Compute(Input);
    NN2.GetOutput(Out2);
    for i := 0 to Out1.Size - 1 do
      AssertEquals('save/load forward equality at ' + IntToStr(i),
        Out1.FData[i], Out2.FData[i], 1e-7);
  finally
    NN2.Free;
    Out2.Free;
    Out1.Free;
    Input.Free;
    NN.Free;
  end;
end;

// The Llama importer compensates for HF's rotate_half pair layout
// (pairs (i, i+hd/2)) by permuting q/k projection rows into
// TNNetRotaryEmbedding's interleaved (2k, 2k+1) layout:
//   CAI channel 2k <- HF row k;  CAI channel 2k+1 <- HF row k+hd/2.
// This test feeds a PERMUTED head vector through TNNetRotaryEmbedding and
// asserts the result equals the hand-computed HF rotate_half rotation of
// the ORIGINAL vector, re-read through the same permutation.
procedure TTestNeuralPretrained.TestRotaryHalfPermutationMatchesHFRotateHalf;
const
  SeqLen = 5;
  HeadDim = 6; // half = 3
  RopeBase = 10000.0;
var
  NN: TNNet;
  Input, Output: TNNetVolume;
  HFVec, HFRot: array[0..HeadDim - 1] of double;
  Freq, CosV, SinV: double;
  Pos, i, Half: integer;
begin
  RandSeed := 424242;
  Half := HeadDim div 2;
  NN := TNNet.Create();
  NN.AddLayer( TNNetInput.Create(SeqLen, 1, HeadDim) );
  NN.AddLayer( TNNetRotaryEmbedding.Create(RopeBase) );
  Input := TNNetVolume.Create(SeqLen, 1, HeadDim);
  Output := TNNetVolume.Create;
  try
    for i := 0 to Input.Size - 1 do
      Input.FData[i] := Cos(i * 0.9) + 0.1 * i;
    NN.Compute(Input);
    NN.GetOutput(Output);
    for Pos := 0 to SeqLen - 1 do
    begin
      // Re-read the CAI channels back into the HF half-split layout:
      // HF row k = CAI channel 2k; HF row k+half = CAI channel 2k+1.
      for i := 0 to Half - 1 do
      begin
        HFVec[i] := Input.FData[Pos * HeadDim + 2 * i];
        HFVec[i + Half] := Input.FData[Pos * HeadDim + 2 * i + 1];
      end;
      // Hand-computed HF rotate_half rotation:
      //   y[i]      = x[i]*cos - x[i+half]*sin
      //   y[i+half] = x[i+half]*cos + x[i]*sin,  angle = pos * base^(-2i/hd)
      for i := 0 to Half - 1 do
      begin
        Freq := Exp(-2.0 * i / HeadDim * Ln(RopeBase));
        CosV := Cos(Pos * Freq);
        SinV := Sin(Pos * Freq);
        HFRot[i] := HFVec[i] * CosV - HFVec[i + Half] * SinV;
        HFRot[i + Half] := HFVec[i + Half] * CosV + HFVec[i] * SinV;
      end;
      for i := 0 to Half - 1 do
      begin
        AssertEquals('rotate_half pos=' + IntToStr(Pos) + ' k=' + IntToStr(i),
          HFRot[i], Output.FData[Pos * HeadDim + 2 * i], 1e-5);
        AssertEquals('rotate_half pos=' + IntToStr(Pos) + ' k+half=' +
          IntToStr(i), HFRot[i + Half],
          Output.FData[Pos * HeadDim + 2 * i + 1], 1e-5);
      end;
    end;
  finally
    Output.Free;
    Input.Free;
    NN.Free;
  end;
end;

// TNNetSwiGLU computes FIRSTHALF * Swish(SECONDHALF); the Llama importer
// therefore loads up_proj into the first depth half and gate_proj into the
// second. This test checks the layer against hand-computed
// silu(gate) * up on a (SeqLen=2, 1, 2*I) tensor packed [up | gate].
procedure TTestNeuralPretrained.TestSwiGLUMatchesLlamaMLPGating;
const
  Inter = 3;
  SeqLen = 2;
var
  NN: TNNet;
  Input, Output: TNNetVolume;
  UpV, GateV, Expected: double;
  t, i: integer;
begin
  RandSeed := 424242;
  NN := TNNet.Create();
  NN.AddLayer( TNNetInput.Create(SeqLen, 1, 2 * Inter) );
  NN.AddLayer( TNNetSwiGLU.Create() );
  Input := TNNetVolume.Create(SeqLen, 1, 2 * Inter);
  Output := TNNetVolume.Create;
  try
    for i := 0 to Input.Size - 1 do
      Input.FData[i] := Sin(i * 1.3) * 1.5 - 0.2;
    NN.Compute(Input);
    NN.GetOutput(Output);
    AssertEquals('SwiGLU output size', SeqLen * Inter, Output.Size);
    for t := 0 to SeqLen - 1 do
      for i := 0 to Inter - 1 do
      begin
        UpV := Input.FData[t * 2 * Inter + i];              // first half
        GateV := Input.FData[t * 2 * Inter + Inter + i];    // second half
        Expected := UpV * (GateV / (1 + Exp(-GateV)));      // up * silu(gate)
        AssertEquals('SwiGLU t=' + IntToStr(t) + ' i=' + IntToStr(i),
          Expected, Output.FData[t * Inter + i], 1e-5);
      end;
  finally
    Output.Free;
    Input.Free;
    NN.Free;
  end;
end;

procedure TTestNeuralPretrained.TestLlamaConfigFromJSONFile;
var
  Config: TLlamaConfig;
begin
  RandSeed := 424242;
  Config := ReadLlamaConfigFromJSONFile(FixturePath('tiny_llama_config.json'));
  AssertEquals('hidden_size', 8, Config.HiddenSize);
  AssertEquals('intermediate_size', 12, Config.IntermediateSize);
  AssertEquals('num_hidden_layers', 2, Config.NumLayers);
  AssertEquals('num_attention_heads', 2, Config.NumHeads);
  AssertEquals('num_key_value_heads', 1, Config.NumKVHeads);
  AssertEquals('vocab_size', 11, Config.VocabSize);
  AssertEquals('max_position_embeddings', 16, Config.MaxPositions);
  AssertEquals('rms_norm_eps', 1e-5, Config.RmsNormEps, 1e-9);
  AssertEquals('rope_theta', 10000.0, Config.RopeTheta, 1e-3);
  AssertFalse('tie_word_embeddings', Config.TieWordEmbeddings);
end;

procedure TTestNeuralPretrained.TestLlamaImporterFailsOnMissingTensor;
var
  Path: string;
  NN: TNNet;
  Config: TLlamaConfig;
  Failed: boolean;
  Payload: array of byte;
  i: integer;
begin
  RandSeed := 424242;
  // A "checkpoint" containing ONLY model.embed_tokens.weight [4, 4]: the
  // importer must fail loudly on the first missing block tensor, not
  // import partially.
  SetLength(Payload, 4 * 4 * 4);
  for i := 0 to High(Payload) do Payload[i] := 0;
  Path := WriteTempSafeTensors(
    '{"model.embed_tokens.weight":{"dtype":"F32","shape":[4,4],' +
    '"data_offsets":[0,64]}}', Payload);
  Config.HiddenSize := 4;
  Config.IntermediateSize := 6;
  Config.NumLayers := 1;
  Config.NumHeads := 2;
  Config.NumKVHeads := 1;
  Config.VocabSize := 4;
  Config.MaxPositions := 8;
  Config.RmsNormEps := 1e-6;
  Config.RopeTheta := 10000;
  Config.TieWordEmbeddings := true;
  Config.ModelType := 'llama';
  Config.SlidingWindow := 0;
  Config.QKVBias := false;
  Config.Prefix := '';
  Failed := false;
  NN := nil;
  try
    try
      NN := BuildLlamaFromSafeTensorsWithConfig(Path, Config);
    except
      on EPretrainedImportError do Failed := true;
    end;
  finally
    NN.Free;
    DeleteFile(Path);
  end;
  AssertTrue('missing block tensors must abort the import', Failed);
end;

// The flagship Llama test: imports the committed tiny random Llama-shaped
// checkpoint and asserts logit parity with the independent pure-Python
// oracle (tools/llama_tiny_fixture.py, verified to match HF transformers'
// LlamaForCausalLM to ~9e-7). Covers the rotate_half row permutation, GQA
// head sharing, per-token RMSNorm, SwiGLU mapping and the untied LM head.
procedure TTestNeuralPretrained.TestLlamaLogitParity;
var
  NN: TNNet;
  Config: TLlamaConfig;
  RefRoot: TJSONData;
  Sequences, SeqArr, LogitsArr, PosArr, RowArr: TJSONArray;
  Input, Output: TNNetVolume;
  RefJson: TStringList;
  SeqCnt, PosCnt, TokCnt: integer;
  Diff, MaxDiff: double;
  SeqLen, Vocab: integer;
begin
  RandSeed := 424242;
  NN := BuildLlamaFromSafeTensorsEx(FixturePath('tiny_llama.safetensors'),
    Config, {SeqLen=}0, {pInferenceOnly=}false,
    FixturePath('tiny_llama_config.json'));
  RefJson := TStringList.Create;
  Input := TNNetVolume.Create;
  Output := TNNetVolume.Create;
  RefRoot := nil;
  try
    AssertEquals('layers', 2, Config.NumLayers);
    AssertEquals('prefix', 'model.', Config.Prefix);
    SeqLen := Config.MaxPositions;
    Vocab := Config.VocabSize;
    RefJson.LoadFromFile(FixturePath('tiny_llama_logits.json'));
    RefRoot := GetJSON(RefJson.Text);
    Sequences := TJSONArray(TJSONObject(RefRoot).Find('sequences'));
    LogitsArr := TJSONArray(TJSONObject(RefRoot).Find('logits'));
    AssertTrue('sequences present', Sequences <> nil);
    AssertTrue('logits present', LogitsArr <> nil);
    AssertTrue('at least 3 sequences', Sequences.Count >= 3);
    MaxDiff := 0;
    Input.ReSize(SeqLen, 1, 1);
    for SeqCnt := 0 to Sequences.Count - 1 do
    begin
      SeqArr := TJSONArray(Sequences.Items[SeqCnt]);
      AssertEquals('sequence length', SeqLen, SeqArr.Count);
      for PosCnt := 0 to SeqLen - 1 do
        Input.FData[PosCnt] := SeqArr.Items[PosCnt].AsInteger;
      NN.Compute(Input);
      NN.GetOutput(Output);
      AssertEquals('output size', SeqLen * Vocab, Output.Size);
      PosArr := TJSONArray(LogitsArr.Items[SeqCnt]);
      for PosCnt := 0 to SeqLen - 1 do
      begin
        RowArr := TJSONArray(PosArr.Items[PosCnt]);
        for TokCnt := 0 to Vocab - 1 do
        begin
          Diff := Abs(Output.FData[PosCnt * Vocab + TokCnt] -
            RowArr.Items[TokCnt].AsFloat);
          if Diff > MaxDiff then MaxDiff := Diff;
        end;
      end;
    end;
    // f32 end-to-end vs the float64 Python oracle on f32-rounded weights.
    // NEVER loosen the gate past 1e-3 - if parity breaks, fix the model,
    // don't widen the tolerance.
    AssertTrue('Llama logit parity: max |diff| = ' +
      FloatToStr(MaxDiff) + ' must be < 1e-4', MaxDiff < 1e-4);
  finally
    RefRoot.Free;
    Output.Free;
    Input.Free;
    RefJson.Free;
    NN.Free;
  end;
end;

// Reader-level sharded-checkpoint coverage: tiny_llama.safetensors.index.json
// (generated by tools/shard_tiny_llama_fixture.py) splits the tiny Llama
// fixture into 2 shards. The sharded reader must expose exactly the same
// tensor set, dtypes, shapes and bytes as the single-file reader.
procedure TTestNeuralPretrained.TestShardedReaderMatchesSingleFile;
var
  Single1, Sharded: TNNetSafeTensorsReader;
  V1, V2: TNNetVolume;
  i, j: integer;
  TName: string;
begin
  RandSeed := 424242;
  Single1 := TNNetSafeTensorsReader.Create(
    FixturePath('tiny_llama.safetensors'));
  Sharded := TNNetSafeTensorsReader.Create(
    FixturePath('tiny_llama.safetensors.index.json'));
  V1 := TNNetVolume.Create;
  V2 := TNNetVolume.Create;
  try
    AssertEquals('single-file shard count', 1, Single1.ShardCount);
    AssertEquals('sharded shard count', 2, Sharded.ShardCount);
    AssertEquals('tensor count', Single1.Count, Sharded.Count);
    for i := 0 to Single1.Count - 1 do
    begin
      TName := Single1.TensorName(i);
      AssertTrue('sharded has ' + TName, Sharded.HasTensor(TName));
      AssertEquals('dtype of ' + TName, Single1.GetDType(TName),
        Sharded.GetDType(TName));
      AssertEquals('shape of ' + TName, Single1.ShapeAsString(TName),
        Sharded.ShapeAsString(TName));
      Single1.LoadTensorFlat(TName, V1);
      Sharded.LoadTensorFlat(TName, V2);
      AssertEquals('size of ' + TName, V1.Size, V2.Size);
      for j := 0 to V1.Size - 1 do
        if V1.FData[j] <> V2.FData[j] then
          Fail('tensor ' + TName + ' differs at element ' + IntToStr(j));
    end;
  finally
    V2.Free;
    V1.Free;
    Sharded.Free;
    Single1.Free;
  end;
end;

// End-to-end sharded import: BuildLlamaFromSafeTensorsEx pointed at the
// 2-shard index.json (NO importer changes - the reader handles sharding
// transparently) must produce logits BIT-IDENTICAL to the single-file load,
// and both must keep parity with the pinned Python oracle logits.
procedure TTestNeuralPretrained.TestShardedLlamaLogitsBitIdentical;
var
  NNSingle, NNSharded: TNNet;
  ConfigSingle, ConfigSharded: TLlamaConfig;
  Input, OutSingle, OutSharded: TNNetVolume;
  i: integer;
begin
  RandSeed := 424242;
  NNSingle := BuildLlamaFromSafeTensorsEx(
    FixturePath('tiny_llama.safetensors'), ConfigSingle, {SeqLen=}0,
    {pInferenceOnly=}false, FixturePath('tiny_llama_config.json'));
  NNSharded := BuildLlamaFromSafeTensorsEx(
    FixturePath('tiny_llama.safetensors.index.json'), ConfigSharded,
    {SeqLen=}0, {pInferenceOnly=}false,
    FixturePath('tiny_llama_config.json'));
  Input := TNNetVolume.Create(ConfigSingle.MaxPositions, 1, 1);
  OutSingle := TNNetVolume.Create;
  OutSharded := TNNetVolume.Create;
  try
    AssertEquals('layers', ConfigSingle.NumLayers, ConfigSharded.NumLayers);
    AssertEquals('prefix', 'model.', ConfigSharded.Prefix);
    for i := 0 to ConfigSingle.MaxPositions - 1 do
      Input.FData[i] := (i * 5 + 2) mod ConfigSingle.VocabSize;
    NNSingle.Compute(Input);
    NNSingle.GetOutput(OutSingle);
    NNSharded.Compute(Input);
    NNSharded.GetOutput(OutSharded);
    AssertEquals('output size', OutSingle.Size, OutSharded.Size);
    for i := 0 to OutSingle.Size - 1 do
      AssertEquals('sharded vs single-file logit ' + IntToStr(i),
        OutSingle.FData[i], OutSharded.FData[i], 0); // BIT-identical
    // The sharded import must also keep oracle parity on its own.
    AssertLogitParityWithFixture(NNSharded,
      FixturePath('tiny_llama_logits.json'), ConfigSharded.MaxPositions,
      ConfigSharded.VocabSize);
  finally
    OutSharded.Free;
    OutSingle.Free;
    Input.Free;
    NNSharded.Free;
    NNSingle.Free;
  end;
end;

// Verifies the distilbert/distilgpt2 import target on REAL pretrained
// weights: tests/fixtures/tiny_distilgpt2.safetensors is a dimension-sliced
// sub-slab of the genuine distilgpt2 checkpoint (2 of 6 layers, 2 heads x 4
// dims, d_model 8, vocab 12, "transformer." tensor prefix - see
// examples/GPT2Import/make_pico_gpt2_fixture.py) and the reference logits
// come from HF transformers' GPT2LMHeadModel in float64 on the same slice.
// The full distilgpt2 loads with BuildGPT2FromSafeTensors unchanged
// (2026-06: 2-layer/8192-vocab real-weight slice max |logit diff| 4.2e-5
// vs transformers; the n_head = n_embd/64 rule holds - 768 -> 12 heads).
procedure TTestNeuralPretrained.TestDistilGPT2LogitParity;
var
  NN: TNNet;
  Config: TGPT2Config;
begin
  RandSeed := 424242;
  NN := BuildGPT2FromSafeTensorsEx(
    FixturePath('tiny_distilgpt2.safetensors'), Config, {SeqLen=}0,
    {NumHeads=}2);
  try
    AssertEquals('n_layer', 2, Config.NLayers);
    AssertEquals('n_embd', 8, Config.NEmbd);
    AssertEquals('n_ctx', 16, Config.NCtx);
    AssertEquals('vocab', 12, Config.VocabSize);
    AssertEquals('prefix', 'transformer.', Config.Prefix);
    AssertLogitParityWithFixture(NN,
      FixturePath('tiny_distilgpt2_logits.json'), Config.NCtx,
      Config.VocabSize);
  finally
    NN.Free;
  end;
end;

// Verifies the HuggingFaceTB/SmolLM2-135M import target on REAL pretrained
// weights: tests/fixtures/tiny_smollm2.safetensors is a dimension-sliced
// sub-slab of the genuine SmolLM2-135M checkpoint (2 of 30 layers, 2 query
// heads sharing 1 kv head x 4 dims, hidden 8, vocab 12 - see
// examples/LlamaImport/make_pico_llama_fixture.py) and the reference logits
// come from HF transformers' LlamaForCausalLM in float64 on the same slice.
// Distinctive coverage vs TestLlamaLogitParity: TIED embeddings (no
// lm_head tensor in the checkpoint), rope_theta=100000 and a BF16-dtype
// fixture (end-to-end DecodeBF16). The full SmolLM2-135M loads with
// BuildLlamaFromSafeTensors unchanged (2026-06: 2-layer/4096-vocab
// real-weight slice max |logit diff| 6.5e-5 vs transformers).
procedure TTestNeuralPretrained.TestSmolLM2LogitParity;
var
  NN: TNNet;
  Config: TLlamaConfig;
begin
  RandSeed := 424242;
  NN := BuildLlamaFromSafeTensorsEx(FixturePath('tiny_smollm2.safetensors'),
    Config, {SeqLen=}0, {pInferenceOnly=}false,
    FixturePath('tiny_smollm2_config.json'));
  try
    AssertEquals('layers', 2, Config.NumLayers);
    AssertEquals('heads', 2, Config.NumHeads);
    AssertEquals('kv_heads', 1, Config.NumKVHeads);
    AssertEquals('vocab', 12, Config.VocabSize);
    AssertEquals('rope_theta', 100000.0, Config.RopeTheta, 1e-3);
    AssertTrue('tie_word_embeddings', Config.TieWordEmbeddings);
    AssertEquals('prefix', 'model.', Config.Prefix);
    AssertLogitParityWithFixture(NN,
      FixturePath('tiny_smollm2_logits.json'), Config.MaxPositions,
      Config.VocabSize);
  finally
    NN.Free;
  end;
end;

// Verifies the Mistral import target: tests/fixtures/tiny_mistral.* is a
// pico randomly-initialized HF MistralForCausalLM (2 layers, 2 query heads
// sharing 1 kv head x 4 dims, hidden 8, vocab 11, untied lm_head) with
// sliding_window=4 SMALLER than the 16-token test sequences, so the
// sliding-window mask is genuinely exercised (the generator
// tools/mistral_qwen2_tiny_fixture.py asserts the windowed logits differ
// from full attention by ~1e-2 on the same weights). Reference logits come
// from HF transformers in float64.
procedure TTestNeuralPretrained.TestMistralLogitParity;
var
  NN: TNNet;
  Config: TLlamaConfig;
begin
  RandSeed := 424242;
  NN := BuildMistralFromSafeTensorsEx(FixturePath('tiny_mistral.safetensors'),
    Config, {SeqLen=}0, {pInferenceOnly=}false,
    FixturePath('tiny_mistral_config.json'));
  try
    AssertEquals('model_type', 'mistral', Config.ModelType);
    AssertEquals('layers', 2, Config.NumLayers);
    AssertEquals('heads', 2, Config.NumHeads);
    AssertEquals('kv_heads', 1, Config.NumKVHeads);
    AssertEquals('vocab', 11, Config.VocabSize);
    AssertEquals('sliding_window', 4, Config.SlidingWindow);
    AssertFalse('qkv_bias', Config.QKVBias);
    AssertEquals('prefix', 'model.', Config.Prefix);
    AssertLogitParityWithFixture(NN,
      FixturePath('tiny_mistral_logits.json'), Config.MaxPositions,
      Config.VocabSize);
  finally
    NN.Free;
  end;
end;

// Verifies the Qwen2 import target: tests/fixtures/tiny_qwen2.* is a pico
// randomly-initialized HF Qwen2ForCausalLM (2 layers, 2 query heads sharing
// 1 kv head x 4 dims, hidden 8, vocab 12, untied lm_head) whose q/k/v
// projection biases were re-randomized to NONZERO values (HF zero-inits
// them; the generator asserts zeroing the biases changes the logits by
// ~0.15), so the bias-loading path - including the rotate_half permutation
// of the q/k biases - is genuinely exercised. Reference logits come from
// HF transformers in float64.
procedure TTestNeuralPretrained.TestQwen2LogitParity;
var
  NN: TNNet;
  Config: TLlamaConfig;
begin
  RandSeed := 424242;
  NN := BuildQwen2FromSafeTensorsEx(FixturePath('tiny_qwen2.safetensors'),
    Config, {SeqLen=}0, {pInferenceOnly=}false,
    FixturePath('tiny_qwen2_config.json'));
  try
    AssertEquals('model_type', 'qwen2', Config.ModelType);
    AssertEquals('layers', 2, Config.NumLayers);
    AssertEquals('heads', 2, Config.NumHeads);
    AssertEquals('kv_heads', 1, Config.NumKVHeads);
    AssertEquals('vocab', 12, Config.VocabSize);
    AssertEquals('sliding_window', 0, Config.SlidingWindow);
    AssertTrue('qkv_bias', Config.QKVBias);
    AssertEquals('prefix', 'model.', Config.Prefix);
    AssertLogitParityWithFixture(NN,
      FixturePath('tiny_qwen2_logits.json'), Config.MaxPositions,
      Config.VocabSize);
  finally
    NN.Free;
  end;
end;

// BuildFromPretrained must route on config.json's model_type:
//   - gpt2 via a HF-style checkpoint DIRECTORY (config.json +
//     model.safetensors; n_head read from the config),
//   - mistral via a directory,
//   - llama and qwen2 via an explicit .safetensors file + config path.
// Each route must reproduce the family's pinned oracle logits, proving the
// dispatch reached the correct builder with the correct config.
procedure TTestNeuralPretrained.TestBuildFromPretrainedDispatch;
var
  NN: TNNet;
  Dir: string;
  ConfigJson: TStringList;
begin
  RandSeed := 424242;
  // ---- gpt2 through the directory route ----
  Dir := IncludeTrailingPathDelimiter(GetTempDir(false)) +
    'cai_bfp_gpt2_' + IntToStr(Random(1000000)) + DirectorySeparator;
  ForceDirectories(Dir);
  ConfigJson := TStringList.Create;
  try
    CopyFileTo(FixturePath('tiny_gpt2.safetensors'),
      Dir + 'model.safetensors');
    ConfigJson.Text := '{"model_type": "gpt2", "n_head": 2}';
    ConfigJson.SaveToFile(Dir + 'config.json');
    NN := BuildFromPretrained(Dir);
    try
      AssertLogitParityWithFixture(NN, FixturePath('tiny_gpt2_logits.json'),
        16, 11);
    finally
      NN.Free;
    end;
    // ---- mistral through the directory route ----
    CopyFileTo(FixturePath('tiny_mistral.safetensors'),
      Dir + 'model.safetensors');
    CopyFileTo(FixturePath('tiny_mistral_config.json'), Dir + 'config.json');
    NN := BuildFromPretrained(Dir);
    try
      AssertLogitParityWithFixture(NN,
        FixturePath('tiny_mistral_logits.json'), 16, 11);
    finally
      NN.Free;
    end;
  finally
    ConfigJson.Free;
    DeleteFile(Dir + 'model.safetensors');
    DeleteFile(Dir + 'config.json');
    RemoveDir(Dir);
  end;
  // ---- llama through the file route (explicit config path) ----
  NN := BuildFromPretrained(FixturePath('tiny_llama.safetensors'), 0, false,
    FixturePath('tiny_llama_config.json'));
  try
    AssertLogitParityWithFixture(NN, FixturePath('tiny_llama_logits.json'),
      16, 11);
  finally
    NN.Free;
  end;
  // ---- qwen2 through the file route ----
  NN := BuildFromPretrained(FixturePath('tiny_qwen2.safetensors'), 0, false,
    FixturePath('tiny_qwen2_config.json'));
  try
    AssertLogitParityWithFixture(NN, FixturePath('tiny_qwen2_logits.json'),
      16, 12);
  finally
    NN.Free;
  end;
end;

// An unsupported model_type must raise EPretrainedImportError with a
// message that NAMES the offending type and LISTS the supported ones.
procedure TTestNeuralPretrained.TestBuildFromPretrainedRejectsUnsupportedModelType;
var
  NN: TNNet;
  ConfigPath, Msg: string;
  ConfigJson: TStringList;
  Failed: boolean;
begin
  RandSeed := 424242;
  ConfigPath := IncludeTrailingPathDelimiter(GetTempDir(false)) +
    'cai_bfp_t5_config_' + IntToStr(Random(1000000)) + '.json';
  ConfigJson := TStringList.Create;
  NN := nil;
  Msg := '';
  Failed := false;
  try
    ConfigJson.Text := '{"model_type": "t5"}';
    ConfigJson.SaveToFile(ConfigPath);
    try
      NN := BuildFromPretrained(FixturePath('tiny_llama.safetensors'), 0,
        false, ConfigPath);
    except
      on E: EPretrainedImportError do
      begin
        Failed := true;
        Msg := E.Message;
      end;
    end;
  finally
    NN.Free;
    ConfigJson.Free;
    DeleteFile(ConfigPath);
  end;
  AssertTrue('unsupported model_type must raise', Failed);
  AssertTrue('error names the offending type: ' + Msg,
    Pos('"t5"', Msg) > 0);
  AssertTrue('error lists the supported types: ' + Msg,
    (Pos('gpt2', Msg) > 0) and (Pos('llama', Msg) > 0) and
    (Pos('mistral', Msg) > 0) and (Pos('qwen2', Msg) > 0));
end;

initialization
  RegisterTest(TTestNeuralPretrained);
end.
