unit TestNeuralHFTokenizer;
// Tests for the HuggingFace tokenizer.json loader (neuralhftokenizer.pas).
//
// The flagship tests are the parity batteries: tests/fixtures contains two
// tiny-but-realistic tokenizer.json files (a GPT-2-style byte-level BPE and
// a Llama-style metaspace BPE with byte fallback) plus
// hf_tokenizer_cases.json, all generated against the real HuggingFace
// `tokenizers` library by tools/hf_tokenizer_fixture.py. For every pinned
// case the Pascal Encode must reproduce HF's ids EXACTLY and Decode must
// reproduce HF's decoded string EXACTLY (ASCII, punctuation, contractions,
// multi-space, tabs/newlines, UTF-8 accents, emoji and special tokens are
// all covered).
//
// This unit is coded by Claude (AI).
{$mode objfpc}{$H+}

interface

uses
  Classes, SysUtils, fpcunit, testregistry, fpjson, jsonparser,
  neuralvolume, neuralhftokenizer, neuralchat;

type
  TTestNeuralHFTokenizer = class(TTestCase)
  private
    function FixturePath(const FileName: string): string;
    procedure RunParityBattery(const GroupName: string);
  published
    procedure TestByteLevelParityWithHF;
    procedure TestMetaspaceParityWithHF;
    procedure TestWordPieceParityWithHF;
    procedure TestUnigramParityWithHF;
    procedure TestUnigramSegmentationAndFusedUnk;
    procedure TestSplitQwen2ParityWithHF;
    procedure TestSplitCl100kParityWithHF;
    procedure TestMetaspacePreTokenizerParityWithHF;
    procedure TestRejectsUnknownSplitPattern;
    procedure TestWordPieceSpecialTokenIds;
    procedure TestByteLevelSpecialTokenIds;
    procedure TestMetaspaceSpecialTokenIds;
    procedure TestDecodeKeepsSpecialsWhenAsked;
    procedure TestRejectsNonBPEModel;
    procedure TestEncodeIntegerArrayHelper;
    procedure TestOffsetMappingRoundTrip;
    procedure TestOffsetMappingWordIds;
    // BPE-dropout (Provilkov et al. 2020): p=0 is bit-identical to eval;
    // p=1 is the maximally-split per-byte tokenization; a seeded mid-value
    // run is deterministic and differs from p=0.
    procedure TestDropoutZeroIsBitIdentical;
    procedure TestDropoutOneIsMaximallySplit;
    procedure TestDropoutSeededIsDeterministicAndDiffers;
  end;

  // Tests for the chat templates in neuralchat.pas. The flagship tests
  // are the parity batteries: tests/fixtures/chat_template_cases.json
  // pins, for every (format x conversation) pair, the EXACT string the
  // authentic published chat_template Jinja renders through the
  // transformers apply_chat_template environment (generated by
  // tools/chat_template_fixture.py); ApplyChatTemplate must reproduce it
  // byte for byte, and the pinned raise cases must raise
  // ENeuralChatError.
  // This class is coded by Claude (AI).
  TTestNeuralChat = class(TTestCase)
  private
    function FixturePath(const FileName: string): string;
    procedure RunChatBattery(const FormatName: string);
  published
    procedure TestChatMLParityWithJinja;
    procedure TestLlama2ParityWithJinja;
    procedure TestLlama3ParityWithJinja;
    procedure TestZephyrParityWithJinja;
    procedure TestGemmaParityWithJinja;
    procedure TestPhi3ParityWithJinja;
    procedure TestMistralParityWithJinja;
    procedure TestDetectFormatOnAuthenticTemplates;
    procedure TestFormatNameRoundTrip;
    procedure TestEncodeChatLlama2SpecialTokens;
    procedure TestEncodeChatChatMLAddedToken;
    procedure TestLoadChatTemplateFromTokenizerConfig;
    procedure TestUnknownFormatRaises;
  end;

implementation

function TTestNeuralHFTokenizer.FixturePath(const FileName: string): string;
begin
  Result := 'fixtures' + DirectorySeparator + FileName;
  if not FileExists(Result) then
    Result := 'tests' + DirectorySeparator + 'fixtures' + DirectorySeparator +
      FileName;
  if not FileExists(Result) then
    Fail('Fixture not found: ' + FileName +
      ' (run python3 tools/hf_tokenizer_fixture.py from the repo root).');
end;

// Loads the tokenizer named by hf_tokenizer_cases.json[GroupName] and
// asserts exact Encode-id and Decode-string parity for every pinned case.
procedure TTestNeuralHFTokenizer.RunParityBattery(const GroupName: string);
var
  Tok: TNeuralHFTokenizer;
  Root: TJSONData;
  Group, CaseObj: TJSONObject;
  Cases, ExpectedIds: TJSONArray;
  Ids: TIntegerList;
  CaseCnt, IdCnt: integer;
  Text, Context: string;
  FS: TFileStream;
begin
  FS := TFileStream.Create(FixturePath('hf_tokenizer_cases.json'),
    fmOpenRead or fmShareDenyWrite);
  try
    Root := GetJSON(FS);
  finally
    FS.Free;
  end;
  Tok := TNeuralHFTokenizer.Create();
  Ids := TIntegerList.Create();
  try
    Group := TJSONObject(Root).Objects[GroupName];
    Tok.LoadFromFile(FixturePath(Group.Get('tokenizer', '')));
    AssertTrue(GroupName + ': vocab not loaded', Tok.GetVocabSize() > 10);
    Cases := Group.Arrays['cases'];
    AssertTrue(GroupName + ': no cases pinned', Cases.Count >= 10);
    for CaseCnt := 0 to Cases.Count - 1 do
    begin
      CaseObj := Cases.Objects[CaseCnt];
      Text := CaseObj.Get('text', '');
      ExpectedIds := CaseObj.Arrays['ids'];
      Context := GroupName + ' case ' + IntToStr(CaseCnt) + ' "' + Text + '"';
      Ids.Clear;
      Tok.Encode(Text, Ids);
      AssertEquals(Context + ': id count', ExpectedIds.Count, Ids.Count);
      for IdCnt := 0 to ExpectedIds.Count - 1 do
        AssertEquals(Context + ': id[' + IntToStr(IdCnt) + ']',
          ExpectedIds.Integers[IdCnt], Ids[IdCnt]);
      AssertEquals(Context + ': decode',
        CaseObj.Get('decoded', ''), Tok.Decode(Ids, true));
    end;
  finally
    Ids.Free;
    Tok.Free;
    Root.Free;
  end;
end;

procedure TTestNeuralHFTokenizer.TestByteLevelParityWithHF;
begin
  RunParityBattery('byte_level');
end;

procedure TTestNeuralHFTokenizer.TestMetaspaceParityWithHF;
begin
  RunParityBattery('metaspace');
end;

procedure TTestNeuralHFTokenizer.TestWordPieceParityWithHF;
begin
  RunParityBattery('wordpiece');
end;

// SentencePiece-Unigram (ALBERT/T5/XLNet/DeBERTa-v3 family): Viterbi
// segmentation over the [piece, log_prob] vocab + Metaspace pre_tokenizer.
procedure TTestNeuralHFTokenizer.TestUnigramParityWithHF;
begin
  RunParityBattery('unigram');
end;

// Targeted Unigram checks: the IsUnigram flag, a known multi-character
// Viterbi segmentation, and that a run of out-of-vocab characters between
// known pieces collapses to a SINGLE fused <unk> id (HF behavior).
procedure TTestNeuralHFTokenizer.TestUnigramSegmentationAndFusedUnk;
var
  Tok: TNeuralHFTokenizer;
  Ids: TIntegerList;
  UnkCount, Cnt: integer;
begin
  Tok := TNeuralHFTokenizer.Create();
  Ids := TIntegerList.Create();
  try
    Tok.LoadFromFile(FixturePath('tiny_unigram_tokenizer.json'));
    AssertTrue('unigram flag', Tok.IsUnigram);
    AssertTrue('not byte-level', not Tok.IsByteLevel);
    AssertTrue('not wordpiece', not Tok.IsWordPiece);
    AssertTrue('unk id present', Tok.UnkId >= 0);
    AssertTrue('vocab loaded', Tok.GetVocabSize() > 10);

    // "the" is a single multi-char vocab piece; the metaspace prefix makes
    // it "▁the" -> the highest-score segmentation is a single id.
    Ids.Clear;
    Tok.Encode('the', Ids);
    AssertEquals('"the" decodes back', 'the', Tok.Decode(Ids, true));

    // A run of three unknown capitals (Q,X,Z) between known pieces must
    // produce exactly ONE fused <unk>.
    Ids.Clear;
    Tok.Encode('the QXZ cat', Ids);
    UnkCount := 0;
    for Cnt := 0 to Ids.Count - 1 do
      if Ids[Cnt] = Tok.UnkId then Inc(UnkCount);
    AssertEquals('the QXZ run fuses to one unk', 1, UnkCount);
  finally
    Ids.Free;
    Tok.Free;
  end;
end;

// Qwen2/Qwen3-style Sequence[Split(cl100k-style regex with \p{N}),
// ByteLevel(use_regex=false)] pre-tokenizer (fixtures generated by
// tools/hf_pretok_fixture.py).
procedure TTestNeuralHFTokenizer.TestSplitQwen2ParityWithHF;
begin
  RunParityBattery('split_qwen2');
end;

// Llama-3/cl100k-style Split pattern (digit runs capped at 3).
procedure TTestNeuralHFTokenizer.TestSplitCl100kParityWithHF;
begin
  RunParityBattery('split_cl100k');
end;

// Mistral / legacy=false Llama style Metaspace PRE_TOKENIZER
// (prepend_scheme=first, split=true) with the Metaspace decoder.
procedure TTestNeuralHFTokenizer.TestMetaspacePreTokenizerParityWithHF;
begin
  RunParityBattery('metaspace_pretok');
end;

// A Split pre_tokenizer whose pattern is not one of the recognized
// cl100k-family literals must raise (no regex engine is vendored).
procedure TTestNeuralHFTokenizer.TestRejectsUnknownSplitPattern;
var
  Tok: TNeuralHFTokenizer;
  TempFile: string;
  SL: TStringList;
  Raised: boolean;
begin
  TempFile := GetTempDir(true) + 'unknown_split_tokenizer.json';
  SL := TStringList.Create();
  Tok := TNeuralHFTokenizer.Create();
  try
    SL.Text := '{"model": {"type": "BPE", "vocab": {"a": 0}, "merges": []},'
      + ' "pre_tokenizer": {"type": "Split", "pattern":'
      + ' {"Regex": "[a-z]+"}, "behavior": "Isolated", "invert": false}}';
    SL.SaveToFile(TempFile);
    Raised := false;
    try
      Tok.LoadFromFile(TempFile);
    except
      on E: EHFTokenizerError do Raised := true;
    end;
    AssertTrue('unknown Split pattern must raise EHFTokenizerError', Raised);
  finally
    Tok.Free;
    SL.Free;
    DeleteFile(TempFile);
  end;
end;

// The WordPiece (BERT-family) fixture: [PAD]/[UNK]/[CLS]/[SEP]/[MASK]
// specials, no BOS/EOS convention. BERT callers fetch [CLS]/[SEP] via
// TokenToId (BertTokenizeSentence in neuralpretrained.pas).
procedure TTestNeuralHFTokenizer.TestWordPieceSpecialTokenIds;
var
  Tok: TNeuralHFTokenizer;
begin
  Tok := TNeuralHFTokenizer.Create();
  try
    Tok.LoadFromFile(FixturePath('tiny_wordpiece_tokenizer.json'));
    AssertTrue('wordpiece flag', Tok.IsWordPiece);
    AssertTrue('not byte-level', not Tok.IsByteLevel);
    AssertEquals('pad', 0, Tok.TokenToId('[PAD]'));
    AssertEquals('unk', 1, Tok.UnkId);
    AssertEquals('cls', 2, Tok.TokenToId('[CLS]'));
    AssertEquals('sep', 3, Tok.TokenToId('[SEP]'));
    AssertEquals('mask', 4, Tok.TokenToId('[MASK]'));
  finally
    Tok.Free;
  end;
end;

procedure TTestNeuralHFTokenizer.TestByteLevelSpecialTokenIds;
var
  Tok: TNeuralHFTokenizer;
begin
  Tok := TNeuralHFTokenizer.Create();
  try
    Tok.LoadFromFile(FixturePath('tiny_bpe_bytelevel_tokenizer.json'));
    AssertTrue('byte-level flag', Tok.IsByteLevel);
    AssertEquals('eos = <|endoftext|>', 0, Tok.EosId);
    AssertEquals('bos doubles as eos in the GPT-2 family', 0, Tok.BosId);
    AssertEquals('no unk in byte-level BPE', -1, Tok.UnkId);
    AssertEquals('added token lookup', 0, Tok.TokenToId('<|endoftext|>'));
  finally
    Tok.Free;
  end;
end;

procedure TTestNeuralHFTokenizer.TestMetaspaceSpecialTokenIds;
var
  Tok: TNeuralHFTokenizer;
begin
  Tok := TNeuralHFTokenizer.Create();
  try
    Tok.LoadFromFile(FixturePath('tiny_bpe_metaspace_tokenizer.json'));
    AssertTrue('not byte-level', not Tok.IsByteLevel);
    AssertEquals('unk', 0, Tok.UnkId);
    AssertEquals('bos = <s>', 1, Tok.BosId);
    AssertEquals('eos = </s>', 2, Tok.EosId);
    AssertEquals('byte token in model vocab', 3, Tok.TokenToId('<0x00>'));
    AssertEquals('id->token round trip', '<0x00>', Tok.IdToToken(3));
  finally
    Tok.Free;
  end;
end;

procedure TTestNeuralHFTokenizer.TestDecodeKeepsSpecialsWhenAsked;
var
  Tok: TNeuralHFTokenizer;
  Ids: TIntegerList;
begin
  Tok := TNeuralHFTokenizer.Create();
  Ids := TIntegerList.Create();
  try
    Tok.LoadFromFile(FixturePath('tiny_bpe_metaspace_tokenizer.json'));
    Tok.Encode('<s>hello</s>', Ids);
    AssertTrue('specials matched in text', Ids.Count >= 3);
    AssertEquals('first id is BOS', Tok.BosId, Ids[0]);
    AssertEquals('last id is EOS', Tok.EosId, Ids[Ids.Count - 1]);
    AssertEquals('skip specials', 'hello', Tok.Decode(Ids, true));
    AssertEquals('keep specials', '<s> hello</s>', Tok.Decode(Ids, false));
  finally
    Ids.Free;
    Tok.Free;
  end;
end;

procedure TTestNeuralHFTokenizer.TestRejectsNonBPEModel;
var
  Tok: TNeuralHFTokenizer;
  TempFile: string;
  SL: TStringList;
  Raised: boolean;
begin
  // BPE, WordPiece and Unigram are supported; any other model.type must
  // still raise (e.g. a hypothetical/unknown model).
  TempFile := GetTempDir(true) + 'not_bpe_tokenizer.json';
  SL := TStringList.Create();
  Tok := TNeuralHFTokenizer.Create();
  try
    SL.Text := '{"model": {"type": "FancyNewModel", "vocab": {}}}';
    SL.SaveToFile(TempFile);
    Raised := false;
    try
      Tok.LoadFromFile(TempFile);
    except
      on E: EHFTokenizerError do Raised := true;
    end;
    AssertTrue('unknown model.type must raise EHFTokenizerError', Raised);
  finally
    Tok.Free;
    SL.Free;
    DeleteFile(TempFile);
  end;
end;

procedure TTestNeuralHFTokenizer.TestEncodeIntegerArrayHelper;
var
  Tok: TNeuralHFTokenizer;
  Arr: TNeuralIntegerArray;
begin
  Tok := TNeuralHFTokenizer.Create();
  try
    Tok.LoadFromFile(FixturePath('tiny_bpe_bytelevel_tokenizer.json'));
    Arr := Tok.Encode('the cat');
    AssertTrue('array helper returns ids', Length(Arr) > 0);
    AssertEquals('decode round-trips the array helper',
      'the cat', Tok.Decode(Arr, true));
  finally
    Tok.Free;
  end;
end;

procedure TTestNeuralHFTokenizer.TestOffsetMappingRoundTrip;
var
  Tok: TNeuralHFTokenizer;
  Offsets: TNeuralTokenOffsetArray;
  Text, Slice, Joined: string;
  I: integer;
begin
  // Byte-level path: every mapped token's (Start,Length) must slice back to a
  // non-empty substring, spans must be monotonic, and concatenating the mapped
  // surfaces in order must reproduce the input with whitespace removed.
  Tok := TNeuralHFTokenizer.Create();
  try
    Tok.LoadFromFile(FixturePath('tiny_bpe_bytelevel_tokenizer.json'));
    Text := 'the cat sat';
    Offsets := Tok.EncodeWithOffsets(Text);
    AssertTrue('byte-level offsets emitted', Length(Offsets) > 0);
    Joined := '';
    for I := 0 to High(Offsets) do
      if Offsets[I].Length > 0 then
      begin
        Slice := Copy(Text, Offsets[I].Start, Offsets[I].Length);
        AssertTrue('span ' + IntToStr(I) + ' nonempty slice', Slice <> '');
        if I > 0 then
          AssertTrue('monotonic start',
            Offsets[I].Start >= Offsets[I - 1].Start);
        Joined := Joined + Slice;
      end;
    AssertEquals('mapped surfaces reconstruct non-space input',
      StringReplace(Text, ' ', '', [rfReplaceAll]), Joined);
  finally
    Tok.Free;
  end;
  // WordPiece path: same invariants (surface stripped of '##').
  Tok := TNeuralHFTokenizer.Create();
  try
    Tok.LoadFromFile(FixturePath('tiny_wordpiece_tokenizer.json'));
    Text := 'the cat';
    Offsets := Tok.EncodeWithOffsets(Text);
    AssertTrue('wordpiece offsets emitted', Length(Offsets) > 0);
    for I := 0 to High(Offsets) do
      if Offsets[I].Length > 0 then
        AssertTrue('wp span ' + IntToStr(I) + ' in bounds',
          (Offsets[I].Start >= 1) and
          (Offsets[I].Start + Offsets[I].Length - 1 <= Length(Text)));
  finally
    Tok.Free;
  end;
end;

procedure TTestNeuralHFTokenizer.TestOffsetMappingWordIds;
var
  Tok: TNeuralHFTokenizer;
  Offsets: TNeuralTokenOffsetArray;
  Text: string;
  I, MaxWord: integer;
begin
  // Three whitespace words -> word ids must be 0,1,2 in non-decreasing order;
  // a subword of word k carries WordId = k (subword -> word alignment).
  Tok := TNeuralHFTokenizer.Create();
  try
    Tok.LoadFromFile(FixturePath('tiny_bpe_bytelevel_tokenizer.json'));
    Text := 'the cat sat';
    Offsets := Tok.EncodeWithOffsets(Text);
    MaxWord := -1;
    for I := 0 to High(Offsets) do
      if Offsets[I].WordId >= 0 then
      begin
        AssertTrue('word ids non-decreasing',
          Offsets[I].WordId >= MaxWord);
        MaxWord := Offsets[I].WordId;
      end;
    AssertEquals('three whitespace words -> max word id 2', 2, MaxWord);
  finally
    Tok.Free;
  end;
end;

// p=0 (default) must reproduce the deterministic byte-level BPE ids exactly
// (bit-identical to eval/inference; mirrors TestNeuralTokenizer).
procedure TTestNeuralHFTokenizer.TestDropoutZeroIsBitIdentical;
var
  Tok: TNeuralHFTokenizer;
  BaseLine, WithZero: TNeuralIntegerArray;
  I: integer;
begin
  Tok := TNeuralHFTokenizer.Create();
  try
    Tok.LoadFromFile(FixturePath('tiny_bpe_bytelevel_tokenizer.json'));
    AssertEquals('DropoutProb defaults to OFF', 0.0, Tok.DropoutProb, 0.0);
    BaseLine := Tok.Encode('the cat sat on the mat');
    Tok.DropoutProb := 0.0;
    RandSeed := 999; // must be irrelevant at p=0
    WithZero := Tok.Encode('the cat sat on the mat');
    AssertEquals('p=0 id count unchanged', Length(BaseLine), Length(WithZero));
    for I := 0 to High(BaseLine) do
      AssertEquals('p=0 id[' + IntToStr(I) + ']', BaseLine[I], WithZero[I]);
  finally
    Tok.Free;
  end;
end;

// p=1 drops EVERY merge, so the tokenization collapses to the per-byte
// alphabet tokens (the maximally-split segmentation), which still
// round-trips on decode.
procedure TTestNeuralHFTokenizer.TestDropoutOneIsMaximallySplit;
var
  Tok: TNeuralHFTokenizer;
  Ids: TNeuralIntegerArray;
  Text: string;
begin
  Tok := TNeuralHFTokenizer.Create();
  try
    Tok.LoadFromFile(FixturePath('tiny_bpe_bytelevel_tokenizer.json'));
    Text := 'the cat';
    Tok.DropoutProb := 1.0;
    RandSeed := 1;
    Ids := Tok.Encode(Text);
    // The maximally-split result is one id per UTF-8 byte of the text
    // (every byte maps to its byte-level alphabet token, no merge applied).
    AssertEquals('p=1 emits one id per input byte', Length(Text), Length(Ids));
    AssertEquals('p=1 still round-trips', Text, Tok.Decode(Ids, true));
  finally
    Tok.Free;
  end;
end;

// A seeded mid-value run is deterministic (same seed -> same ids) and
// differs from the p=0 deterministic segmentation.
procedure TTestNeuralHFTokenizer.TestDropoutSeededIsDeterministicAndDiffers;
var
  Tok: TNeuralHFTokenizer;
  Deterministic, RunA, RunB: TNeuralIntegerArray;
  Text: string;
  I: integer;
  Differs: boolean;
begin
  Tok := TNeuralHFTokenizer.Create();
  try
    Tok.LoadFromFile(FixturePath('tiny_bpe_bytelevel_tokenizer.json'));
    Text := 'the cat sat on the mat';
    Deterministic := Tok.Encode(Text);

    Tok.DropoutProb := 0.5;
    RandSeed := 424242;
    RunA := Tok.Encode(Text);
    RandSeed := 424242;
    RunB := Tok.Encode(Text);

    // Same seed -> identical ids (deterministic given the RNG state).
    AssertEquals('seeded dropout id count stable',
      Length(RunA), Length(RunB));
    for I := 0 to High(RunA) do
      AssertEquals('seeded dropout id[' + IntToStr(I) + ']',
        RunA[I], RunB[I]);

    // The dropout segmentation must differ from the p=0 one (the chosen
    // seed/text actually drops at least one merge).
    Differs := Length(RunA) <> Length(Deterministic);
    if not Differs then
      for I := 0 to High(RunA) do
        if RunA[I] <> Deterministic[I] then Differs := true;
    AssertTrue('seeded dropout differs from deterministic', Differs);
    // And it still round-trips.
    AssertEquals('seeded dropout round-trips', Text, Tok.Decode(RunA, true));
  finally
    Tok.Free;
  end;
end;

{ ---------------------------------------------------------------- }
{ TTestNeuralChat                                                   }
{ ---------------------------------------------------------------- }

function TTestNeuralChat.FixturePath(const FileName: string): string;
begin
  Result := 'fixtures' + DirectorySeparator + FileName;
  if not FileExists(Result) then
    Result := 'tests' + DirectorySeparator + 'fixtures' + DirectorySeparator +
      FileName;
  if not FileExists(Result) then
    Fail('Fixture not found: ' + FileName +
      ' (run python3 tools/chat_template_fixture.py from the repo root).');
end;

// Renders every pinned conversation of FormatName with ApplyChatTemplate
// and asserts byte-exact parity with the Jinja ground truth (or that the
// pinned raise cases raise ENeuralChatError).
procedure TTestNeuralChat.RunChatBattery(const FormatName: string);
var
  Root: TJSONData;
  Group, CaseObj, MsgObj: TJSONObject;
  Cases, MsgArr: TJSONArray;
  Messages: TChatMessages;
  ChatFormat: TNeuralChatFormat;
  CaseCnt, MsgCnt: integer;
  Context, Rendered: string;
  Raised: boolean;
  FS: TFileStream;
begin
  ChatFormat := ChatFormatFromName(FormatName);
  AssertTrue('format name recognized: ' + FormatName,
    ChatFormat <> cfUnknown);
  FS := TFileStream.Create(FixturePath('chat_template_cases.json'),
    fmOpenRead or fmShareDenyWrite);
  try
    Root := GetJSON(FS);
  finally
    FS.Free;
  end;
  try
    Group := TJSONObject(Root).Objects[FormatName];
    Cases := Group.Arrays['cases'];
    AssertTrue(FormatName + ': no cases pinned', Cases.Count >= 5);
    for CaseCnt := 0 to Cases.Count - 1 do
    begin
      CaseObj := Cases.Objects[CaseCnt];
      Context := FormatName + ' case ' + IntToStr(CaseCnt);
      MsgArr := CaseObj.Arrays['messages'];
      SetLength(Messages, MsgArr.Count);
      for MsgCnt := 0 to MsgArr.Count - 1 do
      begin
        MsgObj := MsgArr.Objects[MsgCnt];
        Messages[MsgCnt] := ChatMessage(MsgObj.Get('role', ''),
          MsgObj.Get('content', ''));
      end;
      if CaseObj.Get('raises', false) then
      begin
        Raised := false;
        try
          ApplyChatTemplate(ChatFormat, Messages,
            CaseObj.Get('add_generation_prompt', true));
        except
          on E: ENeuralChatError do Raised := true;
        end;
        AssertTrue(Context + ': must raise ENeuralChatError', Raised);
      end
      else
      begin
        Rendered := ApplyChatTemplate(ChatFormat, Messages,
          CaseObj.Get('add_generation_prompt', true));
        AssertEquals(Context, CaseObj.Get('expected', ''), Rendered);
      end;
    end;
  finally
    Root.Free;
  end;
end;

procedure TTestNeuralChat.TestChatMLParityWithJinja;
begin
  RunChatBattery('chatml');
end;

procedure TTestNeuralChat.TestLlama2ParityWithJinja;
begin
  RunChatBattery('llama2');
end;

procedure TTestNeuralChat.TestLlama3ParityWithJinja;
begin
  RunChatBattery('llama3');
end;

procedure TTestNeuralChat.TestZephyrParityWithJinja;
begin
  RunChatBattery('zephyr');
end;

procedure TTestNeuralChat.TestGemmaParityWithJinja;
begin
  RunChatBattery('gemma');
end;

procedure TTestNeuralChat.TestPhi3ParityWithJinja;
begin
  RunChatBattery('phi3');
end;

procedure TTestNeuralChat.TestMistralParityWithJinja;
begin
  RunChatBattery('mistral');
end;

// DetectChatFormat must recognize each AUTHENTIC published template
// string (pinned in the fixture next to its cases) as its own format --
// this is the auto-detection path for tokenizer_config.json templates.
procedure TTestNeuralChat.TestDetectFormatOnAuthenticTemplates;
var
  Root: TJSONData;
  RootObj: TJSONObject;
  Cnt: integer;
  FormatName, Template: string;
  FS: TFileStream;
begin
  FS := TFileStream.Create(FixturePath('chat_template_cases.json'),
    fmOpenRead or fmShareDenyWrite);
  try
    Root := GetJSON(FS);
  finally
    FS.Free;
  end;
  try
    RootObj := TJSONObject(Root);
    AssertTrue('formats pinned', RootObj.Count >= 7);
    for Cnt := 0 to RootObj.Count - 1 do
    begin
      FormatName := RootObj.Names[Cnt];
      Template := RootObj.Objects[FormatName].Get('template', '');
      AssertTrue(FormatName + ': template pinned', Template <> '');
      AssertEquals('detect ' + FormatName, FormatName,
        ChatFormatName(DetectChatFormat(Template)));
    end;
  finally
    Root.Free;
  end;
  AssertTrue('garbage detects as unknown',
    DetectChatFormat('hello world') = cfUnknown);
end;

procedure TTestNeuralChat.TestFormatNameRoundTrip;
var
  ChatFormat: TNeuralChatFormat;
begin
  for ChatFormat := cfChatML to cfMistral do
    AssertTrue('round trip ' + ChatFormatName(ChatFormat),
      ChatFormatFromName(ChatFormatName(ChatFormat)) = ChatFormat);
  AssertTrue('unknown name', ChatFormatFromName('vicuna') = cfUnknown);
end;

// The rendered template embeds <s>/</s> as TEXT; the metaspace fixture
// tokenizer must map them to single added-token ids (1 and 2) -- the
// HF-fast behavior EncodeChat relies on.
procedure TTestNeuralChat.TestEncodeChatLlama2SpecialTokens;
var
  Tok: TNeuralHFTokenizer;
  Ids: TNeuralIntegerArray;
  Direct: TNeuralIntegerArray;
  Messages: TChatMessages;
  Cnt, EosCount: integer;
begin
  Tok := TNeuralHFTokenizer.Create();
  try
    Tok.LoadFromFile(FixturePath('tiny_bpe_metaspace_tokenizer.json'));
    SetLength(Messages, 2);
    Messages[0] := ChatMessage('user', 'hello');
    Messages[1] := ChatMessage('assistant', 'the cat');
    Ids := EncodeChat(Tok, cfLlama2, Messages, true);
    AssertTrue('ids produced', Length(Ids) > 2);
    AssertEquals('first id is BOS (<s> matched as one added token)',
      Tok.BosId, Ids[0]);
    EosCount := 0;
    for Cnt := 0 to High(Ids) do
      if Ids[Cnt] = Tok.EosId then Inc(EosCount);
    AssertEquals('one EOS for the closed assistant turn', 1, EosCount);
    // EncodeChat is exactly template -> Encode
    Direct := Tok.Encode(ApplyChatTemplate(cfLlama2, Messages, true));
    AssertEquals('same id count as direct Encode',
      Length(Direct), Length(Ids));
    for Cnt := 0 to High(Ids) do
      AssertEquals('id[' + IntToStr(Cnt) + ']', Direct[Cnt], Ids[Cnt]);
  finally
    Tok.Free;
  end;
end;

// ChatML control tokens are matched through the added-tokens mechanism:
// the Qwen2-style fixture has <|im_end|> as added token id 1, so a single
// user turn + generation prompt must contain id 1 exactly once.
procedure TTestNeuralChat.TestEncodeChatChatMLAddedToken;
var
  Tok: TNeuralHFTokenizer;
  Ids: TNeuralIntegerArray;
  Messages: TChatMessages;
  Cnt, ImEndId, ImEndCount: integer;
begin
  Tok := TNeuralHFTokenizer.Create();
  try
    Tok.LoadFromFile(FixturePath('tiny_bpe_split_qwen2_tokenizer.json'));
    ImEndId := Tok.TokenToId('<|im_end|>');
    AssertEquals('<|im_end|> is an added token', 1, ImEndId);
    SetLength(Messages, 1);
    Messages[0] := ChatMessage('user', 'the cat');
    Ids := EncodeChat(Tok, cfChatML, Messages, true);
    ImEndCount := 0;
    for Cnt := 0 to High(Ids) do
      if Ids[Cnt] = ImEndId then Inc(ImEndCount);
    AssertEquals('exactly one <|im_end|> id', 1, ImEndCount);
  finally
    Tok.Free;
  end;
end;

// chat_template auto-detection from tokenizer_config.json: both the
// plain-string form and the newer list-of-named-templates form.
procedure TTestNeuralChat.TestLoadChatTemplateFromTokenizerConfig;
var
  TempFile, Template: string;
  SL: TStringList;
begin
  TempFile := GetTempDir(true) + 'chat_tokenizer_config.json';
  SL := TStringList.Create();
  try
    SL.Text := '{"eos_token": "<|im_end|>", "chat_template":'
      + ' "{% for m in messages %}<|im_start|>{{ m.role }}{% endfor %}"}';
    SL.SaveToFile(TempFile);
    Template := LoadChatTemplateString(TempFile);
    AssertTrue('template loaded', Pos('<|im_start|>', Template) > 0);
    AssertTrue('detected as chatml',
      DetectChatFormatFromConfigFile(TempFile) = cfChatML);

    SL.Text := '{"chat_template": [{"name": "tool_use", "template":'
      + ' "irrelevant"}, {"name": "default", "template":'
      + ' "x<start_of_turn>y"}]}';
    SL.SaveToFile(TempFile);
    AssertEquals('default entry of the list form wins',
      'x<start_of_turn>y', LoadChatTemplateString(TempFile));
    AssertTrue('list form detected as gemma',
      DetectChatFormatFromConfigFile(TempFile) = cfGemma);

    SL.Text := '{"eos_token": "</s>"}';
    SL.SaveToFile(TempFile);
    AssertEquals('no chat_template -> empty string',
      '', LoadChatTemplateString(TempFile));
    AssertTrue('no chat_template -> cfUnknown',
      DetectChatFormatFromConfigFile(TempFile) = cfUnknown);
  finally
    SL.Free;
    DeleteFile(TempFile);
  end;
end;

procedure TTestNeuralChat.TestUnknownFormatRaises;
var
  Messages: TChatMessages;
  Raised: boolean;
begin
  SetLength(Messages, 1);
  Messages[0] := ChatMessage('user', 'hi');
  Raised := false;
  try
    ApplyChatTemplate(cfUnknown, Messages, true);
  except
    on E: ENeuralChatError do Raised := true;
  end;
  AssertTrue('cfUnknown must raise ENeuralChatError', Raised);
end;

initialization
  RegisterTest(TTestNeuralHFTokenizer);
  RegisterTest(TTestNeuralChat);
end.
