program Seq2SeqTranslate;
(*
Copyright (C) 2026 Joao Paulo Schwarz Schuler

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program; if not, write to the Free Software Foundation, Inc.,
51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

Coded by Claude (AI).
*)

// Seq2SeqTranslate -- an OFFLINE, self-contained demonstration of the
// landed sequence-to-sequence DECODE + EVALUATE plumbing:
//
//     encoder/decoder import  ->  DecodeSeq2SeqBeamSearch  ->  BLEU / ROUGE
//
// It runs with NO network access and NO multi-GB checkpoint download: it
// imports the committed pico Marian fixture (tests/fixtures/tiny_marian.*,
// 13-token vocab, 2 layers, d_model 8 - the same fixture the importer
// parity test uses) via BuildMarianFromSafeTensors, runs token-id beam
// search (DecodeSeq2SeqBeamSearch, neuraldecode.pas) over a fixed source
// id sequence, and scores the decoded ids against a reference id sequence
// with corpus BLEU + ROUGE-1/2/L (neuralnlpmetrics.pas).
//
// IMPORTANT - this is a PLUMBING / wiring demo, not a translation-quality
// demo. The pico fixture is RANDOMLY initialized, so the "translation" is
// gibberish and the BLEU/ROUGE numbers against an arbitrary reference are
// meaningless as quality. What this example proves end-to-end is that:
//   (a) a real two-net encoder-decoder imports and beam-decodes offline;
//   (b) the decoded token ids flow into the BLEU/ROUGE metrics; and
//   (c) the pipeline is DETERMINISTIC (re-running beam search yields the
//       exact same ids) and the metrics are well-formed (a reference scored
//       against ITSELF gives BLEU = ROUGE = 1.0).
// Those last two are checked with assertions; the program halts non-zero if
// either fails.
//
// To translate REAL text, point this same DecodeSeq2SeqBeamSearch call at a
// real Helsinki-NLP/opus-mt-* checkpoint (model.safetensors + config.json +
// tokenizer.json) and feed it ids from that checkpoint's tokenizer - the
// Marian importer + beam search are unchanged; only the tokenizer (a
// SentencePiece/Unigram tokenizer.json read by TNeuralHFTokenizer) and the
// detokenize step differ. See examples/Summarize for the BART text path
// over a downloaded checkpoint; this example deliberately stays offline.
//
// Usage:
//   Seq2SeqTranslate [fixture.safetensors] [config.json]
//     (defaults to the committed tiny_marian fixture; relative to the repo
//      root, or pass absolute paths.)

{$mode objfpc}{$H+}

uses
  SysUtils,
  neuralvolume, neuralnetwork, neuralpretrained, neuraldecode,
  neuralnlpmetrics;

const
  // Built-in pico fixture (random weights). Run from the repo root.
  DefaultModel  = 'tests/fixtures/tiny_marian.safetensors';
  DefaultConfig = 'tests/fixtures/tiny_marian_config.json';
  EncSeqLen = 10;   // fixture sinusoidal tables are built for these lengths
  DecSeqLen = 6;
  BeamWidth = 4;
  LengthPenalty = 1.0;

var
  ModelPath, ConfigPath: string;
  Enc, Dec: TNNet;
  Config: TMarianConfig;
  SourceIds, OutA, OutB, Reference: TNeuralIntegerArray;
  i: integer;
  Bleu, BleuSelf: TNeuralFloat;
  R1, R2, RL, R1Self: TNNetRougeScore;
  FloatFmt: TFormatSettings;

  function IdsToStr(const A: TNeuralIntegerArray): string;
  var j: integer;
  begin
    Result := '[';
    for j := 0 to High(A) do
    begin
      if j > 0 then Result := Result + ' ';
      Result := Result + IntToStr(A[j]);
    end;
    Result := Result + ']';
  end;

  function SameIds(const A, B: TNeuralIntegerArray): boolean;
  var j: integer;
  begin
    Result := Length(A) = Length(B);
    if Result then
      for j := 0 to High(A) do
        if A[j] <> B[j] then Exit(false);
  end;

begin
  FloatFmt := DefaultFormatSettings;
  FloatFmt.DecimalSeparator := '.';

  ModelPath := DefaultModel;
  ConfigPath := DefaultConfig;
  if ParamCount >= 1 then ModelPath := ParamStr(1);
  if ParamCount >= 2 then ConfigPath := ParamStr(2);

  if not FileExists(ModelPath) then
  begin
    WriteLn('ERROR: model not found: ', ModelPath);
    WriteLn('Run from the repo root, or pass <fixture.safetensors> ' +
      '<config.json>. The committed pico fixture is generated by ' +
      'tools/marian_tiny_fixture.py.');
    Halt(2);
  end;

  Enc := nil; Dec := nil;
  try
    WriteLn('=== Seq2Seq beam-decode + BLEU/ROUGE plumbing demo (OFFLINE) ===');
    WriteLn('Importing pico Marian fixture: ', ModelPath);
    BuildMarianFromSafeTensors(ModelPath, Enc, Dec, Config,
      EncSeqLen, DecSeqLen, {pTrainable=}false, ConfigPath);
    WriteLn(MarianConfigToString(Config));
    WriteLn('Encoder window ', EncSeqLen, ', decoder window ', DecSeqLen,
      ', beam ', BeamWidth, ', length penalty ',
      FormatFloat('0.00', LengthPenalty, FloatFmt));
    WriteLn('NOTE: random pico weights -> output is gibberish; this demo ',
      'exercises the WIRING, not translation quality.');
    WriteLn;

    // A fixed source id sequence within the 13-token vocab (ids 0..12;
    // 12 = pad, 0 = eos for this fixture). Plain content ids 1..9.
    SetLength(SourceIds, EncSeqLen);
    for i := 0 to EncSeqLen - 1 do
      SourceIds[i] := 1 + (i mod 9); // 1..9

    WriteLn('Source ids: ', IdsToStr(SourceIds));

    // Beam search through the two-net encoder/decoder pair. Marian's
    // decoder_start_token_id = pad; the fixture's eos = 0.
    OutA := DecodeSeq2SeqBeamSearch(Enc, Dec, SourceIds,
      {StartTokenId=}Config.DecoderStartTokenId,
      {EOSTokenId=}Config.PadTokenId, // any terminal id; not hit on gibberish
      {MaxNewTokens=}DecSeqLen - 1, BeamWidth, LengthPenalty);
    WriteLn('Decoded ids (beam search): ', IdsToStr(OutA));

    // (c1) DETERMINISM: a second identical beam run must reproduce the ids.
    OutB := DecodeSeq2SeqBeamSearch(Enc, Dec, SourceIds,
      Config.DecoderStartTokenId, Config.PadTokenId,
      DecSeqLen - 1, BeamWidth, LengthPenalty);
    if not SameIds(OutA, OutB) then
    begin
      WriteLn('FAIL: beam search not deterministic across identical runs.');
      Halt(3);
    end;
    WriteLn('OK: beam decode is deterministic (identical re-run).');

    // Use a small arbitrary reference id sequence (what a real bilingual
    // reference would supply). Quality is meaningless here by design.
    Reference := TNeuralIntegerArray.Create(3, 5, 7, 2, 4);

    WriteLn;
    WriteLn('Reference ids: ', IdsToStr(Reference));

    // BLEU / ROUGE on TOKEN-ID arrays (neuralnlpmetrics has id overloads,
    // so no detokenizer is needed for the plumbing demo).
    Bleu := CorpusBLEU([OutA], [Reference]);
    R1 := RougeN(OutA, Reference, 1);
    R2 := RougeN(OutA, Reference, 2);
    RL := RougeL(OutA, Reference);
    WriteLn('--- decoded-vs-reference scores (gibberish; wiring only) ---');
    WriteLn('BLEU      : ', FormatFloat('0.0000', Bleu, FloatFmt));
    WriteLn('ROUGE-1 F1: ', FormatFloat('0.0000', R1.F1, FloatFmt));
    WriteLn('ROUGE-2 F1: ', FormatFloat('0.0000', R2.F1, FloatFmt));
    WriteLn('ROUGE-L F1: ', FormatFloat('0.0000', RL.F1, FloatFmt));

    // (c2) METRIC SANITY: a reference scored against ITSELF is a perfect
    // match -> BLEU = 1, ROUGE-1 F1 = 1.
    BleuSelf := CorpusBLEU([Reference], [Reference]);
    R1Self := RougeN(Reference, Reference, 1);
    WriteLn;
    WriteLn('Sanity (reference vs itself):');
    WriteLn('  BLEU      : ', FormatFloat('0.0000', BleuSelf, FloatFmt));
    WriteLn('  ROUGE-1 F1: ', FormatFloat('0.0000', R1Self.F1, FloatFmt));
    if (Abs(BleuSelf - 1.0) > 1e-6) or (Abs(R1Self.F1 - 1.0) > 1e-6) then
    begin
      WriteLn('FAIL: self-reference BLEU/ROUGE should be 1.0.');
      Halt(4);
    end;
    WriteLn('OK: self-reference BLEU = ROUGE-1 F1 = 1.0.');

    WriteLn;
    WriteLn('=== plumbing verified: import -> beam decode -> BLEU/ROUGE ===');
  finally
    Dec.Free;
    Enc.Free;
  end;
end.
