#!/usr/bin/env python3
# Generates neural/neuralunicodeclasses.inc -- exact Unicode general-category
# range tables for the \p{L} / \p{N} / \p{M} character classes used by the
# byte-level pre-tokenization regexes in neuralhftokenizer.pas
# (IsLetterCP / IsNumberCP / IsMarkCP).
#
# Run with: python3 tools/gen_unicode_class_tables.py
#
# Emits three const arrays of inclusive [lo, hi] codepoint ranges, sorted
# ascending for binary search:
#   cUnicodeLetterRanges -- category L* (Lu, Ll, Lt, Lm, Lo)
#   cUnicodeNumberRanges -- category N* (Nd, Nl, No)
#   cUnicodeMarkRanges   -- category M* (Mn, Mc, Me)
#
# These REPLACE the historical hand-written "major scripts" approximation:
# real-vocab parity fuzzing against the Qwen3.6-27B tokenizer showed the
# approximation splits differently from HF `tokenizers` whenever an
# uncovered script character (e.g. Bengali letters, Gujarati digits) sits
# next to a covered class -- the Qwen3.5/3.6 split pattern's any-char
# letter-run prefix ([^\r\n\p{L}\p{N}]?[\p{L}\p{M}]+) is especially
# sensitive to this.
import os
import unicodedata


def category_ranges(prefix):
    ranges = []
    start = None
    for cp in range(0x110000):
        ok = unicodedata.category(chr(cp)).startswith(prefix)
        if ok and start is None:
            start = cp
        elif not ok and start is not None:
            ranges.append((start, cp - 1))
            start = None
    if start is not None:
        ranges.append((start, 0x10FFFF))
    return ranges


def emit(f, name, ranges):
    f.write('const\n')
    f.write('  c%sCount = %d;\n' % (name, len(ranges)))
    f.write('  c%s: array[0..c%sCount - 1] of TUnicodeRangePair = (\n'
            % (name, name))
    line = '    '
    parts = ['($%X, $%X)' % r for r in ranges]
    for i, p in enumerate(parts):
        tok = p + (', ' if i + 1 < len(parts) else '')
        if len(line) + len(tok) > 78:
            f.write(line.rstrip() + '\n')
            line = '    '
        line += tok
    f.write(line.rstrip() + '\n  );\n\n')


def main():
    out = os.path.join(os.path.dirname(__file__), '..', 'neural',
                       'neuralunicodeclasses.inc')
    L = category_ranges('L')
    N = category_ranges('N')
    M = category_ranges('M')
    with open(out, 'w', newline='\n') as f:
        f.write(
            '{ ---------------------------------------------------------------- }\n'
            '{ neuralunicodeclasses.inc -- AUTO-GENERATED, do not edit by hand.  }\n'
            '{ Generated by tools/gen_unicode_class_tables.py from Python        }\n'
            '{ unicodedata (Unicode %s). Exact general-category ranges       }\n'
            '{ for the \\p{L} / \\p{N} / \\p{M} regex classes (inclusive [lo,hi]  }\n'
            '{ pairs, ascending, binary-searched by CPInRanges).                 }\n'
            '{ ---------------------------------------------------------------- }\n\n'
            % unicodedata.unidata_version)
        f.write('type\n'
                '  TUnicodeRangePair = array[0..1] of cardinal;\n\n')
        emit(f, 'UnicodeLetterRanges', L)
        emit(f, 'UnicodeNumberRanges', N)
        emit(f, 'UnicodeMarkRanges', M)
    print('wrote %s: L=%d N=%d M=%d ranges' % (out, len(L), len(N), len(M)))


if __name__ == '__main__':
    main()
