#!/usr/bin/env python3
# Generates neural/neuralnfctables.inc -- compact canonical Unicode tables
# for NFD/NFC normalization in neuralhftokenizer.pas.
#
# Run with: /home/bpsa/x/bin/python tools/gen_nfc_tables.py
#
# Emits four const arrays (see the .inc header for the exact layout):
#   cNFCDecomp     -- canonical decomposition pairs (CP -> A [+ B])
#   cNFCComposePair-- canonical composition pairs (A,B -> CP), exclusions removed
#   cNFCCombClass  -- nonzero Canonical_Combining_Class entries
#   cNFKCDecomp    -- COMPATIBILITY decomposition mappings (CP -> [A,B,...]),
#                     i.e. the entries tagged <compat>/<wide>/<super>/...
#
# Coverage: every CANONICAL (non-compatibility) decomposition and every
# nonzero combining class in the Basic Multilingual Plane plus the few
# above it that unicodedata knows -- i.e. the full canonical algorithm,
# not a subset. Hangul is handled ALGORITHMICALLY in Pascal and is
# deliberately excluded from the table. Compatibility forms (NFKC/NFKD)
# ARE emitted (cNFKCDecomp), applied before canonical ordering in Pascal.
import sys
import unicodedata

HANGUL_SBASE = 0xAC00
HANGUL_SCOUNT = 11172  # 0xAC00 .. 0xD7A3


def is_hangul_syllable(cp):
    return HANGUL_SBASE <= cp < HANGUL_SBASE + HANGUL_SCOUNT


def main():
    # Walk every assigned codepoint unicodedata can describe.
    decomp = {}        # cp -> (a, b)  (b may be None for singleton)
    combclass = {}     # cp -> ccc
    full_decomp_first = {}  # cp -> first decomposition codepoint (for exclusion logic)
    compat = {}        # cp -> [c0, c1, ...] FULLY-resolved compatibility decomposition

    for cp in range(0x110000):
        ch = chr(cp)
        ccc = unicodedata.combining(ch)
        if ccc:
            combclass[cp] = ccc
        d = unicodedata.decomposition(ch)
        if not d:
            continue
        parts = d.split()
        if parts and parts[0].startswith('<'):
            # compatibility decomposition (<compat>/<wide>/<super>/<sub>/
            # <fraction>/<font>/<noBreak>/...). Record the FULLY recursive
            # compatibility (NFKD) expansion of CP, MINUS the tag. Hangul
            # syllables never carry a compat tag so no special-case needed.
            nfkd = unicodedata.normalize('NFKD', ch)
            compat[cp] = [ord(c) for c in nfkd]
            continue
        if is_hangul_syllable(cp):
            # algorithmic in Pascal
            continue
        cps = [int(p, 16) for p in parts]
        if len(cps) == 1:
            decomp[cp] = (cps[0], None)
            full_decomp_first[cp] = cps[0]
        elif len(cps) == 2:
            decomp[cp] = (cps[0], cps[1])
            full_decomp_first[cp] = cps[0]
        else:
            raise SystemExit('unexpected canonical decomposition length: %04X %r' % (cp, cps))

    # Composition: a pair (a,b) composes to cp UNLESS:
    #   * cp is a singleton decomposition (b is None) -- never composes,
    #   * cp is in the Composition Exclusions list,
    #   * the first element 'a' itself has ccc != 0 (non-starter) -- such
    #     entries are excluded by the standard.
    # unicodedata gives us the exclusions implicitly: normalize('NFC') of
    # the decomposed pair will NOT recombine excluded composites. Use that.
    compose = {}  # (a,b) -> cp
    for cp, (a, b) in decomp.items():
        if b is None:
            continue
        if combclass.get(a, 0) != 0:
            continue  # non-starter first element
        # Excluded if recomposing chr(a)+chr(b) under NFC does not yield cp.
        recombined = unicodedata.normalize('NFC', chr(a) + chr(b))
        if recombined != chr(cp):
            continue  # composition-excluded / blocked
        compose[(a, b)] = cp

    out = []
    w = out.append
    w('{ ---------------------------------------------------------------- }')
    w('{ neuralnfctables.inc -- AUTO-GENERATED, do not edit by hand.       }')
    w('{ Generated by tools/gen_nfc_tables.py from Python unicodedata      }')
    w('{ (Unicode %s). Compact CANONICAL tables for NFD/NFC.            }' % unicodedata.unidata_version)
    w('{                                                                  }')
    w('{ Coverage: ALL canonical (non-compatibility) decompositions and   }')
    w('{ nonzero Canonical_Combining_Class values that Python unicodedata  }')
    w('{ knows. Hangul syllables are handled ALGORITHMICALLY in Pascal and }')
    w('{ are NOT tabled. Compatibility (NFKC/NFKD) decompositions ARE in   }')
    w('{ cNFKCDecompIdx/cNFKCDecompPool below.                             }')
    w('{ ---------------------------------------------------------------- }')
    w('')

    # Decomposition table: sorted by CP for binary search.
    items = sorted(decomp.items())
    w('// Canonical decomposition: CP -> (A, B). B=0 means a singleton')
    w('// decomposition (CP -> A only). Sorted by CP for binary search.')
    w('const')
    w('  cNFCDecompCount = %d;' % len(items))
    w('  cNFCDecomp: array[0..cNFCDecompCount - 1, 0..2] of cardinal = (')
    rows = []
    for cp, (a, b) in items:
        bb = b if b is not None else 0
        rows.append('    ($%05X, $%05X, $%05X)' % (cp, a, bb))
    w(',\n'.join(rows))
    w('  );')
    w('')

    # Composition table: sorted by (A,B) for binary search.
    citems = sorted(compose.items())
    w('// Canonical composition: (A, B) -> CP. Sorted by (A shl 21) or B')
    w('// packed key for binary search. Composition-excluded / blocked')
    w('// pairs and non-starter-led pairs are already removed.')
    w('const')
    w('  cNFCComposeCount = %d;' % len(citems))
    w('  cNFCCompose: array[0..cNFCComposeCount - 1, 0..2] of cardinal = (')
    rows = []
    for (a, b), cp in citems:
        rows.append('    ($%05X, $%05X, $%05X)' % (a, b, cp))
    w(',\n'.join(rows))
    w('  );')
    w('')

    # Combining class table: sorted by CP.
    kitems = sorted(combclass.items())
    w('// Nonzero Canonical_Combining_Class: CP -> CCC. Sorted by CP.')
    w('const')
    w('  cNFCCombClassCount = %d;' % len(kitems))
    w('  cNFCCombClass: array[0..cNFCCombClassCount - 1, 0..1] of cardinal = (')
    rows = []
    for cp, ccc in kitems:
        rows.append('    ($%05X, %d)' % (cp, ccc))
    w(',\n'.join(rows))
    w('  );')
    w('')

    # Compatibility (NFKD) decomposition table. Variable length, so store a
    # flat pool of codepoints plus an index table (CP, offset, length) sorted
    # by CP for binary search. Applied in Pascal BEFORE canonical ordering
    # when the requested form is NFKC/NFKD.
    xitems = sorted(compat.items())
    pool = []
    index = []
    for cp, cps in xitems:
        index.append((cp, len(pool), len(cps)))
        pool.extend(cps)
    w('// Compatibility decomposition (NFKD). cNFKCDecompIdx maps CP ->')
    w('// (offset, length) into the flat cNFKCDecompPool codepoint array;')
    w('// each entry is the FULL recursive NFKD expansion. Sorted by CP for')
    w('// binary search. Applied before canonical ordering for NFKC/NFKD.')
    w('const')
    w('  cNFKCDecompCount = %d;' % len(index))
    w('  cNFKCDecompPoolCount = %d;' % len(pool))
    w('  cNFKCDecompIdx: array[0..cNFKCDecompCount - 1, 0..2] of cardinal = (')
    rows = []
    for cp, off, ln in index:
        rows.append('    ($%05X, %d, %d)' % (cp, off, ln))
    w(',\n'.join(rows))
    w('  );')
    w('  cNFKCDecompPool: array[0..cNFKCDecompPoolCount - 1] of cardinal = (')
    # 8 codepoints per line for readability.
    plines = []
    for i in range(0, len(pool), 8):
        chunk = pool[i:i + 8]
        plines.append('    ' + ', '.join('$%05X' % c for c in chunk))
    w(',\n'.join(plines))
    w('  );')
    w('')

    text = '\n'.join(out) + '\n'
    path = sys.argv[1] if len(sys.argv) > 1 else 'neural/neuralnfctables.inc'
    with open(path, 'w') as f:
        f.write(text)
    sys.stderr.write('wrote %s: %d decomp, %d compose, %d combclass, '
                     '%d compat (%d pool)\n' %
                     (path, len(items), len(citems), len(kitems),
                      len(index), len(pool)))


if __name__ == '__main__':
    main()
