#!/usr/bin/env python3
"""Pico GGUF fixtures for the Pascal GGUF reader/importer tests.

Coded by Claude (AI).

Writes, with the `gguf` Python package (the llama.cpp reference writer):

  tests/fixtures/tiny_llama_f32.gguf
  tests/fixtures/tiny_llama_f16.gguf
      The EXISTING tests/fixtures/tiny_llama.safetensors checkpoint
      (layers=2, heads=2, kv_heads=1, hidden=8, ffn=12, vocab=11, UNTIED
      head; generated by tools/llama_tiny_fixture.py and oracle-verified
      against HF transformers) converted to GGUF with the llama.cpp tensor
      naming (token_embd.weight, blk.N.attn_q.weight, ...) and the
      convert_hf_to_gguf.py q/k row PERMUTE (HF rotate_half layout ->
      interleaved rotary pairs), exactly like a real llama.cpp conversion.
      The f32 variant must import to logits IDENTICAL to the safetensors
      import (and hence match tiny_llama_logits.json); the f16 variant
      rounds every matrix to half precision (norms stay F32).

  tests/fixtures/tiny_llama_q8.gguf
  tests/fixtures/tiny_llama_q8.safetensors + tiny_llama_q8_config.json
      A NEW seeded pico Llama (layers=2, heads=2, kv_heads=1, hidden=32,
      ffn=32, vocab=8, TIED head) written twice from the same weights:
      Q8_0-quantized GGUF (norms F32) and an F32 safetensors + HF config.
      hidden=32 because Q8_0 blocks span 32 elements along the contiguous
      axis - the in-dimension must be a multiple of 32 (tiny_llama's
      hidden=8 cannot be Q8_0-quantized). Weights are O(1) scale (NOT
      std-0.02) so quantization error and logits are non-vacuous.

Run from the repository root:
  /home/bpsa/x/bin/python tools/make_pico_gguf_fixture.py
"""
import json
import os

import numpy as np

import gguf
from gguf import quants
from safetensors import safe_open
from safetensors.numpy import save_file

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FIX = os.path.join(ROOT, "tests", "fixtures")

F32 = gguf.GGMLQuantizationType.F32
F16 = gguf.GGMLQuantizationType.F16
Q8_0 = gguf.GGMLQuantizationType.Q8_0


def permute_qk(w, n_head):
    """llama.cpp convert_hf_to_gguf.py LlamaModel.permute: HF rotate_half
    row layout -> interleaved rotary pairs (per head: new[2p] = old[p],
    new[2p+1] = old[p + head_dim//2])."""
    return (w.reshape(n_head, 2, w.shape[0] // n_head // 2, *w.shape[1:])
             .swapaxes(1, 2)
             .reshape(w.shape))


# ggml tensor name for one HF llama tensor name (block tensors only).
HF_TO_GGUF = {
    "input_layernorm.weight": "attn_norm.weight",
    "self_attn.q_proj.weight": "attn_q.weight",
    "self_attn.k_proj.weight": "attn_k.weight",
    "self_attn.v_proj.weight": "attn_v.weight",
    "self_attn.o_proj.weight": "attn_output.weight",
    "post_attention_layernorm.weight": "ffn_norm.weight",
    "mlp.gate_proj.weight": "ffn_gate.weight",
    "mlp.up_proj.weight": "ffn_up.weight",
    "mlp.down_proj.weight": "ffn_down.weight",
}


def write_llama_gguf(path, cfg, weights, matrix_dtype, tokens):
    """Writes one llama-architecture GGUF file. weights maps HF tensor
    names to float32 numpy arrays (HF [out, in] row layout, q/k in HF
    rotate_half order). matrix_dtype: F32 | F16 | Q8_0 applies to the 2-D
    matrices; 1-D norm gains always stay F32 (the llama.cpp convention)."""
    w = gguf.GGUFWriter(path, "llama")
    w.add_block_count(cfg["num_hidden_layers"])
    w.add_context_length(cfg["max_position_embeddings"])
    w.add_embedding_length(cfg["hidden_size"])
    w.add_feed_forward_length(cfg["intermediate_size"])
    w.add_head_count(cfg["num_attention_heads"])
    w.add_head_count_kv(cfg["num_key_value_heads"])
    w.add_layer_norm_rms_eps(cfg["rms_norm_eps"])
    w.add_rope_freq_base(cfg["rope_theta"])
    w.add_vocab_size(cfg["vocab_size"])
    # A minimal tokenizer block: exercises string-array metadata parsing.
    w.add_tokenizer_model("llama")
    w.add_token_list(tokens)

    def add(gguf_name, data, is_matrix):
        data = np.ascontiguousarray(data, dtype=np.float32)
        if is_matrix and matrix_dtype == Q8_0:
            q = quants.quantize(data, Q8_0)
            w.add_tensor(gguf_name, q, raw_dtype=Q8_0)
        elif is_matrix and matrix_dtype == F16:
            w.add_tensor(gguf_name, data.astype(np.float16))
        else:
            w.add_tensor(gguf_name, data)

    n_head = cfg["num_attention_heads"]
    n_kv = cfg["num_key_value_heads"]
    add("token_embd.weight", weights["model.embed_tokens.weight"], True)
    for b in range(cfg["num_hidden_layers"]):
        hf_p = "model.layers.%d." % b
        gg_p = "blk.%d." % b
        for hf_suffix, gg_suffix in HF_TO_GGUF.items():
            data = weights[hf_p + hf_suffix]
            if hf_suffix == "self_attn.q_proj.weight":
                data = permute_qk(data, n_head)
            elif hf_suffix == "self_attn.k_proj.weight":
                data = permute_qk(data, n_kv)
            add(gg_p + gg_suffix, data, data.ndim == 2)
    add("output_norm.weight", weights["model.norm.weight"], False)
    if not cfg["tie_word_embeddings"]:
        add("output.weight", weights["lm_head.weight"], True)

    w.write_header_to_file()
    w.write_kv_data_to_file()
    w.write_tensors_to_file()
    w.close()
    print("wrote %s (%d bytes)" % (path, os.path.getsize(path)))


# ---------------------------------------------------------------------------
# 1) tiny_llama.safetensors -> tiny_llama_f32.gguf / tiny_llama_f16.gguf
# ---------------------------------------------------------------------------
with open(os.path.join(FIX, "tiny_llama_config.json")) as f:
    tiny_cfg = json.load(f)
tiny_weights = {}
with safe_open(os.path.join(FIX, "tiny_llama.safetensors"), "numpy") as f:
    for name in f.keys():
        if "rotary_emb.inv_freq" in name:
            continue  # dummy ignorable buffer, not a real weight
        tiny_weights[name] = f.get_tensor(name).astype(np.float32)
tiny_tokens = ["<tok_%d>" % i for i in range(tiny_cfg["vocab_size"])]
write_llama_gguf(os.path.join(FIX, "tiny_llama_f32.gguf"), tiny_cfg,
                 tiny_weights, F32, tiny_tokens)
write_llama_gguf(os.path.join(FIX, "tiny_llama_f16.gguf"), tiny_cfg,
                 tiny_weights, F16, tiny_tokens)

# ---------------------------------------------------------------------------
# 2) NEW hidden-32 pico model (Q8_0-quantizable) -> gguf + safetensors
# ---------------------------------------------------------------------------
q8_cfg = {
    "architectures": ["LlamaForCausalLM"],
    "model_type": "llama",
    "hidden_size": 32,
    "intermediate_size": 32,
    "num_hidden_layers": 2,
    "num_attention_heads": 2,
    "num_key_value_heads": 1,
    "vocab_size": 8,
    "max_position_embeddings": 12,
    "rms_norm_eps": 1e-5,
    "rope_theta": 10000.0,
    "tie_word_embeddings": True,  # no output.weight -> exercises the
    "rope_scaling": None,         # tied-LM-head GGUF inference
}
rng = np.random.RandomState(20260612)
H = q8_cfg["hidden_size"]
I = q8_cfg["intermediate_size"]
KV = q8_cfg["num_key_value_heads"] * (H // q8_cfg["num_attention_heads"])
q8_weights = {
    "model.embed_tokens.weight":
        rng.randn(q8_cfg["vocab_size"], H).astype(np.float32) * 0.4,
    "model.norm.weight":
        (1.0 + 0.1 * rng.randn(H)).astype(np.float32),
}
for b in range(q8_cfg["num_hidden_layers"]):
    p = "model.layers.%d." % b
    q8_weights[p + "input_layernorm.weight"] = \
        (1.0 + 0.1 * rng.randn(H)).astype(np.float32)
    q8_weights[p + "self_attn.q_proj.weight"] = \
        rng.randn(H, H).astype(np.float32) * 0.25
    q8_weights[p + "self_attn.k_proj.weight"] = \
        rng.randn(KV, H).astype(np.float32) * 0.25
    q8_weights[p + "self_attn.v_proj.weight"] = \
        rng.randn(KV, H).astype(np.float32) * 0.25
    q8_weights[p + "self_attn.o_proj.weight"] = \
        rng.randn(H, H).astype(np.float32) * 0.25
    q8_weights[p + "post_attention_layernorm.weight"] = \
        (1.0 + 0.1 * rng.randn(H)).astype(np.float32)
    q8_weights[p + "mlp.gate_proj.weight"] = \
        rng.randn(I, H).astype(np.float32) * 0.25
    q8_weights[p + "mlp.up_proj.weight"] = \
        rng.randn(I, H).astype(np.float32) * 0.25
    q8_weights[p + "mlp.down_proj.weight"] = \
        rng.randn(H, I).astype(np.float32) * 0.25

q8_tokens = ["<tok_%d>" % i for i in range(q8_cfg["vocab_size"])]
write_llama_gguf(os.path.join(FIX, "tiny_llama_q8.gguf"), q8_cfg,
                 q8_weights, Q8_0, q8_tokens)
save_file(q8_weights, os.path.join(FIX, "tiny_llama_q8.safetensors"))
with open(os.path.join(FIX, "tiny_llama_q8_config.json"), "w") as f:
    json.dump(q8_cfg, f, indent=1)
print("wrote tiny_llama_q8.safetensors (%d bytes) + config" %
      os.path.getsize(os.path.join(FIX, "tiny_llama_q8.safetensors")))
