#!/usr/bin/env python3
"""Generate a tiny RANDOM Marian / OPUS-MT parity fixture for
tests/TestNeuralPretrained.pas (no network access needed: the model is
randomly initialized from a pico config, never downloaded).

One fixture, KB-scale, pinned in tests/fixtures/:

  tiny_marian.*: MarianMTModel (the Helsinki-NLP/opus-mt-* translation
      architecture) with every Marian trait the importer must reproduce:
        - POST-norm encoder-decoder blocks: LayerNorm AFTER the residual
          add (self_attn_layer_norm / encoder_attn_layer_norm /
          final_layer_norm per block; NO final stack norm), plain BIASED
          nn.LayerNorm (eps 1e-5) - vs T5's pre-RMSNorm;
        - STATIC sinusoidal positions in HF Marian's HALF-SPLIT layout
          (sin in columns 0..d/2-1, cos in columns d/2..d-1 - NOT the
          interleaved Vaswani layout), NOT saved in real checkpoints
          (_keys_to_ignore_on_save) so dropped here and regenerated by
          the importer;
        - swish/SiLU FFN (fc2(silu(fc1(x))), both biased);
        - standard 1/sqrt(head_dim) attention scaling, ALL q/k/v/out
          projections biased;
        - scale_embedding: token embeddings multiplied by sqrt(d_model)
          BEFORE adding positions (the head stays unscaled);
        - shared source/target embedding TIED to the lm_head PLUS the
          final_logits_bias vector added to every logit row;
        - decoder_start_token_id = pad_token_id (rows of the pinned
          decoder ids start with it).

The reference is computed by HF transformers in float64 (the oracle
convention of the committed fixtures): the encoder final hidden states
plus the full encoder-decoder logits for pinned encoder/decoder input
ids.

Coded by Claude (AI).

Usage (from the repo root):
  python3 tools/marian_tiny_fixture.py
writes tests/fixtures/tiny_marian{.safetensors,_config.json,_logits.json}.
Needs torch + transformers + safetensors.
"""
import json
import math

import numpy as np
import torch
from safetensors.torch import save_file
from transformers import MarianConfig, MarianMTModel

N_LAYER = 2
N_HEAD = 2                    # head_dim = D_MODEL / N_HEAD = 4
D_MODEL = 8
D_FF = 16
VOCAB = 13
PAD = 12                      # Marian convention: pad = vocab - 1
MAX_POS = 16
ENC_LEN = 10
DEC_LEN = 6
N_SEQUENCES = 2

torch.manual_seed(20260612)

# Pinned inputs: encoder ids end with eos 0 (the opus-mt convention) and
# decoder ids start with decoder_start_token_id = pad (the Marian shift).
enc_sequences = [[(5 * i + 3 * s + s * s) % (VOCAB - 2) + 1
                  for i in range(ENC_LEN - 1)] + [0]
                 for s in range(N_SEQUENCES)]
dec_sequences = [[PAD] + [(3 * i + 2 * s + 1) % (VOCAB - 2) + 1
                          for i in range(DEC_LEN - 1)]
                 for s in range(N_SEQUENCES)]

cfg_dict = {
    'architectures': ['MarianMTModel'],
    'model_type': 'marian',
    'd_model': D_MODEL,
    'encoder_layers': N_LAYER,
    'decoder_layers': N_LAYER,
    'encoder_attention_heads': N_HEAD,
    'decoder_attention_heads': N_HEAD,
    'encoder_ffn_dim': D_FF,
    'decoder_ffn_dim': D_FF,
    'vocab_size': VOCAB,
    'max_position_embeddings': MAX_POS,
    'activation_function': 'swish',
    'scale_embedding': True,
    'static_position_embeddings': True,
    'share_encoder_decoder_embeddings': True,
    'tie_word_embeddings': True,
    'dropout': 0.0,
    'attention_dropout': 0.0,
    'activation_dropout': 0.0,
    'pad_token_id': PAD,
    'eos_token_id': 0,
    'decoder_start_token_id': PAD,
}
model = MarianMTModel(MarianConfig(**cfg_dict, attn_implementation='eager'))

# HF inits with tiny stds at this pico width; boost so every quirk is
# visible in the oracle: O(1) attention scores, FFN pre-activations in the
# region where swish and relu/gelu genuinely differ, layer-norm gains and
# biases away from (1, 0), a final_logits_bias that moves the argmax.
with torch.no_grad():
    model.model.shared.weight.normal_(0.0, 0.5)
    for stack_layers in (model.model.encoder.layers,
                         model.model.decoder.layers):
        for layer in stack_layers:
            attns = [layer.self_attn]
            if hasattr(layer, 'encoder_attn'):
                attns.append(layer.encoder_attn)
            for attn in attns:
                for proj in (attn.q_proj, attn.k_proj, attn.v_proj,
                             attn.out_proj):
                    proj.weight.normal_(0.0, 0.45)
                    proj.bias.normal_(0.0, 0.2)
            layer.fc1.weight.normal_(0.0, 0.7)
            layer.fc1.bias.normal_(0.0, 0.3)
            layer.fc2.weight.normal_(0.0, 0.4)
            layer.fc2.bias.normal_(0.0, 0.2)
            norms = [layer.self_attn_layer_norm, layer.final_layer_norm]
            if hasattr(layer, 'encoder_attn_layer_norm'):
                norms.append(layer.encoder_attn_layer_norm)
            for norm in norms:
                norm.weight.normal_(1.0, 0.25)
                norm.bias.normal_(0.0, 0.2)
    model.final_logits_bias.normal_(0.0, 0.6)
model = model.double().eval()

# Real HF checkpoints drop the tied/static duplicates: encoder/decoder
# embed_tokens and lm_head alias shared (_tied_weights_keys), and the
# SINUSOIDAL embed_positions tables are _keys_to_ignore_on_save (the
# importer regenerates them from the formula).
drop = {
    'model.encoder.embed_tokens.weight',
    'model.decoder.embed_tokens.weight',
    'model.encoder.embed_positions.weight',
    'model.decoder.embed_positions.weight',
    'lm_head.weight',
}
sd = {k: v.to(torch.float32).clone().contiguous()
      for k, v in model.state_dict().items() if k not in drop}
save_file(sd, 'tests/fixtures/tiny_marian.safetensors')
with open('tests/fixtures/tiny_marian_config.json', 'w') as f:
    json.dump(cfg_dict, f, indent=1)

enc_hidden, logits = [], []
with torch.no_grad():
    for es, ds in zip(enc_sequences, dec_sequences):
        enc_ids = torch.tensor([es])
        dec_ids = torch.tensor([ds])
        enc_hidden.append(
            model.model.encoder(input_ids=enc_ids).last_hidden_state[0]
            .tolist())
        logits.append(
            model(input_ids=enc_ids,
                  decoder_input_ids=dec_ids).logits[0].tolist())
with open('tests/fixtures/tiny_marian_logits.json', 'w') as f:
    json.dump({'enc_sequences': enc_sequences,
               'dec_sequences': dec_sequences,
               'enc_hidden': enc_hidden, 'logits': logits}, f)
print(f'wrote tiny_marian.safetensors ({len(sd)} tensors) + config + oracle')
for k in sorted(sd):
    print(f'  {k} {list(sd[k].shape)}')

# ---- fixture self-checks: every quirk must be visible in the oracle ----
import copy

enc_ids = torch.tensor([enc_sequences[0]])
dec_ids = torch.tensor([dec_sequences[0]])
with torch.no_grad():
    base = model(input_ids=enc_ids, decoder_input_ids=dec_ids).logits

    # 1. The saved embed_positions table (regenerated by the importer)
    # must match Marian's documented half-split layout: column c < d/2 is
    # sin(pos / 10000^(2c/d)), column d/2 + c is cos(pos / 10000^(2c/d)).
    tab = model.model.encoder.embed_positions.weight.cpu().numpy()
    ref = np.zeros((MAX_POS, D_MODEL))
    for pos in range(MAX_POS):
        for c in range(D_MODEL // 2):
            ref[pos, c] = math.sin(pos / 10000 ** (2 * c / D_MODEL))
            ref[pos, D_MODEL // 2 + c] = math.cos(
                pos / 10000 ** (2 * c / D_MODEL))
    assert np.abs(tab - ref).max() < 1e-6, 'unexpected sinusoid layout'
    print('half-split sinusoidal layout check passed')

    # 2. The positions must matter (zeroing both tables moves the logits)
    # - an importer that forgets them FAILS parity.
    nopos = copy.deepcopy(model)
    nopos.model.encoder.embed_positions.weight.zero_()
    nopos.model.decoder.embed_positions.weight.zero_()
    d = (nopos(input_ids=enc_ids, decoder_input_ids=dec_ids).logits -
         base).abs().max().item()
    assert d > 1e-2, f'positions had no effect ({d})'
    print(f'sinusoidal-position effect on logits: max |diff| = {d:.4f}')

    # 3. swish vs relu (and vs exact gelu) must be distinguishable above
    # the 1e-4 parity gate - the wrong FFN activation FAILS.
    for wrong in ('relu', 'gelu'):
        alt = copy.deepcopy(model)
        for stack_layers in (alt.model.encoder.layers,
                             alt.model.decoder.layers):
            for layer in stack_layers:
                layer.activation_fn = (torch.nn.ReLU() if wrong == 'relu'
                                       else torch.nn.GELU().double())
        d = (alt(input_ids=enc_ids, decoder_input_ids=dec_ids).logits -
             base).abs().max().item()
        assert d > 1e-3, f'swish vs {wrong} indistinguishable ({d})'
        print(f'swish-vs-{wrong} effect on logits: max |diff| = {d:.4f}')

    # 4. final_logits_bias must matter (a head that forgets to fold it in
    # FAILS parity).
    nb = copy.deepcopy(model)
    nb.final_logits_bias.zero_()
    d = (nb(input_ids=enc_ids, decoder_input_ids=dec_ids).logits -
         base).abs().max().item()
    assert d > 1e-1, f'final_logits_bias had no effect ({d})'
    print(f'final_logits_bias effect on logits: max |diff| = {d:.4f}')

    # 5. scale_embedding (sqrt(d_model) on the token embeddings, NOT on
    # the head) must matter.
    ns = copy.deepcopy(model)
    ns.model.encoder.embed_scale = 1.0
    ns.model.decoder.embed_scale = 1.0
    d = (ns(input_ids=enc_ids, decoder_input_ids=dec_ids).logits -
         base).abs().max().item()
    assert d > 1e-2, f'embed_scale had no effect ({d})'
    print(f'embed_scale effect on logits: max |diff| = {d:.4f}')

    # 6. The encoder input must reach the logits through cross-attention.
    other = torch.tensor([enc_sequences[1]])
    d = (model(input_ids=other, decoder_input_ids=dec_ids).logits -
         base).abs().max().item()
    assert d > 1e-2, f'encoder ids had no effect on logits ({d})'
    print(f'encoder-input effect on logits: max |diff| = {d:.4f}')

    # 7. Decoder self-attention must be CAUSAL: changing a LATER decoder
    # token must not change EARLIER logit rows.
    dec2 = dec_ids.clone()
    dec2[0, -1] = (dec2[0, -1] + 1) % (VOCAB - 2) + 1
    l2 = model(input_ids=enc_ids, decoder_input_ids=dec2).logits
    d_early = (l2[0, :-1] - base[0, :-1]).abs().max().item()
    assert d_early < 1e-9, f'decoder attention is not causal ({d_early})'
    print('decoder causality check passed')

    # 8. Every Linear is BIASED (the Marian convention - the opposite of
    # T5) and the biases are nonzero, so a bias-dropping import FAILS.
    for m in model.modules():
        if isinstance(m, torch.nn.Linear) and m is not model.lm_head:
            assert m.bias is not None, 'unexpected bias-free Linear'
            assert m.bias.abs().max().item() > 1e-3, 'all-zero Linear bias'
    print('biased-Linear check passed')

    # 9. POST-norm: the block output must be exactly LayerNorm(...) - its
    # per-token mean is the norm bias mean, not free as in pre-norm. Checked
    # structurally above (forward source); here assert the encoder output
    # changes when the LAST block's final_layer_norm bias shifts (a pre-norm
    # wiring would norm before the residual and dilute the shift).
    pn = copy.deepcopy(model)
    pn.model.encoder.layers[-1].final_layer_norm.bias += 1.0
    eh = pn.model.encoder(input_ids=enc_ids).last_hidden_state
    eh_base = model.model.encoder(input_ids=enc_ids).last_hidden_state
    d = (eh - eh_base - 1.0).abs().max().item()
    assert d < 1e-9, f'encoder output is not post-normed ({d})'
    print('post-norm placement check passed')
print('all fixture self-checks passed')
